### PR TITLE
Bugfix - Test if InstalledScriptInfos folder exists and create if needed

### LINKED ISSUE #1540: Install-PSResource Failing with Scripts on Ubuntu 22.04
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://www.powershellgallery.com/packages/Microsoft.PowerShell.PSResourceGet)
- [X] Search the existing issues.

### Steps to reproduce

Hello! I am experiencing a bug with PSRG 1.0.1 where scripts seemingly won't install on Ubuntu 22.04. This seems to happen with multiple scripts, but I used Assert-SameFile from https://www.powershellgallery.com/packages/Assert-SameFile/1.1.0 and tried it with PowerShell 7.4.1 on Windows 11 22H2, macOS 14.2.1, and Ubuntu 22.04, and only Ubuntu is showing this error.

After testing, it seems that running one of the two the below (depending on the scope you are trying to install with) before trying to install a script is an effective workaround:
```
mkdir -p ~/.local/share/powershell/Scripts/InstalledScriptInfos
mkdir -p /usr/local/share/powershell/Scripts/InstalledScriptInfos
```

### Expected behavior

```console
(taken from successful test on Windows 11 22h2)
PS C:\Users\nate> Install-PSResource Assert-SameFile

Untrusted repository
You are installing the modules from an untrusted repository. If you trust this repository, change its Trusted value by
running the Set-PSResourceRepository cmdlet. Are you sure you want to install the PSResource from 'PSGallery'?
[Y] Yes  [A] Yes to All  [N] No  [L] No to All  [S] Suspend  [?] Help (default is "N"): a
WARNING: The installation path for the script does not currently appear in the CurrentUser path environment variable. To make the script discoverable, add the script installation path, C:\Users\nate\Documents\PowerShell\Scripts, to the environment PATH variable.
PS C:\Users\nate> Get-InstalledPSResource -Name Assert-SameFile

Name            Version Prerelease Repository Description
----            ------- ---------- ---------- -----------
Assert-SameFile 1.1.0              PSGallery  This script automates one typical test scenario, it compares the sample …

PS C:\Users\nate>
```

### Actual behavior

```console
PS /home/vscode> Install-PSResource Assert-SameFile

Untrusted repository
You are installing the modules from an untrusted repository. If you trust this repository, change its Trusted value by running the 
Set-PSResourceRepository cmdlet. Are you sure you want to install the PSResource from 'PSGallery'?
[Y] Yes  [A] Yes to All  [N] No  [L] No to All  [S] Suspend  [?] Help (default is "N"): a
Install-PSResource: Unable to successfully install package 'Assert-SameFile': 'Could not find a part of the path '/home/vscode/.local/share/powershell/Scripts/InstalledScriptInfos/Assert-SameFile_InstalledScriptInfo.xml'.'
Install-PSResource: Operation is not valid due to the current state of the object.
Install-PSResource: Package(s) 'Assert-SameFile' could not be installed from repository 'PSGallery'.
PS /home/vscode>
```

### Error details

```console
Exception             : 
    Type    : Microsoft.PowerShell.PSResourceGet.UtilClasses.ResourceNotFoundException
    Message : Package(s) 'Assert-SameFile' could not be installed from repository 'PSGallery'.
    HResult : -2146233088
TargetObject          : Microsoft.PowerShell.PSResourceGet.Cmdlets.InstallPSResource
CategoryInfo          : InvalidData: (Microsoft.PowerShel…s.InstallPSResource:InstallPSResource) [Install-PSResource], ResourceNotFoundException
FullyQualifiedErrorId : InstallPackageFailure,Microsoft.PowerShell.PSResourceGet.Cmdlets.InstallPSResource
InvocationInfo        : 
    MyCommand        : Install-PSResource
    ScriptLineNumber : 1
    OffsetInLine     : 1
    HistoryId        : 10
    Line             : Install-PSResource Assert-SameFile
    Statement        : Install-PSResource Assert-SameFile
    PositionMessage  : At line:1 char:1
                       + Install-PSResource Assert-SameFile
                       + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    InvocationName   : Install-PSResource
    CommandOrigin    : Internal
ScriptStackTrace      : at <ScriptBlock>, <No file>: line 1
PipelineIterationInfo :
```

### Environment data

```powershell
ModuleType Version    PreRelease Name                                ExportedCommands
---------- -------    ---------- ----                                ----------------
Binary     1.0.1                 Microsoft.PowerShell.PSResourceGet  {Find-PSResource, Get-InstalledPSResource, Get-PSResourceRepository, Get-PSS…

Key   : PSVersion
Value : 7.4.1
Name  : PSVersion


Key   : PSEdition
Value : Core
Name  : PSEdition


Key   : GitCommitId
Value : 7.4.1
Name  : GitCommitId


Key   : OS
Value : Ubuntu 22.04.3 LTS
Name  : OS


Key   : Platform
Value : Unix
Name  : Platform


Key   : PSCompatibleVersions
Value : {1.0, 2.0, 3.0, 4.0…}
Name  : PSCompatibleVersions


Key   : PSRemotingProtocolVersion
Value : 2.3
Name  : PSRemotingProtocolVersion


Key   : SerializationVersion
Value : 1.1.0.1
Name  : SerializationVersion


Key   : WSManStackVersion
Value : 3.0
Name  : WSManStackVersion
```

### Visuals

_No response_

### PR DESCRIPTION
**Pull request by anamnavi**
Install-PSResource code was not checking if the InstalledScriptInfos folder existed, would try to use that path regardless and throw an uncaught error. This PR makes a fix to ensure the folder exists.

Fixes #1540 
# PR Summary

## PR Checklist

- [ ] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [ ] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [ ] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [ ] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.
- **[Breaking changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)**
    - [ ] None
    - **OR**
    - [ ] [Documentation needed]()
        - [ ] Issue filed: 
- **User-facing changes**
    - [ ] Not Applicable
    - **OR**
    - [ ] [Documentation needed]()
        - [ ] Issue filed: 
- **Testing - New and feature**
    - [ ] N/A or can only be tested interactively
    - **OR**
    - [ ] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
- **Tooling**
    - [ ] I have considered the user experience from a tooling perspective and don't believe tooling will be impacted.
    - **OR**
    - [ ] I have considered the user experience from a tooling perspective and enumerated concerns in the summary.

### CODE REVIEW

File: src/code/InstallHelper.cs [hunk 1]
```diff
@@ -488,12 +488,21 @@ private List<PSResourceInfo> FilterByInstalledPkgs(List<PSResourceInfo> packages
...
             else
             {
-                var scriptXML = pkgInfo.Name + "_InstalledScriptInfo.xml";
+                string scriptInfoFolderPath = Path.Combine(installPath, "InstalledScriptInfos");
+                string scriptXML = pkgInfo.Name + "_InstalledScriptInfo.xml";
+                string scriptXmlFilePath = Path.Combine(scriptInfoFolderPath, scriptXML);
                 if (!_savePkg)
                 {
+                    // Need to ensure "InstalledScriptInfos directory exists
+                    if (!Directory.Exists(Path.Combine(installPath, "InstalledScriptInfos")))
```
Comment (adityapatwardhan) [inline src/code/InstallHelper.cs]:
```suggestion
                    if (!Directory.Exists(scriptInfoFolderPath))

```

File: src/code/InstallHelper.cs [hunk 2]
```diff
@@ -488,12 +488,21 @@ private List<PSResourceInfo> FilterByInstalledPkgs(List<PSResourceInfo> packages
...
+                    }
+
                     // Need to delete old xml files because there can only be 1 per script
-                    _cmdletPassedIn.WriteVerbose(string.Format("Checking if path '{0}' exists: ", File.Exists(Path.Combine(installPath, "InstalledScriptInfos", scriptXML))));
-                    if (File.Exists(Path.Combine(installPath, "InstalledScriptInfos", scriptXML)))
+                    _cmdletPassedIn.WriteVerbose(string.Format("Checking if path '{0}' exists: '{1}'", scriptXmlFilePath, File.Exists(scriptXmlFilePath)));
+                    if (File.Exists(scriptXmlFilePath))
                     {
                         _cmdletPassedIn.WriteVerbose("Deleting script metadata XML");
                         File.Delete(Path.Combine(installPath, "InstalledScriptInfos", scriptXML));
```
Comment (adityapatwardhan) [inline src/code/InstallHelper.cs]:
```suggestion
                        File.Delete(Path.Combine(scriptInfoFolderPath, scriptXML));

```

**Review by adityapatwardhan — CHANGES_REQUESTED** [review]

**Review by adityapatwardhan — APPROVED** [review]

**Review by alerickson — APPROVED** [review]
