### PR TITLE
Uninstall and Get-Installed prerelease support for Version parameter

### LINKED ISSUE #83: Non-Prerelease Modules do not install over Prerelease versions without -force
The new prerelease support allows for prerelease naming of the package, but that doesn't reflect at all on PowerShell's versioning.

If I install module foo with a version of 2.0.0-beta1 (and powershell version 2.0.0), then later try to install foo 2.0.0, the second module install will silently fail.

## Expected Behavior
Installing the released version of a module should supercede the prerelease version.

(this would likely also impact other pre-release versions - i.e. upgrading from beta1 to beta2)

## Current Behavior
Attempting to install the released version over a pre-release fails silently.  

 ## Steps to Reproduce (for bugs)
```powershell
register-PSModuleRepository -name PreReleaseTest -SourceLocation https://www.myget.org/F/usepowershell/api/v2 
install-module PSConfAsia -allowprerelease -maximumversion 2.0.0-alpha-Repository PreReleaseTest -scope CurrentUser

## Print the version from PSGetModuleInfo
## Note the 2.0.0-alpha
([xml](cat ~\Documents\WindowsPowerShell\Modules\PSConfAsia\2.0.0\PSGetModuleInfo.xml -raw)).SelectNodes("//*[@N='NormalizedVersion']").'#text'

install-module PSConfAsia --maximumversion 2.0.0 -repository PreReleaseTest -scope CurrentUser

## Print the version from PSGetModuleInfo
## Still alpha
([xml](cat ~\Documents\WindowsPowerShell\Modules\PSConfAsia\2.0.0\PSGetModuleInfo.xml -raw)).SelectNodes("//*[@N='NormalizedVersion']").'#text'

install-module PSConfAsia --maximumversion 2.0.0 -repository PreReleaseTest -scope CurrentUser -force

## Print the version from PSGetModuleInfo
## How we have the release version
([xml](cat ~\Documents\WindowsPowerShell\Modules\PSConfAsia\2.0.0\PSGetModuleInfo.xml -raw)).SelectNodes("//*[@N='NormalizedVersion']").'#text'

```

```PowerShell

> $PSVersionTable

 LoECDA-PS > $PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.1.16299.98
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.16299.98
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

> Get-Module -ListAvailable PowerShellGet,PackageManagement

    Directory: C:\Users\stmuraws\Documents\WindowsPowerShell\Modules


ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Script     1.1.7.0    PackageManagement                   {Find-Package, Get-Package, Get-PackageProvider, Get-PackageSource...}
Script     1.6.0      PowerShellGet                       {Install-Module, Find-Module, Save-Module, Update-Module...}


    Directory: C:\Program Files\WindowsPowerShell\Modules


ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Binary     1.0.0.1    PackageManagement                   {Find-Package, Get-Package, Get-PackageProvider, Get-PackageSource...}
Script     1.0.0.1    PowerShellGet                       {Install-Module, Find-Module, Save-Module, Update-Module...}
```

### LINKED ISSUE #348: Can't downgrade prerelease version using find | install
I updated to PSReadlLine 2.2.0-beta2 but on my system, it has some serious perf issues and when I start an admin Windows Terminal, none of my history is available.  So I want to downgrade to beta1.  I can remove beta2 but my first attempt to install beta1 failed:
```
> Find-PSResource psreadline -Prerelease -Version 2.2.0-beta1 | Install-PSResource
Install-PSResource: Unable to cast object of type 'System.Version' to type 'NuGet.Versioning.NuGetVersion'.
```
Seems like that should work.  I did get the following to work:
```
Install-PSResource PSReadLine -Prerelease -Version 2.2.0-beta1
```
Which makes the `find | install` failure that much more puzzling.

### LINKED ISSUE #365: Uninstall-Module shouldn't require -AllowPrerelease when a prerelease version is being uninstalled.
## Steps to reproduce

```powershell
$moduleName = 'PSReadLine'
$prereleaseVersion = '2.2.0-beta2'

# Install with -AllowPrerelease
Install-Module -Force -AllowPrerelease $moduleName -RequiredVersion $prereleaseVersion

try {
  { Uninstall-Module -ErrorAction Stop $moduleName -RequiredVersion $prereleaseVersion } | Should -not -Throw
}
finally {
 # Uninstalling only succeeds with -AllowPrerelease
 Uninstall-Module -AllowPrerelease $moduleName  -RequiredVersion $prereleaseVersion 
}
```

## Expected behavior

The test should pass.

## Actual behavior

The test fails, because `-AllowPrerelease` is unexpectedly required.

```none
Expected no exception to be thrown, but an exception 
"The '-AllowPrerelease' parameter must be specified when using the Prerelease string in MinimumVersion, MaximumVersion, or RequiredVersion." 
was thrown
```

## Environment data

```none
PowerShell Core 7.2.0-preview.5
```

### PR DESCRIPTION
**Pull request by anamnavi**
# PR Summary

Add prerelease support for Uninstall-PSResource and Get-InstalledPSResource, so that a prerelease version module isn't obtained when the version part alone is provided, we look into the PSGetModuleInfo.xml file and verify that is the correct version with prerelease label specifically. 

## PR Context

Part of bug fixes for preview 12 release
resolves #365 , resolves #83, resolves #348
screenshot of #83 working:
image

screenshot of #348 working:
image

## PR Checklist

- [x] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [x] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.
- **[Breaking changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)**
    - [ ] None
    - **OR**
    - [ ] [Documentation needed]()
        - [ ] Issue filed: 
- **User-facing changes**
    - [ ] Not Applicable
    - **OR**
    - [ ] [Documentation needed]()
        - [ ] Issue filed: 
- **Testing - New and feature**
    - [ ] N/A or can only be tested interactively
    - **OR**
    - [x] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
- **Tooling**
    - [ ] I have considered the user experience from a tooling perspective and don't believe tooling will be impacted.
    - **OR**
    - [ ] I have considered the user experience from a tooling perspective and enumerated concerns in the summary.

### CODE REVIEW

File: src/code/GetInstalledPSResource.cs [hunk 1]
```diff
@@ -59,7 +60,8 @@ protected override void BeginProcessing()
             {
                 _versionRange = VersionRange.All;
             }
-            else if (!Utils.TryParseVersionOrVersionRange(Version, out _versionRange))
+            else if (!Utils.TryParseVersionOrVersionRange(version: Utils.GetVersionWithoutPrerelease(Version, out _prereleaseLabels),
```
Comment (PaulHigin) [inline src/code/GetInstalledPSResource.cs]: version: parameter should go on next line.

File: src/code/GetInstalledPSResource.cs [hunk 2]
```diff
@@ -130,8 +132,16 @@ protected override void ProcessRecord()
             }
 
             GetHelper getHelper = new GetHelper(this);
+            string[] versionRangeParts = _versionRange.ToString().Trim(new char []{'[', ']', '(', ')'}).Split(',');
```
Comment (PaulHigin) [inline src/code/GetInstalledPSResource.cs]: Include comment demonstrating what expected version range looks like and what parts are returned.  It would be better to have a private method that parses the version range and returns a concrete type that contains expected version parts.

File: src/code/GetInstalledPSResource.cs [hunk 3]
```diff
@@ -130,8 +132,16 @@ protected override void ProcessRecord()
             }
 
             GetHelper getHelper = new GetHelper(this);
+            string[] versionRangeParts = _versionRange.ToString().Trim(new char []{'[', ']', '(', ')'}).Split(',');
+
             foreach (PSResourceInfo pkg in getHelper.FilterPkgPaths(namesToSearch, _versionRange, _pathsToSearch))
             {
+                if ((_versionRange != VersionRange.All) && (!String.IsNullOrEmpty(versionRangeParts[0]) && pkg.Version.ToString().StartsWith(versionRangeParts[0]) && !String.Equals(pkg.PrereleaseLabel, _prereleaseLabels[0], StringComparison.InvariantCultureIgnoreCase)) ||
```
Comment (PaulHigin) [inline src/code/GetInstalledPSResource.cs]: This should be in a private method along with comments to demonstrate expected form.  Why are there multiple prerelease labels.  Will the array always contain two items?  Private method should guarantee version/prerelease contains all expected internal items.

File: src/code/UninstallPSResource.cs [hunk 4]
```diff
@@ -202,6 +208,11 @@ private bool UninstallModuleHelper(string pkgPath, string pkgName, out ErrorReco
             errRecord = null;
             var successfullyUninstalledPkg = false;
 
+            if (!CheckIfPrerelease(isModule: true, pkgName: pkgName, pkgPath: pkgPath))
```
Comment (PaulHigin) [inline src/code/UninstallPSResource.cs]: We never uninstall prerelease packages?  Should have a comment.

File: src/code/UninstallPSResource.cs [hunk 5]
```diff
@@ -332,6 +348,26 @@ private bool CheckIfDependency(string pkgName, out ErrorRecord errRecord)
             }
             return false;
         }
+        
+        private bool CheckIfPrerelease(bool isModule, string pkgPath, string pkgName)
+        {
+            string PSGetModuleInfoFilePath = isModule ? Path.Combine(pkgPath, "PSGetModuleInfo.xml") : Path.Combine(Path.GetDirectoryName(pkgPath), "InstalledScriptInfos", pkgName + "_InstalledScriptInfo.xml");
+            if (!PSResourceInfo.TryRead(PSGetModuleInfoFilePath, out PSResourceInfo psGetInfo, out string errorMsg))
```
Comment (PaulHigin) [inline src/code/UninstallPSResource.cs]: Should error be reported?

File: src/code/UninstallPSResource.cs [hunk 6]
```diff
@@ -332,6 +348,26 @@ private bool CheckIfDependency(string pkgName, out ErrorRecord errRecord)
...
+        
+        private bool CheckIfPrerelease(bool isModule, string pkgPath, string pkgName)
+        {
+            string PSGetModuleInfoFilePath = isModule ? Path.Combine(pkgPath, "PSGetModuleInfo.xml") : Path.Combine(Path.GetDirectoryName(pkgPath), "InstalledScriptInfos", pkgName + "_InstalledScriptInfo.xml");
+            if (!PSResourceInfo.TryRead(PSGetModuleInfoFilePath, out PSResourceInfo psGetInfo, out string errorMsg))
+            {
+                return false;
+            }
+
+            string[] versionRangeParts = _versionRange.ToString().Trim(new char []{'[', ']', '(', ')'}).Split(',');
```
Comment (PaulHigin) [inline src/code/UninstallPSResource.cs]: Duplicate code should go into a single private method.

File: src/code/UninstallPSResource.cs [hunk 7]
```diff
@@ -332,6 +348,26 @@ private bool CheckIfDependency(string pkgName, out ErrorRecord errRecord)
...
+            if ((_versionRange != VersionRange.All) &&
+                (psGetInfo.Version.ToString().StartsWith(versionRangeParts[0]) && !String.Equals(psGetInfo.PrereleaseLabel, _prereleaseLabels[0], StringComparison.InvariantCultureIgnoreCase)) ||
```
Comment (PaulHigin) [inline src/code/UninstallPSResource.cs]: Again, it is not clear what this is doing.  Comment should clearly explain what is expected for prerelease versions.

File: src/code/Utils.cs [hunk 8]
```diff
@@ -116,6 +116,51 @@ public static string[] GetStringArray(ArrayList list)
...
+                prereleaseLabels = prereleaseLabelList.ToArray();
+                return versionString.Substring(0, 1) + String.Join(",", versionOnlyParts) + versionString.Substring(versionString.Length-1);
+            }
+
+            // just a specific version
+            prereleaseLabels = new string[]{""};
+            return GetVersionWithoutPrereleaseHelper(versionString, out prereleaseLabels[0]);
+        }
+
+        public static string GetVersionWithoutPrereleaseHelper(string versionString, out string prereleaseLabel)
```
Comment (PaulHigin) [inline src/code/Utils.cs]: We should stop using 'helper' in method names.  Should just be a description of what the method does.

File: src/code/Utils.cs [hunk 9]
```diff
@@ -116,6 +116,51 @@ public static string[] GetStringArray(ArrayList list)
...
         #region Version methods
 
+        public static string GetVersionWithoutPrerelease(string versionString, out string[] prereleaseLabels)
+        {
+            List<String> prereleaseLabelList = new List<string>();
+            if (versionString.StartsWith("[") || versionString.StartsWith("("))
+            {
+                // this is a version range, i.e: [3.0.0-preview, ] or (2.9.0, 3.0.0-preview)
+                // not supported, bc you can't install versions with same core version part side by side (3.0.0, 3.0.0-preview)
+                string[] versionRangeParts = versionString.Trim(new char[]{'[', ']', '(', ')'}).Split(',');
```
Comment (PaulHigin) [inline src/code/Utils.cs]: Duplicate code.

**Review by PaulHigin — CHANGES_REQUESTED** [review]

File: src/code/UninstallPSResource.cs (hunk 5 above)
Comment (anamnavi) [reply src/code/UninstallPSResource.cs]: we write a verbose message with error now, and skip to next package

File: src/code/GetHelper.cs [hunk 10]
```diff
@@ -112,16 +112,15 @@ public IEnumerable<String> FilterPkgPathsByVersion(VersionRange versionRange, Li
                     foreach (string versionPath in versionsDirs)
                     {
                         _cmdletPassedIn.WriteVerbose(string.Format("Searching through package version path: '{0}'", versionPath));
-                        DirectoryInfo dirInfo = new DirectoryInfo(versionPath);
-
-                        // if the version is not valid, we'll just skip it and output a debug message
-                        if (!NuGetVersion.TryParse(dirInfo.Name, out NuGetVersion dirAsNugetVersion))
+                        if(!Utils.GetVersionFromPSGetModuleInfoFile(installedPkgPath: versionPath,
```
Comment (PaulHigin) [inline src/code/GetHelper.cs]: Maybe name should be: `GetVersionForInstallPath`?

File: src/code/UninstallPSResource.cs [hunk 11]
```diff
@@ -110,7 +109,9 @@ protected override void ProcessRecord()
                     break;
 
                 case InputObjectParameterSet:
-                    if (!Utils.TryParseVersionOrVersionRange(InputObject.Version.ToString(), out _versionRange))
+                    string inputObjectPrereleaseLabel = InputObject.PrereleaseLabel;
+                    string inputObjectVersion = String.IsNullOrEmpty(inputObjectPrereleaseLabel) ? InputObject.Version.ToString() : Utils.GetNormalizedVersionString(versionString: InputObject.Version.ToString(), prerelease: inputObjectPrereleaseLabel);
```
Comment (PaulHigin) [inline src/code/UninstallPSResource.cs:113]: Please add vertical space for readability.

File: src/code/Utils.cs [hunk 12]
```diff
@@ -180,6 +180,45 @@ public static string[] GetStringArray(ArrayList list)
...
+            bool isModule,
+            PSCmdlet cmdletPassedIn,
+            out NuGetVersion pkgNuGetVersion)
+        {
+            // for Modules, installedPkgPath will look like this:
+            // ./PowerShell/Modules/test_module/3.0.0
+            // for Scripts, installedPkgPath will look like this:
+            // ./PowerShell/Scripts/test_script.ps1
+
+            string pkgName = String.Empty;
```
Comment (PaulHigin) [inline src/code/Utils.cs]: Could use the ternary operator here.

File: src/code/Utils.cs [hunk 13]
```diff
@@ -180,6 +180,45 @@ public static string[] GetStringArray(ArrayList list)
...
+            if (!isModule)
+            {
+                pkgName = Utils.GetInstalledPackageName(installedPkgPath);
+            }
+
+            string PSGetModuleInfoFilePath = isModule ? Path.Combine(installedPkgPath, "PSGetModuleInfo.xml") : Path.Combine((new DirectoryInfo(installedPkgPath).Parent).FullName, "InstalledScriptInfos", $"{pkgName}_InstalledScriptInfo.xml");
```
Comment (PaulHigin) [inline src/code/Utils.cs]: Variable name should be camel case, and should not include 'module' since the path can be for either module or script package.  Maybe `packageInfoFilePath`?

File: src/code/Utils.cs [hunk 14]
```diff
@@ -180,6 +180,45 @@ public static string[] GetStringArray(ArrayList list)
...
+            if (!PSResourceInfo.TryRead(PSGetModuleInfoFilePath, out PSResourceInfo psGetInfo, out string errorMsg))
+            {
+                cmdletPassedIn.WriteVerbose(String.Format("The PSGetModuleInfo.xml file found at location: {0} cannot be parsed due to {1}", PSGetModuleInfoFilePath, errorMsg));
```
Comment (PaulHigin) [inline src/code/Utils.cs]: Message is not quite correct.  Could be PSGetModuleInfo.xml or _InstalledScriptInfo.xml file.

File: src/code/Utils.cs [hunk 15]
```diff
@@ -180,6 +180,45 @@ public static string[] GetStringArray(ArrayList list)
...
+                NuGetVersion.TryParse(installedPkgPath, out pkgNuGetVersion);
```
Comment (PaulHigin) [inline src/code/Utils.cs]: Is there any reason to return parsed version from path if `false` is returned?  Please comment to indicate what the returned boolean means.

**Review by PaulHigin — CHANGES_REQUESTED** [review]

File: src/code/Utils.cs (hunk 13 above)
Comment (anamnavi) [reply src/code/Utils.cs]: renamed to `packageInfoXMLFilePath`

File: src/code/Utils.cs (hunk 15 above)
Comment (anamnavi) [reply src/code/Utils.cs]: Good point, thanks! If false is returned that means the PSGetModuleInfo.xml or InstalledScriptInfo.xml file could not be parsed properly, or, that the version could not be parsed into a NuGetVersion. I've added a comment to explain this. In GetHelper the caller method skips the package if false is returned as expected. So I changed this called method to not parse a version if we're returning false; instead we'll set it to null.

**Review by PaulHigin — APPROVED** [review]
LGTM

File: src/code/GetHelper.cs [hunk 16]
```diff
@@ -150,17 +149,17 @@ public IEnumerable<String> FilterPkgPathsByVersion(VersionRange versionRange, Li
                         // check to make sure it's within the version range.
                         // script versions will be parsed from the script xml file
                         PSResourceInfo scriptInfo = OutputPackageObject(pkgPath, _scriptDictionary);
-                        if (scriptInfo == null)
+                        if(!Utils.GetVersionForInstallPath(installedPkgPath: pkgPath,
+                            isModule: false,
+                            cmdletPassedIn: _cmdletPassedIn,
+                            out NuGetVersion dirAsNugetVersion))
```
Comment (alerickson) [inline src/code/GetHelper.cs]: Maybe the varianble name `dirAsNugetVersion` should be changed to `pkgNuGetVersion` or something like that?

File: src/code/GetHelper.cs [hunk 17]
```diff
@@ -150,17 +149,17 @@ public IEnumerable<String> FilterPkgPathsByVersion(VersionRange versionRange, Li
...
+                            // skip to next iteration of the loop
+                            yield return pkgPath;
                         }
 
-                        if (!NuGetVersion.TryParse(scriptInfo.Version.ToString(), out NuGetVersion scriptVersion))
-                        {
-                            _cmdletPassedIn.WriteVerbose(string.Format("Version '{0}' could not be properly parsed from the script metadata file from the script installed at '{1}'", scriptInfo.Version.ToString(), scriptInfo.InstalledLocation));
-                        }
-                        else if (versionRange.Satisfies(scriptVersion))
+                        _cmdletPassedIn.WriteVerbose(string.Format("Directory parsed as NuGet version: '{0}'", dirAsNugetVersion));
```
Comment (alerickson) [inline src/code/GetHelper.cs]: And this could be changed to something like `Package version parsed as NuGet version: ` or something of that nature.

**Review by alerickson — APPROVED** [review]
