### PR TITLE
Publish should find prerelease dependency versions.

### LINKED ISSUE #1250: Publishing module that requires prerelease module fails
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://www.powershellgallery.com/packages/PSResourceGet)
- [X] Search the existing issues.

### Steps to reproduce

If you try to publish a module that requires a prerelease module it will fail during publishing.

Job logs: https://github.com/anypackage/psresourceget/actions/runs/5523381734/jobs/10074329386

### Expected behavior

```console
# Published
```

### Actual behavior

```console
Publish-PSResource $module.ModuleBase -ApiKey $env:NUGET_KEY
     |  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Dependency 'Microsoft.PowerShell.PSResourceGet' was not found in
     | repository 'PSGallery'.  Make sure the dependency is published to the
     | repository before publishing this module.
```

### Error details

_No response_

### Environment data

```powershell
beta22
```

### Visuals

_No response_

### PR DESCRIPTION
**Pull request by anamnavi**
When finding dependency packages for Publish, detect prerelease versions of the dependency packages if specific version is not specified.

Additionally, when writing tests we found that LocalServerApi.InstallVersion() File.Exists() call fails for Linux as Linux is case sensitive platform. Using wildcard matching should allow the (dep) package to be found. Currently it is not able to be found.

Also undoes changes of PR #1276 as that solution towards the case sensitivity issue for Linux was not sufficient/correct.

# PR Summary

## PR Context

Resolves #1250 

## PR Checklist

- [x] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [x] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.
- **[Breaking changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)**
    - [ ] None
    - **OR**
    - [ ] [Documentation needed]()
        - [ ] Issue filed: 
- **User-facing changes**
    - [ ] Not Applicable
    - **OR**
    - [ ] [Documentation needed]()
        - [ ] Issue filed: 
- **Testing - New and feature**
    - [ ] N/A or can only be tested interactively
    - **OR**
    - [ ] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
- **Tooling**
    - [ ] I have considered the user experience from a tooling perspective and don't believe tooling will be impacted.
    - **OR**
    - [ ] I have considered the user experience from a tooling perspective and enumerated concerns in the summary.

### CODE REVIEW

File: src/code/LocalServerApiCalls.cs [hunk 1]
```diff
@@ -256,19 +256,31 @@ public override Stream InstallVersion(string packageName, string version, out Er
...
 
-            if (fs == null)
+            if (String.IsNullOrEmpty(pkgVersionPath))
             {
-                errRecord = new ErrorRecord(new LocalResourceEmpty("The contents of the package file for specified resource was empty or invalid"), "InstallVersionFailure", ErrorCategory.ResourceUnavailable, this);
+                errRecord = new ErrorRecord(new LocalResourceEmpty($"'{packageName}' is not present in repository"), "InstallNameFailure", ErrorCategory.ResourceUnavailable, this);
+            }
+            else
+            {
+                fs = new FileStream(pkgVersionPath, FileMode.Open, FileAccess.Read);
```
Comment (adityapatwardhan) [inline src/code/LocalServerApiCalls.cs:285]: do we need a try catch?

File: src/code/PublishPSResource.cs [hunk 2]
```diff
@@ -856,10 +853,11 @@ private bool CheckDependenciesExist(Hashtable dependencies, string repositoryNam
 
                 // Search for and return the dependency if it's in the repository.
                 FindHelper findHelper = new FindHelper(_cancellationToken, this, _networkCredential);
-                bool depPrerelease = depVersion.Contains("-");
 
                 var repository = new[] { repositoryName };
-                var dependencyFound = findHelper.FindByResourceName(depName, ResourceType.Module, versionRange, nugetVersion, versionType, depVersion, depPrerelease, null, repository, false);
+                // Note: we set prerelease argument for FindByResourceName() to true because if no version is specified we want latest version (including prerelease).
+                // If version is specified it will get that one. There is also no way to specify a prerelease flag with RequiredModules hashtable of dependency so always try to get latest version.
+                var dependencyFound = findHelper.FindByResourceName(depName, ResourceType.Module, versionRange, nugetVersion, versionType, depVersion, true, null, repository, false);
```
Comment (adityapatwardhan) [inline src/code/PublishPSResource.cs]: use named parameters for true, null and false

**Review by adityapatwardhan — CHANGES_REQUESTED** [review]

**Review by adityapatwardhan — APPROVED** [review]
