### PR TITLE
Bugfix - Correctly match package names from local repos

### LINKED ISSUE #1641: Error parsing version from package name for filesystem-based repository
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://www.powershellgallery.com/packages/Microsoft.PowerShell.PSResourceGet)
- [X] Search the existing issues.

### Steps to reproduce

```powershell
PS> Get-PSResourceRepository -Name LocalPSResource

Name            Uri                        Trusted Priority
----            ---                        ------- --------
LocalPSResource file:///D:/LocalPSResource True    100

PS> Find-PSResource -Name Documentarian -Repository LocalPSResource -Debug -Verbose
DEBUG: In FindPSResource::ProcessResourceNameParameterSet()
DEBUG: Filtering package name(s) on wildcards
DEBUG: In FindHelper::FindByResourceName()
DEBUG: Parameters passed in >>> Name: 'Documentarian'; ResourceType: 'None'; VersionRange: ''; NuGetVersion: ''; VersionType: 'NoVersion'; Version: ''; Prerelease: 'False'; Tag: ''; Repository: 'LocalPSResource'; IncludeDependencies 'False'
DEBUG: Searching through repository 'LocalPSResource'
DEBUG: In FindHelper::SearchByNames()
DEBUG: No version specified, package name is specified
DEBUG: In LocalServerApiCalls::FindName()
DEBUG: In LocalServerApiCalls::FindNameHelper()
DEBUG: In LocalServerApiCalls::GetInfoFromFileName()
DEBUG: Version parsed as '0.0.1'
DEBUG: In LocalServerApiCalls::GetInfoFromFileName()
DEBUG: Version parsed as '0.0.2'
DEBUG: In LocalServerApiCalls::GetInfoFromFileName()
DEBUG: Version parsed as ''
Find-PSResource: Could not parse version devx.0.0.1 from file Documentarian.DevX.0.0.1.nupkg

PS> dir D:\LocalPSResource\

    Directory: D:\LocalPSResource

Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
-a---           3/12/2024 10:49 AM          25126 Documentarian.0.0.1.nupkg
-a---           4/22/2024  3:41 PM          25358 Documentarian.0.0.2.nupkg
-a---           3/12/2024 10:49 AM          37419 Documentarian.DevX.0.0.1.nupkg
-a---           3/12/2024 10:49 AM          30318 Documentarian.MarkdownBuilder.0.0.1.nupkg
-a---           3/12/2024 10:49 AM          13310 Documentarian.MicrosoftDocs.0.0.2.nupkg
-a---           3/12/2024 10:49 AM          60297 Documentarian.ModuleAuthor.0.0.2.nupkg
-a---           3/12/2024 10:49 AM          24868 Documentarian.Vale.0.2.0.nupkg
-a---           7/27/2022  8:38 PM          10530 DocumentWMI.0.1.0-beta1.nupkg
-a---            4/2/2024  8:33 AM          13673 JDHTools.1.0.0.nupkg
-a---            8/9/2023  7:56 PM           5541 ManageIssues.1.0.2.nupkg
-a---           7/27/2022  6:59 PM          79342 Microsoft.PowerShell.WhatsNew.0.4.0.nupkg
-a---           9/15/2023  1:40 PM         181572 platyps.0.14.2.nupkg
-a---           9/15/2023  1:43 PM          19383 psini.3.1.3.nupkg
-a---          12/15/2023 12:46 PM           8308 PSStyle.1.1.7.nupkg
-a---           4/16/2024  9:43 PM           4951 sdwheeler.ADUtils.1.0.0.nupkg
-a---            2/5/2024  8:57 AM           7030 sdwheeler.ContentUtils.1.0.0.nupkg
-a---           4/16/2024  9:43 PM           7150 sdwheeler.ContentUtils.1.0.1.nupkg
-a---           4/16/2024  9:43 PM           3637 sdwheeler.CryptoTools.1.0.0.nupkg
-a---           3/19/2024 10:09 AM           3475 sdwheeler.DataConversion.1.0.1.nupkg
-a---           4/16/2024  9:43 PM           3119 sdwheeler.DataConversion.1.0.2.nupkg
-a---           7/28/2022  8:34 AM          13721 sdwheeler.DocsHelpers.1.0.5.nupkg
-a---           4/16/2024  9:43 PM           9787 sdwheeler.EssentialUtils.1.0.3.nupkg
-a---           4/16/2024  9:43 PM           5956 sdwheeler.FileManagement.1.0.2.nupkg
-a---           4/16/2024  9:43 PM          13107 sdwheeler.GitTools.1.1.2.nupkg
-a---           4/15/2024 10:16 AM           7755 sdwheeler.PSUtils.1.0.2.nupkg
-a---           4/16/2024  9:43 PM           7915 sdwheeler.PSUtils.1.0.3.nupkg
-a---           4/16/2024  9:43 PM           5559 sdwheeler.ROBTools.1.0.0.nupkg
-a---           4/16/2024  9:43 PM           3900 sdwheeler.SqliteTools.1.0.0.nupkg
-a---           4/16/2024  9:43 PM           5389 sdwheeler.SystemUtils.1.0.0.nupkg
-a---           4/16/2024  9:44 PM           5829 sdwheeler.Themes.0.0.1.nupkg
-a---           9/18/2023  2:26 PM         205104 Yayaml.0.1.1.nupkg
```

### Expected behavior

```console
Name          Version Prerelease Repository      Description
----          ------- ---------- ----------      -----------
Documentarian 0.0.2              LocalPSResource Collection of general purpose functions for working with Markdown doc…
```

### Actual behavior

```console
I get the error:

Find-PSResource: Could not parse version devx.0.0.1 from file Documentarian.DevX.0.0.1.nupkg
```

### Error details

_No response_

### Environment data

```powershell
PS> gmo Microsoft.PowerShell.PSResourceGet

ModuleType Version    PreRelease Name                                ExportedCommands
---------- -------    ---------- ----                                ----------------
Binary     1.0.2                 Microsoft.PowerShell.PSResourceGet  {Find-PSResource, Get-InstalledPSResource, Get-PS…

PS> $PSVersionTable.PSVersion

Major  Minor  Patch  PreReleaseLabel BuildLabel
-----  -----  -----  --------------- ----------
7      5      0      preview.2
```

### Visuals

_No response_

### PR DESCRIPTION
**Pull request by anamnavi**
# PR Summary
There was a bug in how we parse out name and version information from package file names when performing search against local repositories. 

If you have a package `test` and test.submodule` present in the local repository their files will look like this:
```
`test.1.0.0.nupkg`
`test.submodule.1.0.0.nupkg`
```
We used WildCardPattern class before, with pattern `{packageName}.*" which would pick up both packages if package `test` was searched for. The code logic then assumed the rest of the part of the name would be the version so it would search through both package names and try to parse `submodule.1.0.0` into a version. 

This fix uses Regex more accurately created for the package name and to expect a version right after the name, not text.

## PR Context
Fixes #1641 #1648 

## PR Checklist

- [x] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [x] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.
- **[Breaking changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)**
    - [ ] None
    - **OR**
    - [ ] [Documentation needed]()
        - [ ] Issue filed: 
- **User-facing changes**
    - [ ] Not Applicable
    - **OR**
    - [ ] [Documentation needed]()
        - [ ] Issue filed: 
- **Testing - New and feature**
    - [ ] N/A or can only be tested interactively
    - **OR**
    - [x] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
- **Tooling**
    - [ ] I have considered the user experience from a tooling perspective and don't believe tooling will be impacted.
    - **OR**
    - [ ] I have considered the user experience from a tooling perspective and enumerated concerns in the summary.

### CODE REVIEW

File: src/code/LocalServerApiCalls.cs [hunk 1]
```diff
@@ -255,32 +255,48 @@ private FindResults FindNameHelper(string packageName, string[] tags, bool inclu
             FindResults findResponse = new FindResults();
             errRecord = null;
 
-            WildcardPattern pkgNamePattern = new WildcardPattern($"{packageName}.*", WildcardOptions.IgnoreCase);
             NuGetVersion latestVersion = new NuGetVersion("0.0.0.0");
             String latestVersionPath = String.Empty;
             string actualPkgName = packageName;
 
+            string regexPattern = $"{packageName}" + @".\d+\.\d+\.\d+(?:-\w+|.\d)*.nupkg";
```
Comment (alerickson) [inline src/code/LocalServerApiCalls.cs:263]: Can you add a comment explaining what this regex is looking for?

File: src/code/LocalServerApiCalls.cs [hunk 2]
```diff
@@ -255,32 +255,48 @@ private FindResults FindNameHelper(string packageName, string[] tags, bool inclu
...
+            Regex rx = new Regex(regexPattern, RegexOptions.Compiled | RegexOptions.IgnoreCase);
+
+            _cmdletPassedIn.WriteDebug($"pattern is: {regexPattern}");
```
Comment (alerickson) [inline src/code/LocalServerApiCalls.cs]: Should this be removed or is this included for general debugging?

File: src/code/LocalServerApiCalls.cs [hunk 3]
```diff
@@ -255,32 +255,48 @@ private FindResults FindNameHelper(string packageName, string[] tags, bool inclu
...
+
             foreach (string path in Directory.GetFiles(Repository.Uri.LocalPath))
             {
                 string packageFullName = Path.GetFileName(path);
+                MatchCollection matches = rx.Matches(packageFullName);
+                if (matches.Count == 0)
+                {
```
Comment (alerickson) [inline src/code/LocalServerApiCalls.cs:272]: It might be nice to add logging here saying no matches were found.

**Review by alerickson — APPROVED** [review]
Looks good, just added a couple comments

File: src/code/LocalServerApiCalls.cs (hunk 2 above)
Comment (anamnavi) [reply src/code/LocalServerApiCalls.cs]: for general debugging, but I've updated the debug message to be clearer.

File: src/code/LocalServerApiCalls.cs (hunk 3 above)
Comment (anamnavi) [reply src/code/LocalServerApiCalls.cs:272]: this condition just means that as we're iterating through the files, if a file's name doesn't match it'll be reflected as `matches.Count == 0` or even as `groups.Count == 0`. So if we added logging here it may be a lot of logs. We do have a condition after this iteration of files completes, where if the package file path `latestVersionPath` is empty and not set then we write an error.
