### PR TITLE
Detect empty V2 server responses at ServerApiCall level instead of ResponseUtil level

### LINKED ISSUE #1349: For V2Server (PSGallery) Package Not Found should be detected at ServerApiCall level
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://www.powershellgallery.com/packages/PSResourceGet)
- [X] Search the existing issues.

### Steps to reproduce

Currently for V2 server protocol repositories (i.e PSGallery) when a package is not found an XML response lacking package metadata is returned from the ServerApiCall level, and then in the ResponseUtil level ConvertToPSResourceResult() detects and returns an error. This is different from how all other repositories' servers detect and return error, and the XML response for V2 Server actually contains a "Count" element that has a value of 0 when the package is not found. This change will improve consistency and make for easier/cleaner error handling.

### Expected behavior

```console
Behavior will remain same as current/actual but request for code change. The FullyQualifiedErrorId will change though.
```

### Actual behavior

```console
Behavior will remain same as current/actual but request for code change. The FullyQualifiedErrorId will change though.
```

### Error details

_No response_

### Environment data

```powershell
platform agnostic.
```

### Visuals

_No response_

### PR DESCRIPTION
**Pull request by anamnavi**
Previously for scenarios where a package could not be found on the server, V2ServerApiCall responses returned were non-empty XML responses, so an error indicating package not found was not detected and errRecord was not populated. This meant that at the ResponseUtil level the response would try to be converted to a PSResourceInfo and throw an error and we would catch and error handle in FindHelper for the "Package not found" scenario.

This PR changes that. The parameter `$inlinecount=allpages` is added to the V2 request so that `count` is always returned in the response. This is used to detect a "Package not found" scenario and then an errRecord with FullyQualifiedErrorId "PackageNotFound" is returned and detected in FindHelper to properly error write or write verbose.

Changes were also made to the other ServerApiCalls classes to consistently return errRecords with FullyQualifiedErrorId "PackageNotFound" when a package isn't found.

# PR Summary

## PR Context
Resolves #1349

## PR Checklist

- [ ] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [ ] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [ ] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [ ] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.
- **[Breaking changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)**
    - [ ] None
    - **OR**
    - [ ] [Documentation needed]()
        - [ ] Issue filed: 
- **User-facing changes**
    - [ ] Not Applicable
    - **OR**
    - [ ] [Documentation needed]()
        - [ ] Issue filed: 
- **Testing - New and feature**
    - [ ] N/A or can only be tested interactively
    - **OR**
    - [ ] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
- **Tooling**
    - [ ] I have considered the user experience from a tooling perspective and don't believe tooling will be impacted.
    - **OR**
    - [ ] I have considered the user experience from a tooling perspective and enumerated concerns in the summary.

### CODE REVIEW

File: src/code/V2ServerAPICalls.cs [hunk 1]
```diff
@@ -291,8 +306,26 @@ public override FindResults FindName(string packageName, bool includePrerelease,
             // We need to explicitly add 'Id eq <packageName>' whenever $filter is used, otherwise arbitrary results are returned.
             string idFilterPart = $" and Id eq '{packageName}'";
             string typeFilterPart = GetTypeFilterForRequest(type);
-            var requestUrlV2 = $"{Repository.Uri}/FindPackagesById()?id='{packageName}'&$filter={prerelease}{idFilterPart}{typeFilterPart}";
+            var requestUrlV2 = $"{Repository.Uri}/FindPackagesById()?id='{packageName}'&$inlinecount=allpages&$filter={prerelease}{idFilterPart}{typeFilterPart}";
             string response = HttpRequestCall(requestUrlV2, out errRecord);
+            if (errRecord != null)
+            {
+                return new FindResults(stringResponse: new string[]{ string.Empty }, hashtableResponse: emptyHashResponses, responseType: v2FindResponseType);
```
Comment (alerickson) [inline src/code/V2ServerAPICalls.cs]:
```suggestion
                return new FindResults(stringResponse: Utils.EmptyStrArray, hashtableResponse: emptyHashResponses, responseType: v2FindResponseType);                
```

File: src/code/V2ServerAPICalls.cs [hunk 2]
```diff
@@ -291,8 +306,26 @@ public override FindResults FindName(string packageName, bool includePrerelease,
...
             string response = HttpRequestCall(requestUrlV2, out errRecord);
+            if (errRecord != null)
+            {
+                return new FindResults(stringResponse: new string[]{ string.Empty }, hashtableResponse: emptyHashResponses, responseType: v2FindResponseType);                
+            }
+
+            int count = GetCountFromResponse(response, out errRecord);
+            if (errRecord != null)
+            {
+                return new FindResults(stringResponse: new string[]{ string.Empty }, hashtableResponse: emptyHashResponses, responseType: v2FindResponseType);
```
Comment (alerickson) [inline src/code/V2ServerAPICalls.cs]:
```suggestion
                return new FindResults(stringResponse: Utils.EmptyStrArray, hashtableResponse: emptyHashResponses, responseType: v2FindResponseType);                
```

File: src/code/V2ServerAPICalls.cs [hunk 3]
```diff
@@ -318,9 +351,26 @@ public override FindResults FindNameWithTag(string packageName, string[] tags, b
                 tagFilterPart += $" and substringof('{tag}', Tags) eq true";
             }
 
-            var requestUrlV2 = $"{Repository.Uri}/FindPackagesById()?id='{packageName}'&$filter={prerelease}{idFilterPart}{typeFilterPart}{tagFilterPart}";
-
+            var requestUrlV2 = $"{Repository.Uri}/FindPackagesById()?id='{packageName}'&$inlinecount=allpages&$filter={prerelease}{idFilterPart}{typeFilterPart}{tagFilterPart}";
             string response = HttpRequestCall(requestUrlV2, out errRecord);
+            if (errRecord != null)
+            {
+                return new FindResults(stringResponse: new string[]{ string.Empty }, hashtableResponse: emptyHashResponses, responseType: v2FindResponseType);
```
Comment (alerickson) [inline src/code/V2ServerAPICalls.cs]:
```suggestion
                return new FindResults(stringResponse: Utils.EmptyStrArray, hashtableResponse: emptyHashResponses, responseType: v2FindResponseType);                
```

File: src/code/V2ServerAPICalls.cs [hunk 4]
```diff
@@ -318,9 +351,26 @@ public override FindResults FindNameWithTag(string packageName, string[] tags, b
...
             string response = HttpRequestCall(requestUrlV2, out errRecord);
+            if (errRecord != null)
+            {
+                return new FindResults(stringResponse: new string[]{ string.Empty }, hashtableResponse: emptyHashResponses, responseType: v2FindResponseType);                
+            }
+
+            int count = GetCountFromResponse(response, out errRecord);
+            if (errRecord != null)
+            {
+                return new FindResults(stringResponse: new string[]{ string.Empty }, hashtableResponse: emptyHashResponses, responseType: v2FindResponseType);
```
Comment (alerickson) [inline src/code/V2ServerAPICalls.cs]:
```suggestion
                return new FindResults(stringResponse: Utils.EmptyStrArray, hashtableResponse: emptyHashResponses, responseType: v2FindResponseType);                
```

File: src/code/V2ServerAPICalls.cs [hunk 5]
```diff
@@ -473,9 +545,26 @@ public override FindResults FindVersion(string packageName, string version, Reso
             // We need to explicitly add 'Id eq <packageName>' whenever $filter is used, otherwise arbitrary results are returned.
             string idFilterPart = $" and Id eq '{packageName}'";
             string typeFilterPart = GetTypeFilterForRequest(type);
-            var requestUrlV2 = $"{Repository.Uri}/FindPackagesById()?id='{packageName}'&$filter= NormalizedVersion eq '{version}'{idFilterPart}{typeFilterPart}";
-
+            var requestUrlV2 = $"{Repository.Uri}/FindPackagesById()?id='{packageName}'&$inlinecount=allpages&$filter= NormalizedVersion eq '{version}'{idFilterPart}{typeFilterPart}";
             string response = HttpRequestCall(requestUrlV2, out errRecord);
+            if (errRecord != null)
+            {
+                return new FindResults(stringResponse: new string[]{ string.Empty }, hashtableResponse: emptyHashResponses, responseType: v2FindResponseType);
```
Comment (alerickson) [inline src/code/V2ServerAPICalls.cs]:
```suggestion
                return new FindResults(stringResponse: Utils.EmptyStrArray, hashtableResponse: emptyHashResponses, responseType: v2FindResponseType);                
```

File: src/code/V2ServerAPICalls.cs [hunk 6]
```diff
@@ -473,9 +545,26 @@ public override FindResults FindVersion(string packageName, string version, Reso
...
             string response = HttpRequestCall(requestUrlV2, out errRecord);
+            if (errRecord != null)
+            {
+                return new FindResults(stringResponse: new string[]{ string.Empty }, hashtableResponse: emptyHashResponses, responseType: v2FindResponseType);                
+            }
+
+            int count = GetCountFromResponse(response, out errRecord);
+            if (errRecord != null)
+            {
+                return new FindResults(stringResponse: new string[]{ string.Empty }, hashtableResponse: emptyHashResponses, responseType: v2FindResponseType);
```
Comment (alerickson) [inline src/code/V2ServerAPICalls.cs]:
```suggestion
                return new FindResults(stringResponse: Utils.EmptyStrArray, hashtableResponse: emptyHashResponses, responseType: v2FindResponseType);                
```

File: src/code/V2ServerAPICalls.cs [hunk 7]
```diff
@@ -496,9 +585,26 @@ public override FindResults FindVersionWithTag(string packageName, string versio
                 tagFilterPart += $" and substringof('{tag}', Tags) eq true";
             }
 
-            var requestUrlV2 = $"{Repository.Uri}/FindPackagesById()?id='{packageName}'&$filter= NormalizedVersion eq '{version}'{idFilterPart}{typeFilterPart}{tagFilterPart}";
-
+            var requestUrlV2 = $"{Repository.Uri}/FindPackagesById()?id='{packageName}'&$inlinecount=allpages&$filter= NormalizedVersion eq '{version}'{idFilterPart}{typeFilterPart}{tagFilterPart}";
             string response = HttpRequestCall(requestUrlV2, out errRecord);
+            if (errRecord != null)
+            {
+                return new FindResults(stringResponse: new string[]{ string.Empty }, hashtableResponse: emptyHashResponses, responseType: v2FindResponseType);
```
Comment (alerickson) [inline src/code/V2ServerAPICalls.cs]:
```suggestion
                return new FindResults(stringResponse: Utils.EmptyStrArray, hashtableResponse: emptyHashResponses, responseType: v2FindResponseType);                
```

File: src/code/V2ServerAPICalls.cs [hunk 8]
```diff
@@ -496,9 +585,26 @@ public override FindResults FindVersionWithTag(string packageName, string versio
...
             string response = HttpRequestCall(requestUrlV2, out errRecord);
+            if (errRecord != null)
+            {
+                return new FindResults(stringResponse: new string[]{ string.Empty }, hashtableResponse: emptyHashResponses, responseType: v2FindResponseType);                
+            }
+
+            int count = GetCountFromResponse(response, out errRecord);
+            if (errRecord != null)
+            {
+                return new FindResults(stringResponse: new string[]{ string.Empty }, hashtableResponse: emptyHashResponses, responseType: v2FindResponseType);
```
Comment (alerickson) [inline src/code/V2ServerAPICalls.cs]:
```suggestion
                return new FindResults(stringResponse: Utils.EmptyStrArray, hashtableResponse: emptyHashResponses, responseType: v2FindResponseType);                
```

**Review by alerickson — APPROVED** [review]
