### PR TITLE
Install-PSResource: Installation path for scripts not included in environment PATH variable

### LINKED ISSUE #709: Install-psresource does not install PSGalleryScripts
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://www.powershellgallery.com/packages/PowerShellGet)
- [X] Search the existing issues.

### Steps to reproduce

This issue only affects scripts that are published to the powershell gallery, or psgalleryscripts.  For the purposes of this issue, the example script I will use is "Export-PSObjectToINI,"  You can use "Find-Psresource" to find the "Export-PSObjectToINI" script hosted in the powershell gallery easily:
2022-07-14 15_26_48-Administrator_ Windows PowerShell ISE
But when trying to install the script using "install-psresource", the module doesn't return any error or output, which would typically indicate the resource was successfully installed, but attempting to run the script reveals that it was not installed at all:

2022-07-14 15_29_36-Administrator_ Windows PowerShell ISE

This is a problem that needs to be resolved, as the only way to install scripts from the powershell gallery as of now is to import the old version of powershellget and use the "install-script" command.  

### Expected behavior

```console
The script should have successfully installed on the local machine.
```

### Actual behavior

```console
The script was not installed on the local machine
```

### Error details

```console
No error to be had.
```

### Environment data

```powershell
get-module powershellget; $PSVersionTable

ModuleType Version    Name                                ExportedCommands                                                                                               
---------- -------    ----                                ----------------                                                                                               
Binary     3.0.14     PowerShellGet                       {Find-PSResource, Get-PSResource, Get-PSResourceRepository, Install-PSResource...}                             

Key   : PSVersion
Value : 5.1.22000.653
Name  : PSVersion


Key   : PSEdition
Value : Desktop
Name  : PSEdition


Key   : PSCompatibleVersions
Value : {1.0, 2.0, 3.0, 4.0...}
Name  : PSCompatibleVersions


Key   : BuildVersion
Value : 10.0.22000.653
Name  : BuildVersion


Key   : CLRVersion
Value : 4.0.30319.42000
Name  : CLRVersion


Key   : WSManStackVersion
Value : 3.0
Name  : WSManStackVersion


Key   : PSRemotingProtocolVersion
Value : 2.3
Name  : PSRemotingProtocolVersion


Key   : SerializationVersion
Value : 1.1.0.1
Name  : SerializationVersion
```

### Visuals

_No response_

### PR DESCRIPTION
**Pull request by anamnavi**
# PR Summary

Installing a script with Install-PSResource happens successfully however the scripts installation path isn't added to the environment PATH variable as was in V2. 

Upon discussion from the team, we feel it is best for consistency across Windows and Linux to not attempt to modify the user's/machine's environment PATH variable, rather emit a warning indicating how the user could do so and specifying the path they would need to add. The script is still installed successfully, but the user would have to modify the environment PATH variable for discoverability.

## PR Context

Resolves #709 

## PR Checklist

- [x] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [x] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.
- **[Breaking changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)**
    - [ ] None
    - **OR**
    - [ ] [Documentation needed]()
        - [ ] Issue filed: 
- **User-facing changes**
    - [ ] Not Applicable
    - **OR**
    - [ ] [Documentation needed]()
        - [ ] Issue filed: 
- **Testing - New and feature**
    - [ ] N/A or can only be tested interactively
    - **OR**
    - [ ] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
- **Tooling**
    - [ ] I have considered the user experience from a tooling perspective and don't believe tooling will be impacted.
    - **OR**
    - [ ] I have considered the user experience from a tooling perspective and enumerated concerns in the summary.

### CODE REVIEW

File: src/code/InstallHelper.cs [hunk 1]
```diff
@@ -575,6 +575,24 @@ private List<PSResourceInfo> FilterByInstalledPkgs(List<PSResourceInfo> packages
...
                     _cmdletPassedIn.WriteVerbose(String.Format("Successfully installed package '{0}' to location '{1}'", pkg.Name, installPath));
                     pkgsSuccessfullyInstalled.Add(pkg);
+
+                    if (!isModule)
+                    {
+                        // Add Scripts install path to Path environment variable so that it can be ran without prepending the path
+                        if (!Environment.GetEnvironmentVariable("PATH").Contains(installPath))
+                        {
+                            // need to add Scripts install path
+                            string currentPathEnvVarValue = Environment.GetEnvironmentVariable("PATH", EnvironmentVariableTarget.User);
```
Comment (alerickson) [inline src/code/InstallHelper.cs]: I think we should also check the scope and accommodate for AllUsers scope as well, similar to what v2 does here: https://github.com/PowerShell/PowerShellGetv2/blob/5aba7531f526b6e60b2757c36799995597b6dcec/src/PowerShellGet/private/functions/ValidateAndSet-PATHVariableIfUserAccepts.ps1#L34

**Comment by alerickson** [comment]
V2 prompts for user to accept/confirm the action before setting the environment variable.  I'm not a fan of prompts but since it's changing the env var, I think it might be important to include (see: https://github.com/PowerShell/PowerShellGetv2/blob/5aba7531f526b6e60b2757c36799995597b6dcec/src/PowerShellGet/PSGet.Resource.psd1#L222 for the v2 prompt)

File: src/code/InstallHelper.cs [hunk 2]
```diff
@@ -575,6 +575,24 @@ private List<PSResourceInfo> FilterByInstalledPkgs(List<PSResourceInfo> packages
 
                     _cmdletPassedIn.WriteVerbose(String.Format("Successfully installed package '{0}' to location '{1}'", pkg.Name, installPath));
                     pkgsSuccessfullyInstalled.Add(pkg);
+
+                    if (!isModule)
+                    {
+                        // Add Scripts install path to Path environment variable so that it can be ran without prepending the path
+                        if (!Environment.GetEnvironmentVariable("PATH").Contains(installPath))
```
Comment (alerickson) [inline src/code/InstallHelper.cs]: Also looks like v2 checks that that both `installPath` and `installPath\` are not in `PATH` before adding `installPath` to `PATH` (see: https://github.com/PowerShell/PowerShellGetv2/blob/5aba7531f526b6e60b2757c36799995597b6dcec/src/PowerShellGet/private/functions/ValidateAndSet-PATHVariableIfUserAccepts.ps1#L71)

File: src/code/InstallHelper.cs (hunk 1 above)
Comment (alerickson) [reply src/code/InstallHelper.cs]: It also looks like on top of adding the scope specific target, it is also adding the path to the env var for the current process (see: https://github.com/PowerShell/PowerShellGetv2/blob/5aba7531f526b6e60b2757c36799995597b6dcec/src/PowerShellGet/private/functions/ValidateAndSet-PATHVariableIfUserAccepts.ps1#L110)

**Review by alerickson — CHANGES_REQUESTED** [review]

File: src/code/InstallHelper.cs (hunk 1 above)
Comment (anamnavi) [reply src/code/InstallHelper.cs]: I added a check to accommodate for AllUsers scope, and to add the path to current process target.

File: src/code/InstallHelper.cs (hunk 2 above)
Comment (anamnavi) [reply src/code/InstallHelper.cs]: added this check, good catch thank you!

**Comment by alerickson** [comment]
This looks good to me!  Should be good once the tests are resolved.

File: src/code/InstallHelper.cs [hunk 3]
```diff
@@ -35,6 +35,8 @@ internal class InstallHelper
         public const string PSScriptFileExt = ".ps1";
         private const string MsgRepositoryNotTrusted = "Untrusted repository";
         private const string MsgInstallUntrustedPackage = "You are installing the modules from an untrusted repository. If you trust this repository, change its Trusted value by running the Set-PSResourceRepository cmdlet. Are you sure you want to install the PSresource from '{0}' ?";
+        private const string ScriptPATHPromptQuery = "Your system has not been configured with a default script installation path yet, which means you can only run a script by specifying the full path to the script file. This action places the script into the folder '{0}', and adds that folder to your PATH environment variable. Do you want to add the script installation path '{0}' to the PATH environment variable?";
```
Comment (PaulHigin) [inline src/code/InstallHelper.cs]:
```suggestion
        private const string ScriptPATHPromptQuery = "The installation path for the script does not appear in the {scope} path environment variable. Do you want the script installation path, {path}, added to the {scope} PATH environment variable?";

```

File: src/code/InstallHelper.cs [hunk 4]
```diff
@@ -580,6 +587,43 @@ private List<PSResourceInfo> FilterByInstalledPkgs(List<PSResourceInfo> packages
 
                     _cmdletPassedIn.WriteVerbose(String.Format("Successfully installed package '{0}' to location '{1}'", pkg.Name, installPath));
                     pkgsSuccessfullyInstalled.Add(pkg);
+
+                    if (!_savePkg && !isModule)
+                    {
+                        // Add Scripts install path to Path environment variable so that it can be ran without prepending the path
```
Comment (PaulHigin) [inline src/code/InstallHelper.cs]:
```suggestion
                        // Add Scripts install path to Path environment variable so that it can be discovered.

```

File: src/code/InstallHelper.cs [hunk 5]
```diff
@@ -580,6 +587,43 @@ private List<PSResourceInfo> FilterByInstalledPkgs(List<PSResourceInfo> packages
 
                     _cmdletPassedIn.WriteVerbose(String.Format("Successfully installed package '{0}' to location '{1}'", pkg.Name, installPath));
                     pkgsSuccessfullyInstalled.Add(pkg);
+
+                    if (!_savePkg && !isModule)
+                    {
+                        // Add Scripts install path to Path environment variable so that it can be ran without prepending the path
+                        string envPathValue = Environment.GetEnvironmentVariable("PATH"); // todo anam- does this get all targets?
```
Comment (PaulHigin) [inline src/code/InstallHelper.cs]: This retrieves environment variable in the current process. We want to check that both process and scope PATH variables contain the path, and if not then update those paths.  We only need to prompt the user for non-process (scope) PATH variable changes.

File: src/code/InstallHelper.cs [hunk 6]
```diff
@@ -580,6 +587,43 @@ private List<PSResourceInfo> FilterByInstalledPkgs(List<PSResourceInfo> packages
 
                     _cmdletPassedIn.WriteVerbose(String.Format("Successfully installed package '{0}' to location '{1}'", pkg.Name, installPath));
                     pkgsSuccessfullyInstalled.Add(pkg);
+
+                    if (!_savePkg && !isModule)
+                    {
+                        // Add Scripts install path to Path environment variable so that it can be ran without prepending the path
+                        string envPathValue = Environment.GetEnvironmentVariable("PATH"); // todo anam- does this get all targets?
+                        string installPathwithBackSlash = installPath + "\\";
+                        if (!envPathValue.Contains(installPath) && !envPathValue.Contains(installPathwithBackSlash))
```
Comment (PaulHigin) [inline src/code/InstallHelper.cs]: This code is complex enough to be in its own private static method.  We also need error handling if the environment variable cannot be retrieved or set (access denied).  For example a non-Admin user will not be able to get/set machine scope variables.  Access error would probably happen during installation, but we still need to handle access errors here.

Comment (PaulHigin) [reply src/code/InstallHelper.cs]: The private method should also be able to override the user prompt via a `force` parameter.

File: test/InstallPSResource.Tests.ps1 [hunk 7]
```diff
@@ -181,32 +181,71 @@ Describe 'Test Install-PSResource for Module' {
...
     # Windows only
-    It "Install resource under no specified scope - Windows only" -Skip:(!(Get-IsWindows)) {
+    It "Install module resource under no specified scope - Windows only" -Skip:(!(Get-IsWindows)) {
         Install-PSResource -Name $testModuleName -Repository $PSGalleryName -TrustRepository 
         $pkg = Get-PSResource $testModuleName
         $pkg.Name | Should -Be $testModuleName
         $pkg.InstalledLocation.ToString().Contains("Documents") | Should -Be $true
     }
 
+    # Windows only
```
Comment (PaulHigin) [inline test/InstallPSResource.Tests.ps1]: We should also have tests that verify environment PATH variables exist (for non-interactive case, force case).

**Review by PaulHigin — CHANGES_REQUESTED** [review]

File: test/InstallPSResource.Tests.ps1 (hunk 7 above)
Comment (anamnavi) [reply test/InstallPSResource.Tests.ps1]: No longer applicable with warning based approach, so resolving.

**Review by PaulHigin — APPROVED** [review]
LGTM

**Review by alyssa1303 — APPROVED** [review]
LGTM too

**Review by alerickson — APPROVED** [review]
