### PR TITLE
Bugfix: Populate Includes Metadata for Package from Containerregistry Repository

### LINKED ISSUE #1845: Find-PSResource does not have any data in Include property for ContainerRegistry
### Prerequisites

- [x] Write a descriptive title.
- [x] Make sure you are able to repro it on the [latest released version](https://www.powershellgallery.com/packages/Microsoft.PowerShell.PSResourceGet)
- [x] Search the existing issues.

### Steps to reproduce

When querying for packages, Find-PSResource is missing the data in the Includes property. The data is found when using PSGallery repository.

### Expected behavior

```console
PS> $a = Find-PSResource -Name az.compute -Repository MAR
PS> $a.Includes

Cmdlet         : {Add-AzImageDataDisk, Add-AzVhd, Add-AzVMAdditionalUnattendContent, Add-AzVMDataDisk…}
Command        : {Add-AzImageDataDisk, Add-AzVhd, Add-AzVMAdditionalUnattendContent, Add-AzVMDataDisk…}
DscResource    : {}
Function       :
RoleCapability :
Workflow       :
```

### Actual behavior

```console
PS> $a = Find-PSResource -Name az.compute -Repository MAR
PS> $a.Includes

Cmdlet         : {}
Command        : {}
DscResource    : {}
Function       : {}
RoleCapability : {}
Workflow       : {}
```

### Error details

```console

```

### Environment data

```powershell
PS> Get-Module microsoft.powershell.psresourceget; $PSVersionTable | Format-Table

ModuleType Version    PreRelease Name                                ExportedCommands
---------- -------    ---------- ----                                ----------------
Binary     1.1.1                 Microsoft.PowerShell.PSResourceGet  {Compress-PSResource, Find-PSResource, Get-InstalledPSResource, Get-PSResourceRepository…}


Name                           Value
----                           -----
PSVersion                      7.5.2
PSEdition                      Core
GitCommitId                    7.5.2
OS                             Microsoft Windows 10.0.26100
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Visuals

Image

### PR DESCRIPTION
**Pull request by anamnavi**
Find-PSResource wasn't populating `Includes` metadata for a package retrieved from a ContainerRegistry repository, so updated the code in PSResourceInfo.cs to call the method to retrieve that metadata.
# PR Summary

## PR Context
Resolves #1845

## PR Checklist

- [x] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [x] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.
- **[Breaking changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)**
    - [ ] None
    - **OR**
    - [ ] [Documentation needed]()
        - [ ] Issue filed: 
- **User-facing changes**
    - [ ] Not Applicable
    - **OR**
    - [ ] [Documentation needed]()
        - [ ] Issue filed: 
- **Testing - New and feature**
    - [ ] N/A or can only be tested interactively
    - **OR**
    - [x] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
- **Tooling**
    - [ ] I have considered the user experience from a tooling perspective and don't believe tooling will be impacted.
    - **OR**
    - [ ] I have considered the user experience from a tooling perspective and enumerated concerns in the summary.

### CODE REVIEW

File: src/code/PSResourceInfo.cs [hunk 1]
```diff
@@ -1699,16 +1708,22 @@ private static ResourceType ParseHttpMetadataType(
...
         {
             // possible type combinations:
-            // M, C
-            // M, D
-            // M
-            // S
+                // M, C
+                // M, D
+                // M
+                // S
```
Comment (adityapatwardhan) [inline src/code/PSResourceInfo.cs]: extra spaces?

**Review by adityapatwardhan — APPROVED** [review]

**Review by adityapatwardhan — APPROVED** [review]
