### PR TITLE
Bugfix for Update cmdlet attempting to reinstall latest preview version

### LINKED ISSUE #464: Update-PSResource -Prerelease removes PowerShellGet 3.0
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://www.powershellgallery.com/packages/PowerShellGet)
- [X] Search the existing issues.

### Steps to reproduce

After installing PowerShellGet 3.0 Preview 11, run `Update-PSResource -Prerelease` removes itself.

### Expected behavior

```console
PSResources gets updated.
```

### Actual behavior

```console
PowerShellGet module's files gets removed.
```

### Error details

_No response_

### Environment data

```powershell
ModuleType Version    PreRelease Name                                ExportedCommands
---------- -------    ---------- ----                                ----------------
Binary     3.0.11     beta       PowerShellGet                       {Find-PSResource, Get-InstalledPSResource, Get-PSResourceRepository, Install-PSResource…}

Key   : PSVersion
Value : 7.2.0-preview.8
Name  : PSVersion


Key   : PSEdition
Value : Core
Name  : PSEdition


Key   : GitCommitId
Value : 7.2.0-preview.8
Name  : GitCommitId


Key   : OS
Value : Microsoft Windows 10.0.22000
Name  : OS


Key   : Platform
Value : Win32NT
Name  : Platform


Key   : PSCompatibleVersions
Value : {1.0, 2.0, 3.0, 4.0…}
Name  : PSCompatibleVersions


Key   : PSRemotingProtocolVersion
Value : 2.3
Name  : PSRemotingProtocolVersion


Key   : SerializationVersion
Value : 1.1.0.1
Name  : SerializationVersion


Key   : WSManStackVersion
Value : 3.0
Name  : WSManStackVersion
```

### Visuals

_No response_

### PR DESCRIPTION
**Pull request by anamnavi**
# PR Summary

Fix bug related to updating a prerelease version package. If the package has latest prerelease version, the discrepancy with System.Version and NuGetVersion instances used for latest version comparison was causing the latest preview version to be attempted to be reinstalled. With this fix it can detect correctly if it the latest version is the latest and not reinstall.

## PR Context

Resolves #464 #818 #749 #619 

## PR Checklist

- [x] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [x] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.
- **[Breaking changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)**
    - [ ] None
    - **OR**
    - [ ] [Documentation needed]()
        - [ ] Issue filed: 
- **User-facing changes**
    - [ ] Not Applicable
    - **OR**
    - [ ] [Documentation needed]()
        - [ ] Issue filed: 
- **Testing - New and feature**
    - [ ] N/A or can only be tested interactively
    - **OR**
    - [ ] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
- **Tooling**
    - [ ] I have considered the user experience from a tooling perspective and don't believe tooling will be impacted.
    - **OR**
    - [ ] I have considered the user experience from a tooling perspective and enumerated concerns in the summary.

### CODE REVIEW

**Review by alerickson — APPROVED** [review]

File: src/code/UpdatePSResource.cs [hunk 1]
```diff
@@ -354,7 +354,13 @@ protected override void EndProcessing()
                     continue;
                 }
 
-                if ((versionRange == VersionRange.All && repositoryPackage.Version > installedPackage.Version) ||
+                if (!NuGetVersion.TryParse(repositoryPackage.Version.ToString(), out NuGetVersion repositoryPackageNuGetVersion))
```
Comment (anamnavi) [inline src/code/UpdatePSResource.cs:357]:
```suggestion
// Using System.Version for comparison isn't consistent here, as repositoryPackage.Version (3.0.17.0) and installedVersion (3.017.-1) should refer to the same version but due to how System.Version handles last digit creates discrepancies.
                if (!NuGetVersion.TryParse(repositoryPackage.Version.ToString(), out NuGetVersion repositoryPackageNuGetVersion))

```

**Review by alyssa1303 — APPROVED** [review]

**Review by alyssa1303 — APPROVED** [review]
This might also fix this issue too #749
