### PR TITLE
Bug fix for version ranges with prerelease versions not returning the correct versions

### LINKED ISSUE #1235: Find-PSResource prerelease version ranges not correct
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://www.powershellgallery.com/packages/PSResourceGet)
- [X] Search the existing issues.

### Steps to reproduce

Version ranges with prerelease version are not returning the correct versions. As you can see from this version range `(2.0,2.1)` it should not return prerelease versions of 2.0.0 as that is older than 2.0.0 which I have excluded. Then it should be returning prerelease versions of 2.1.0 as those are valid in this range as they are older stable 2.1.0.

### Expected behavior

```console
Find-PSResource -Name PSReadLine -Version '(2.0,2.1)' -Prerelease

Name       Version Prerelease Repository Description
----       ------- ---------- ---------- -----------
PSReadLine 2.1.0   rc1        PSGallery  Great command line editing in the PowerShell console host
PSReadLine 2.1.0   beta2      PSGallery  Great command line editing in the PowerShell console host
PSReadLine 2.1.0   beta1      PSGallery  Great command line editing in the PowerShell console host
PSReadLine 2.0.4              PSGallery  Great command line editing in the PowerShell console host
PSReadLine 2.0.3              PSGallery  Great command line editing in the PowerShell console host
PSReadLine 2.0.2              PSGallery  Great command line editing in the PowerShell console host
PSReadLine 2.0.1              PSGallery  Great command line editing in the PowerShell console host
```

### Actual behavior

```console
Find-PSResource -Name PSReadLine -Version '(2.0,2.1)' -Prerelease

Name       Version Prerelease Repository Description
----       ------- ---------- ---------- -----------
PSReadLine 2.0.4              PSGallery  Great command line editing in the PowerShell console host
PSReadLine 2.0.3              PSGallery  Great command line editing in the PowerShell console host
PSReadLine 2.0.2              PSGallery  Great command line editing in the PowerShell console host
PSReadLine 2.0.1              PSGallery  Great command line editing in the PowerShell console host
PSReadLine 2.0.0   rc2        PSGallery  Great command line editing in the PowerShell console host
PSReadLine 2.0.0   rc1        PSGallery  Great command line editing in the PowerShell console host
PSReadLine 2.0.0   beta6      PSGallery  Great command line editing in the PowerShell console host
PSReadLine 2.0.0   beta5      PSGallery  Great command line editing in the PowerShell console host
PSReadLine 2.0.0   beta4      PSGallery  Great command line editing in the PowerShell console host
PSReadLine 2.0.0   beta3      PSGallery  Great command line editing in the PowerShell console host
PSReadLine 2.0.0   beta2      PSGallery  Great command line editing in the PowerShell console host
PSReadLine 2.0.0   beta1      PSGallery  Great command line editing in the PowerShell console host
```

### Error details

_No response_

### Environment data

```powershell
7.4-preview4
psresourceget beta22
```

### Visuals

_No response_

### PR DESCRIPTION
**Pull request by alerickson**
# PR Summary
Bug fix for version ranges with prerelease versions not returning the correct versions.

## PR Context
Resolves #1235 

## PR Checklist

- [x] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [x] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.
- **[Breaking changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)**
    - [x] None
    - **OR**
    - [ ] [Documentation needed]()
        - [ ] Issue filed: 
- **User-facing changes**
    - [x] Not Applicable
    - **OR**
    - [ ] [Documentation needed]()
        - [ ] Issue filed: 
- **Testing - New and feature**
    - [ ] N/A or can only be tested interactively
    - **OR**
    - [x] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
- **Tooling**
    - [x] I have considered the user experience from a tooling perspective and don't believe tooling will be impacted.
    - **OR**
    - [ ] I have considered the user experience from a tooling perspective and enumerated concerns in the summary.

### CODE REVIEW

File: src/code/V2ServerAPICalls.cs [hunk 1]
```diff
@@ -797,7 +797,14 @@ private string FindVersionGlobbing(string packageName, VersionRange versionRange
             if (versionRange.MaxVersion != null)
             {
                 string operation = versionRange.IsMaxInclusive ? "le" : "lt";
-                maxPart = String.Format(format, operation, $"'{versionRange.MaxVersion.ToNormalizedString()}'");
+                string maxString = $"{versionRange.MaxVersion.Major}.{versionRange.MaxVersion.Minor + 1}";
```
Comment (anamnavi) [inline src/code/V2ServerAPICalls.cs:802]: why do we add 1? (I might be missing something obvious but a comment may help here for the reason)

**Review by anamnavi — APPROVED** [review]
LGTM

File: src/code/V2ServerAPICalls.cs (hunk 1 above)
Comment (alerickson) [reply src/code/V2ServerAPICalls.cs:802]: I'll add a comment, we add 1 because we want to get all the prerelease versions for a version and unfortunately the gallery views that as > the stable version.
So if I'm searching for versions "(1.0.0, 3.0.0)" 3.0.0-prerelease should get returned but the gallery doesn't return it.  If we search for range "(1.0.0, 3.1.0)" we get the prerelease versions for 3.0.0 as well.  I'm also validating that whatever versions get returned are valid within the version range to validate it's an appropriate version for that range.
