### PR TITLE
Bug fix for saving Az dependencies

### LINKED ISSUE #1341: [Save-PSRessource] Strange behavior when PSGallery return error (HttpRequest)
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://www.powershellgallery.com/packages/PSResourceGet)
- [X] Search the existing issues.

### Steps to reproduce

The following command does nothing except delete files (see Visual) :
```powershell
 Save-PSResource -Name 'AZ' -Path C:\temp\CacheTemp\ -verbose
```
This problem seems to depend on the state of the PSGallery WEB server.

### Expected behavior

```console
Save the 'AZ' module or stop processing when a major error occurs.
```

### Actual behavior

```console
When executing processing, the WEB server triggers an exception, but Save-PSResource processing continues.
No module is saved in the indicated directory (which exists).
Save-PSResource with InvokeBuils works and loading AZ module via PSGallery interface works.
```

### Error details

```console
First error :

C:\temp> $error[-2]|select *


writeErrorStream      : True
PSMessageDetails      :
Exception             : System.Threading.Tasks.TaskCanceledException: Une tâche a été annulée.
                           à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
                           à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task
                        task)
                           à Microsoft.PowerShell.PSResourceGet.Cmdlets.V2ServerAPICalls.<SendV2RequestAsync>d__33.Move
                        Next()
                        --- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel
                        l'exception a été levée ---
                           à System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                           à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
                           à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task
                        task)
                           à Microsoft.PowerShell.PSResourceGet.Cmdlets.V2ServerAPICalls.HttpRequestCall(String
                        requestUrlV2, ErrorRecord& errRecord)
TargetObject          : Microsoft.PowerShell.PSResourceGet.Cmdlets.V2ServerAPICalls
CategoryInfo          : ConnectionError: (Microsoft.Power...2ServerAPICalls:V2ServerAPICalls) [Save-PSResource],
                        TaskCanceledException
FullyQualifiedErrorId : HttpRequestCallFailure,Microsoft.PowerShell.PSResourceGet.Cmdlets.SavePSResource
ErrorDetails          :
InvocationInfo        : System.Management.Automation.InvocationInfo
ScriptStackTrace      : à <ScriptBlock>, <Aucun fichier> : ligne 1
PipelineIterationInfo : {0, 1}


C:\temp> $error[-2].Exception|select *


Task              : System.Threading.Tasks.Task`1[System.Net.Http.HttpResponseMessage]
CancellationToken : System.Threading.CancellationToken
Message           : Une tâche a été annulée.
Data              : {}
InnerException    :
TargetSite        : Void ThrowForNonSuccess(System.Threading.Tasks.Task)
StackTrace        :    à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
                       à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                       à
                    Microsoft.PowerShell.PSResourceGet.Cmdlets.V2ServerAPICalls.<SendV2RequestAsync>d__33.MoveNext()
                    --- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a
                    été levée ---
                       à System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                       à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
                       à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                       à Microsoft.PowerShell.PSResourceGet.Cmdlets.V2ServerAPICalls.HttpRequestCall(String
                    requestUrlV2, ErrorRecord& errRecord)
HelpLink          :
Source            : mscorlib
HResult           : -2146233029

```

Second error :
```


writeErrorStream      : True
PSMessageDetails      :
Exception             : System.Net.Http.HttpRequestException: 'Une erreur s'est produite lors de la copie du contenu
                        vers un flux.' Request sent: 'https://www.powershellgallery.com/api/v2/FindPackagesById()?id='A
                        z.Accounts'&$orderby=NormalizedVersion%20desc&$inlinecount=allpages&$skip=0&$filter=IsPrereleas
                        e%20eq%20false%20and%20Id%20eq%20'Az.Accounts'%20and%20NormalizedVersion%20ge%20'2.10.2''
                        Inner exception: 'Réception d'un EOF inattendu ou de 0 octet du flux de transport.'
                           à Microsoft.PowerShell.PSResourceGet.Cmdlets.V2ServerAPICalls.<SendV2RequestAsync>d__33.Move
                        Next()
                        --- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel
                        l'exception a été levée ---
                           à System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                           à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task
                        task)
                           à Microsoft.PowerShell.PSResourceGet.Cmdlets.V2ServerAPICalls.HttpRequestCall(String
                        requestUrlV2, ErrorRecord& errRecord)
TargetObject          : Microsoft.PowerShell.PSResourceGet.Cmdlets.V2ServerAPICalls
CategoryInfo          : ConnectionError: (Microsoft.Power...2ServerAPICalls:V2ServerAPICalls) [Save-PSResource],
                        HttpRequestException
FullyQualifiedErrorId : HttpRequestCallFailure,Microsoft.PowerShell.PSResourceGet.Cmdlets.SavePSResource
ErrorDetails          :
InvocationInfo        : System.Management.Automation.InvocationInfo
ScriptStackTrace      : à <ScriptBlock>, <Aucun fichier> : ligne 1
PipelineIterationInfo : {0, 1}


C:\temp> $error[5].Exception|select *


Message        : 'Une erreur s'est produite lors de la copie du contenu vers un flux.' Request sent: 'https://www.power
                 shellgallery.com/api/v2/FindPackagesById()?id='Az.Accounts'&$orderby=NormalizedVersion%20desc&$inlinec
                 ount=allpages&$skip=0&$filter=IsPrerelease%20eq%20false%20and%20Id%20eq%20'Az.Accounts'%20and%20Normal
                 izedVersion%20ge%20'2.10.2'' Inner exception: 'Réception d'un EOF inattendu ou de 0 octet du flux de
                 transport.'
Data           : {}
InnerException :
TargetSite     : Void MoveNext()
StackTrace     :    à Microsoft.PowerShell.PSResourceGet.Cmdlets.V2ServerAPICalls.<SendV2RequestAsync>d__33.MoveNext()
                 --- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été
                 levée ---
                    à System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                    à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                    à Microsoft.PowerShell.PSResourceGet.Cmdlets.V2ServerAPICalls.HttpRequestCall(String requestUrlV2,
                 ErrorRecord& errRecord)
HelpLink       :
Source         : Microsoft.PowerShell.PSResourceGet
HResult        : -2146233088

```
```


### Environment data

```powershell
ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Binary     0.5.23     Microsoft.PowerShell.PSResourceGet  {Find-PSResource, Get-InstalledPSResource, Get-PSResourceR...

Key   : PSVersion
Value : 5.1.19041.3031
Name  : PSVersion


Key   : PSEdition
Value : Desktop
Name  : PSEdition


Key   : PSCompatibleVersions
Value : {1.0, 2.0, 3.0, 4.0, 5.0, 5.1.19041.3031}
Name  : PSCompatibleVersions


Key   : BuildVersion
Value : 10.0.19041.3031
Name  : BuildVersion


Key   : CLRVersion
Value : 4.0.30319.42000
Name  : CLRVersion


Key   : WSManStackVersion
Value : 3.0
Name  : WSManStackVersion


Key   : PSRemotingProtocolVersion
Value : 2.3
Name  : PSRemotingProtocolVersion


Key   : SerializationVersion
Value : 1.1.0.1
Name  : SerializationVersion
```

### Visuals

image

First error : 
image

Second Error: 
image

### PR DESCRIPTION
**Pull request by alerickson**
# PR Summary
Bug fix for a somewhat obscure bug installing or saving a module (seen with some of Az's dependency modules) from the PowerShell Gallery.  If installing a module using a version range and prerelease is true, this bug will occur if the lower value in the version range has a 9 in it. 

This is because since the PSGallery views '3.0.0-prerelease' as being a higher version than '3.0.0', when a request goes out to the Gallery, PSResourceGet searches just beyond that version. For example:  if looking for 1.9.0, PSResource get would look for a range of [1.9.0, 1.10.0] to ensure it's catching all the 1.9.0 prereleases.

However, in another Gallery bug, the Gallery views 1.9.0 as being a greater version than 1.10.0, so incorrect results are returned from the server.

This PR is a small fix for a very narrow situation and meant to accommodate for many scenarios (specifically when installing dependencies and especially Az dependencies).

However, the larger issue is that the Gallery always views '9.0' as being greater than '10.0'.  This is out of scope for PSResourceGet, and requires a more thorough investigation with both the PSGallery code base and potentially PSResourceGet if work arounds are required client side.

## PR Context

Resolves #1341 

## PR Checklist

- [x] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [x] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.
- **[Breaking changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)**
    - [x] None
    - **OR**
    - [ ] [Documentation needed]()
        - [ ] Issue filed: 
- **User-facing changes**
    - [x] Not Applicable
    - **OR**
    - [ ] [Documentation needed]()
        - [ ] Issue filed: 
- **Testing - New and feature**
    - [ ] N/A or can only be tested interactively
    - **OR**
    - [x] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
- **Tooling**
    - [x] I have considered the user experience from a tooling perspective and don't believe tooling will be impacted.
    - **OR**
    - [ ] I have considered the user experience from a tooling perspective and enumerated concerns in the summary.

### CODE REVIEW

File: src/code/V2ServerAPICalls.cs [hunk 1]
```diff
@@ -839,10 +839,14 @@ private string FindVersionGlobbing(string packageName, VersionRange versionRange
...
             {
                 string operation = versionRange.IsMaxInclusive ? "le" : "lt";
-                // Adding 1 because we want to retrieve all the prerelease versions for the max version and PSGallery views prerelease as higher than its stable
+                // Adding '9' as a digit to the end of the patch portion of the version
+                // because we want to retrieve all the prerelease versions for the upper end of the range
+                // and PSGallery views prerelease as higher than its stable.
                 // eg 3.0.0-prerelease > 3.0.0
-                string maxString = includePrerelease ? $"{versionRange.MaxVersion.Major}.{versionRange.MaxVersion.Minor + 1}" :
-                                $"{versionRange.MaxVersion.ToNormalizedString()}";
+                // If looking for '[1.9.9,1.9.9]' including prerelease values, this will search for '[1.9.9,1.9.99]'
```
Comment (anamnavi) [inline src/code/V2ServerAPICalls.cs]:
```suggestion
                // If looking for versions within '[1.9.9,1.9.9]' including prerelease values, this will change it to search for '[1.9.9,1.9.99]' 
```

**Review by anamnavi — APPROVED** [review]
LGTM
