### PR TITLE
Check for ModulePrefix parameter presence instead of it being a dynamic parameter

### LINKED ISSUE #1827: Meaningful error handling when repository not registered
### Prerequisites

- [x] Write a descriptive title.
- [x] Make sure you are able to repro it on the [latest released version](https://www.powershellgallery.com/packages/Microsoft.PowerShell.PSResourceGet)
- [x] Search the existing issues.

### Steps to reproduce

```
Publish-PSResource -NupkgPath $path -Repository "111" -ModulePrefix "public/psresource" -debug
Publish-PSResource: A parameter cannot be found that matches parameter name 'ModulePrefix'.
```

### Expected behavior

```console
should print meaningful error such as "repository xxx was not registered" or such
```

### Actual behavior

```console
when using -ModulePrefix with `-NupkgPath` and `-Repository`; if repository was not registered it printed cannot find parameter 'ModulePrefix'
```

### Error details

```console

```

### Environment data

```powershell
Binary     1.1.1                 Microsoft.PowerShell.PSResourceGet
```

### Visuals

_No response_

### PR DESCRIPTION
**Pull request by anamnavi**
For `Publish-PSResource` declare `ModulePrefix` as a regular parameter instead of a dynamic parameter. This allows for better error message writing and error handling with regards to how this parameter works with repositories.

# PR Summary

## PR Context
Resolves #1827 #1806 

## PR Checklist

- [ ] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [ ] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [ ] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [ ] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.
- **[Breaking changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)**
    - [ ] None
    - **OR**
    - [ ] [Documentation needed]()
        - [ ] Issue filed: 
- **User-facing changes**
    - [ ] Not Applicable
    - **OR**
    - [ ] [Documentation needed]()
        - [ ] Issue filed: 
- **Testing - New and feature**
    - [ ] N/A or can only be tested interactively
    - **OR**
    - [ ] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
- **Tooling**
    - [ ] I have considered the user experience from a tooling perspective and don't believe tooling will be impacted.
    - **OR**
    - [ ] I have considered the user experience from a tooling perspective and enumerated concerns in the summary.

### CODE REVIEW

File: src/code/PublishPSResource.cs [hunk 1]
```diff
@@ -151,16 +142,42 @@ protected override void BeginProcessing()
 
             _networkCredential = Credential != null ? new NetworkCredential(Credential.UserName, Credential.Password) : null;
 
+            // Create the repository store file (PSResourceRepository.xml) if it does not already exist
+            // This is to create a better experience for those who have just installed v3 and want to get up and running quickly
+            RepositorySettings.CheckRepositoryStore();
+
+            if (MyInvocation.BoundParameters.ContainsKey(nameof(ModulePrefix)))
+            {
+                if (MyInvocation.BoundParameters.ContainsKey(nameof(Repository))) // can remove if Repository is 'Mandatory' parameter
```
Comment (alerickson) [inline src/code/PublishPSResource.cs]: What does "can remove if Repository is 'Mandatory' parameter" mean?  What's being removed?

**Review by alerickson — APPROVED** [review]

File: src/code/PublishPSResource.cs (hunk 1 above)
Comment (anamnavi) [reply src/code/PublishPSResource.cs]: I just meant if we make the `-Repository` parameter mandatory for `Publish-PSResource` then I'll remove the check for seeing if `Repository` was included in the cmdlet invocation because that condition is guaranteed.

**Review by adityapatwardhan — APPROVED** [review]

**Comment by anamnavi** [comment]
@EmilienCourt please track this in favor of #1865
