### PR TITLE
Bug fix in Publish-PSResource when creating nuspec

### LINKED ISSUE #603: Review ProjectUri/Url  and IconUri/Url in Publish-PSResource
### Summary of the new feature / enhancement

See: https://github.com/PowerShell/PowerShellGet/pull/551#issuecomment-1020034298

Ensure that 'ProjectUri' or 'ProjectUrl' and 'IconUri' and 'IconUrl' are being used in the appropriate spots and are being referenced correctly when reading from module manifests and writing to nuspecs. 

### Proposed technical implementation details (optional)

_No response_

### PR DESCRIPTION
**Pull request by alerickson**
# PR Summary
In module manifests, properties are labeled "LicenseUri", "ProjectUri", and "IconUri", however in a nuspec the same properties are "LicenseUrl", "ProjectUrl", and "IconUrl", respectively.  This PR updates references to "url" and changes them to "uri" where appropriate.   

All of these properties, as well as "ReleaseNotes"  are found under the "PSData" section of a module manifest, so the code is moved under that section to reflect this and so we can properly extract the respective values.

Only those nuspec properties which exist in the module manifest get added to the nuspec.  See below for all properties that are allowed in a nuspec:
https://docs.microsoft.com/en-us/nuget/reference/nuspec

## PR Context

Resolves #603 

## PR Checklist

- [x] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [x] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.
- **[Breaking changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)**
    - [x] None
    - **OR**
    - [ ] [Documentation needed]()
        - [ ] Issue filed: 
- **User-facing changes**
    - [x] Not Applicable
    - **OR**
    - [ ] [Documentation needed]()
        - [ ] Issue filed: 
- **Testing - New and feature**
    - [x] N/A or can only be tested interactively
    - **OR**
    - [ ] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
- **Tooling**
    - [x] I have considered the user experience from a tooling perspective and don't believe tooling will be impacted.
    - **OR**
    - [ ] I have considered the user experience from a tooling perspective and enumerated concerns in the summary.

### CODE REVIEW

**Comment by alerickson** [comment]
This PR is ready to be reviewed.

File: src/code/PublishPSResource.cs [hunk 1]
```diff
@@ -540,10 +540,36 @@ private bool IsValidModuleManifest(string moduleManifestPath)
...
+                        {
+                            metadataElementsDictionary.Add("projectUrl", projectUri.Trim());
+                        }
+
+                        if (psData.ContainsKey("iconuri") && psData["iconuri"] is string iconUri)
+                        {
+                            metadataElementsDictionary.Add("iconUrl", iconUri.Trim());
+                        }
+
+                        if (psData.ContainsKey("releasenotes") && psData["releasenotes"] is string releaseNotes)
```
Comment (PaulHigin) [inline src/code/PublishPSResource.cs]: Can `releaseNotes` ever be anything other than string type?

File: src/code/PublishPSResource.cs [hunk 2]
```diff
@@ -540,10 +540,36 @@ private bool IsValidModuleManifest(string moduleManifestPath)
...
+                        {
+                            metadataElementsDictionary.Add("releaseNotes", releaseNotes.Trim());
+                        }
+
+                        // defaults to false
+                        string requireLicenseAcceptance = psData.ContainsKey("requirelicenseacceptance") ? psData["ReleaseNotes"] as string  : "false";
```
Comment (PaulHigin) [inline src/code/PublishPSResource.cs]:
```suggestion
                        string requireLicenseAcceptance = psData.ContainsKey("requirelicenseacceptance") ? psData["requirelicenseacceptance"] : "false";

```

**Review by PaulHigin — CHANGES_REQUESTED** [review]

File: src/code/PublishPSResource.cs (hunk 1 above)
Comment (alerickson) [reply src/code/PublishPSResource.cs]: That's a good question, I just looked up how `releaseNotes` is referenced in v2 and it can be a string[] as well, so I'll update this to accommodate for that as well

File: src/code/PublishPSResource.cs [hunk 3]
```diff
@@ -540,10 +540,37 @@ private bool IsValidModuleManifest(string moduleManifestPath)
                 {
                     if (privateData["PSData"] is Hashtable psData)
                     {
-                        if (psData.ContainsKey("Prerelease") && psData["Prerelease"] is string preReleaseVersion)
+                        if (psData.ContainsKey("prerelease") && psData["prerelease"] is string preReleaseVersion)
                         {
                             version = string.Format(@"{0}-{1}", version, preReleaseVersion);
                         }
+
+                        if (psData.ContainsKey("licenseUri") && psData["licenseuri"] is string licenseUri)
```
Comment (anamnavi) [inline src/code/PublishPSResource.cs]: typo in key name check
```suggestion
                        if (psData.ContainsKey("licenseuri") && psData["licenseuri"] is string licenseUri)

```

File: src/code/PublishPSResource.cs [hunk 4]
```diff
@@ -540,10 +540,37 @@ private bool IsValidModuleManifest(string moduleManifestPath)
...
                     {
-                        if (psData.ContainsKey("Prerelease") && psData["Prerelease"] is string preReleaseVersion)
+                        if (psData.ContainsKey("prerelease") && psData["prerelease"] is string preReleaseVersion)
                         {
                             version = string.Format(@"{0}-{1}", version, preReleaseVersion);
                         }
+
+                        if (psData.ContainsKey("licenseUri") && psData["licenseuri"] is string licenseUri)
+                        {
+                            metadataElementsDictionary.Add("license", licenseUri.Trim());
```
Comment (anamnavi) [inline src/code/PublishPSResource.cs:551]: I'm a little confused, why do we add license as `license` but project as `projectUrl` and icon as `iconUrl`? Do the 3 of them follow different naming guidelines for the nuspec now?

File: src/code/PublishPSResource.cs [hunk 5]
```diff
@@ -628,7 +631,7 @@ private bool IsValidModuleManifest(string moduleManifestPath)
                 <owners>Microsoft,PowerShell</owners>
                 <requireLicenseAcceptance>false</requireLicenseAcceptance>
                 <license type="expression">MIT</license>
-                <licenseUrl>https://licenses.nuget.org/MIT</licenseUrl>
+                <license>https://licenses.nuget.org/MIT</license>
                 <icon>Powershell_black_64.png</icon>
                 <projectUrl>https://github.com/PowerShell/PowerShell</projectUrl>
```
Comment (anamnavi) [inline src/code/PublishPSResource.cs:644]: Per the comment about naming guideline for the 3 (license, icon, project) would `projectUrl` change to the below? Or would icon be `iconUrl` and only license is named `license`?
```suggestion
                <project>https://github.com/PowerShell/PowerShell</project>

```

**Review by anamnavi — COMMENTED** [review]
Have some questions about whether license, icon and project are named consistently in the nuspec or license will follow different naming (without "Url" appended at end) and why?

File: src/code/PublishPSResource.cs (hunk 4 above)
Comment (alerickson) [reply src/code/PublishPSResource.cs:551]: The nuspec schema is specified here, so this is what I used to validate correct property names: https://docs.microsoft.com/en-us/nuget/reference/nuspec

`license` used to be `licenseUrl` but the latter is deprecated now: https://docs.microsoft.com/en-us/nuget/reference/nuspec#licenseurl

Similar situation with `icon` and `iconUrl`: https://docs.microsoft.com/en-us/nuget/reference/nuspec#iconurl

File: src/code/PublishPSResource.cs (hunk 5 above)
Comment (alerickson) [reply src/code/PublishPSResource.cs:644]: Nope, `projectUrl` would not change to `project`, see: https://docs.microsoft.com/en-us/nuget/reference/nuspec#projecturl

**Review by PaulHigin — APPROVED** [review]
LGTM
