### PR TITLE
Bug fix for searching through local repositories with -Type parameter

### LINKED ISSUE #1219: Find-PSResource doesn't filter by type on local repository
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://www.powershellgallery.com/packages/PSResourceGet)
- [X] Search the existing issues.

### Steps to reproduce

```powershell
Register-PSResourceRepository -Name LocalRepo -Uri c:\path

Find-PSResource -Type Script -Repository LocalRepo
Find-PSResource -Type Module -Repository LocalRepo
Find-PSResource -Type None -Repository LocalRepo
```

### Expected behavior

```console
resources filtered by type (no resources, when Type is None)
```

### Actual behavior

```console
all resources are returned
```

### Error details

```console
no error occurs
```

### Environment data

```powershell
ModuleType Version    PreRelease Name
---------- -------    ---------- ----
Binary     0.5.22     beta22     Microsoft.PowerShell.PSResourceGet


Name                           Value
----                           -----
PSVersion                      7.3.5
PSEdition                      Core
GitCommitId                    7.3.5
OS                             Microsoft Windows 10.0.19045
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Visuals

_No response_

### PR DESCRIPTION
**Pull request by alerickson**
# PR Summary
Bug fix for searching through local repositories with -Type parameter.  This PR allows for filtering on type.

## PR Context
Resolves #1219 

## PR Checklist

- [x] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [x] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.
- **[Breaking changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)**
    - [x] None
    - **OR**
    - [ ] [Documentation needed]()
        - [ ] Issue filed: 
- **User-facing changes**
    - [x] Not Applicable
    - **OR**
    - [ ] [Documentation needed]()
        - [ ] Issue filed: 
- **Testing - New and feature**
    - [ ] N/A or can only be tested interactively
    - **OR**
    - [x] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
- **Tooling**
    - [x] I have considered the user experience from a tooling perspective and don't believe tooling will be impacted.
    - **OR**
    - [ ] I have considered the user experience from a tooling perspective and enumerated concerns in the summary.

### CODE REVIEW

File: src/code/PSResourceInfo.cs [hunk 1]
```diff
@@ -1437,6 +1437,11 @@ private PSObject ConvertToCustomObject()
         private static Dependency[] GetDependenciesForPs1(ModuleSpecification[] requiredModules)
         {
             List<Dependency> deps = new List<Dependency>();
+            if (requiredModules == null)
+            {
+                return deps.ToArray();
+            }
+
```
Comment (adityapatwardhan) [inline src/code/PSResourceInfo.cs:1444]: Is this related to the PR? seems like a fix for a different issue

**Review by adityapatwardhan — CHANGES_REQUESTED** [review]

File: src/code/PSResourceInfo.cs (hunk 1 above)
Comment (alerickson) [reply src/code/PSResourceInfo.cs:1444]: Yup, I can add this is a different PR to it separate.

Comment (alerickson) [reply src/code/PSResourceInfo.cs:1444]: Oh actually it is needed for the -Type issue, I tried removing it and it does impact -Type functionality.

**Review by adityapatwardhan — APPROVED** [review]
