### PR TITLE
Bug fix for deduping dependencies in Find-PSResource

### LINKED ISSUE #1372: [Question] About the result of Find-PSResource -IncludeDependencies
### Summary of the new feature / enhancement

With _Microsoft.PowerShell.PSResourceGet_ v0.5.24     

For the following command we see that we have many versions of 'Az.Accounts' as dependencies  : 
```Powershell
$m=Find-psresource -Name "AZ" -IncludeDependencies -verbose -Repository PSGallery
$m.count
#162

$m[0]
$m[0].Dependencies.count
#81

$g=$m|group-object 'Name' -AsHashTable
$g.'Az.Accounts'.count
#81
$g.'Az.Accounts'|sort version -Descending

Count Name                      Group
----- ----                      -----
   20 2.12.5                    {Microsoft.PowerShell.PSResourceGet.UtilClasses.PSResourceInfo, Microsoft.PowerShell...
    3 2.10.2                    {Microsoft.PowerShell.PSResourceGet.UtilClasses.PSResourceInfo, Microsoft.PowerShell...
    9 2.12.4                    {Microsoft.PowerShell.PSResourceGet.UtilClasses.PSResourceInfo, Microsoft.PowerShell...
    1 1.9.1                     {Microsoft.PowerShell.PSResourceGet.UtilClasses.PSResourceInfo}
    2 2.11.0                    {Microsoft.PowerShell.PSResourceGet.UtilClasses.PSResourceInfo, Microsoft.PowerShell...
    2 2.11.2                    {Microsoft.PowerShell.PSResourceGet.UtilClasses.PSResourceInfo, Microsoft.PowerShell...
    7 2.12.0                    {Microsoft.PowerShell.PSResourceGet.UtilClasses.PSResourceInfo, Microsoft.PowerShell...
   14 2.12.3                    {Microsoft.PowerShell.PSResourceGet.UtilClasses.PSResourceInfo, Microsoft.PowerShell...
    1 2.9.1                     {Microsoft.PowerShell.PSResourceGet.UtilClasses.PSResourceInfo}
    1 1.6.1                     {Microsoft.PowerShell.PSResourceGet.UtilClasses.PSResourceInfo}
    3 1.6.5                     {Microsoft.PowerShell.PSResourceGet.UtilClasses.PSResourceInfo, Microsoft.PowerShell...
    1 2.2.0                     {Microsoft.PowerShell.PSResourceGet.UtilClasses.PSResourceInfo}
    1 2.7.2                     {Microsoft.PowerShell.PSResourceGet.UtilClasses.PSResourceInfo}
    1 1.7.1                     {Microsoft.PowerShell.PSResourceGet.UtilClasses.PSResourceInfo}
    2 1.6.7                     {Microsoft.PowerShell.PSResourceGet.UtilClasses.PSResourceInfo, Microsoft.PowerShell...
    2 2.12.1                    {Microsoft.PowerShell.PSResourceGet.UtilClasses.PSResourceInfo, Microsoft.PowerShell...
    1 2.10.3                    {Microsoft.PowerShell.PSResourceGet.UtilClasses.PSResourceInfo}
    1 2.8.0                     {Microsoft.PowerShell.PSResourceGet.UtilClasses.PSResourceInfo}
    2 2.12.2                    {Microsoft.PowerShell.PSResourceGet.UtilClasses.PSResourceInfo, Microsoft.PowerShell...
    1 2.2.4                     {Microsoft.PowerShell.PSResourceGet.UtilClasses.PSResourceInfo}
    1 2.7.0                     {Microsoft.PowerShell.PSResourceGet.UtilClasses.PSResourceInfo}
    1 2.10.0                    {Microsoft.PowerShell.PSResourceGet.UtilClasses.PSResourceInfo}
    1 2.7.5                     {Microsoft.PowerShell.PSResourceGet.UtilClasses.PSResourceInfo}
    1 2.7.1                     {Microsoft.PowerShell.PSResourceGet.UtilClasses.PSResourceInfo}
    1 2.2.8                     {Microsoft.PowerShell.PSResourceGet.UtilClasses.PSResourceInfo}
    1 1.7.4                     {Microsoft.PowerShell.PSResourceGet.UtilClasses.PSResourceInfo}
```

But if we use _Save-PsResource_ we only find in the backup directory the latest version '2.12.5' of the _'Az.Accounts_' module.

This result suggests (finally for me) that the 'Az' module needs all these versions, whereas the behavior of a call to Import-Module without specifying a version loads the last version registered whether it is stable or not.

In the [doc](https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.psresourceget/find-psresource?view=powershellget-3.x#-includedependencies) of the -IncludeDependency parameter it says:
```
When specified, search returns all matching resources their dependencies. Dependencies are deduplicated.
```

For _'Dependencies are deduplicated._' does this only apply to dependencies with the same name and version?

For 'When specified, search returns all matching resources their dependencies.' the result contains all the minimum versions referenced in the dependent modules' manifests:
```
$g.'Az.Advisor'.dependencies

Name        VersionRange
----        ------------
Az.Accounts [2.10.2, )


$g.'Az.MySql'.dependencies

Name        VersionRange
----        ------------
Az.Accounts [2.12.4, )

...
```

Shouldn't the result of _Find-PSResource -IncludeDependencies_ only list the latest version (2.12.5) of the 'Az.Accounts' module (i.e. the one specified in the manifest of the requested module ('Az'))?

### Proposed technical implementation details (optional)

_No response_

### PR DESCRIPTION
**Pull request by alerickson**
# PR Summary
Find-PSResource should not display duplicate package dependencies when returning packages found.

## PR Context
Resolves #1372 

## PR Checklist

- [x] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [x] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.
- **[Breaking changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)**
    - [x] None
    - **OR**
    - [ ] [Documentation needed]()
        - [ ] Issue filed: 
- **User-facing changes**
    - [x] Not Applicable
    - **OR**
    - [ ] [Documentation needed]()
        - [ ] Issue filed: 
- **Testing - New and feature**
    - [ ] N/A or can only be tested interactively
    - **OR**
    - [x] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
- **Tooling**
    - [x] I have considered the user experience from a tooling perspective and don't believe tooling will be impacted.
    - **OR**
    - [ ] I have considered the user experience from a tooling perspective and enumerated concerns in the summary.

### CODE REVIEW

File: src/code/FindHelper.cs [hunk 1]
```diff
@@ -962,6 +967,34 @@ private HashSet<string> GetPackageNamesPopulated(string[] pkgNames)
             return pkgsToDiscover;
         }
 
+
+        private bool TryAddToPackagesFoundHash(PSResourceInfo foundPkg)
+        {
+            bool addedToHash = false;
+            string foundPkgName = foundPkg.Name;
+            string foundPkgVersion = foundPkg.Version.ToString();
```
Comment (anamnavi) [inline src/code/FindHelper.cs]: `foundPkg.Version` is of type System.Version....so this will not factor in prerelease versions correctly. If you have a package with `3.0.0-beta1` and `3.0.0-beta2` and both are dependencies it'll see that the `3.0.0` is already stored in the list value.

Perhaps we should create a string with the version and prerelease and use that for `foundPkgVersion`? You can call Utils.GetNormalizedVersionString(string versionString, string prerelease) to get this string.

File: src/code/FindHelper.cs [hunk 2]
```diff
@@ -962,6 +967,34 @@ private HashSet<string> GetPackageNamesPopulated(string[] pkgNames)
             return pkgsToDiscover;
         }
 
+
+        private bool TryAddToPackagesFoundHash(PSResourceInfo foundPkg)
```
Comment (anamnavi) [inline src/code/FindHelper.cs]: nitpick but this is a dictionary we're adding to right, not hash so maybe we can change the name. not blocking.

File: src/code/FindHelper.cs [hunk 3]
```diff
@@ -1009,15 +1041,26 @@ private HashSet<string> GetPackageNamesPopulated(string[] pkgNames)
                         }
 
                         depPkg = currentResult.returnedObject;
-                        string pkgHashKey = String.Format("{0}{1}", depPkg.Name, depPkg.Version.ToString());
 
-                        if (!foundPkgs.Contains(pkgHashKey))
+                        if (!_packagesFound.ContainsKey(depPkg.Name)) // todo version should be full version
```
Comment (anamnavi) [inline src/code/FindHelper.cs]: what does this todo mean?

**Review by anamnavi — CHANGES_REQUESTED** [review]
I think we should use the normalized version string which takes prerelease into account instead of the System.Version version..

File: src/code/FindHelper.cs (hunk 1 above)
Comment (anamnavi) [inline src/code/FindHelper.cs]:
```suggestion
            string foundPkgVersion = Utils.GetNormalizedVersionString(foundPkg.Version.ToString(), foundPkg.Prerelease);
```

File: src/code/FindHelper.cs [hunk 4]
```diff
@@ -962,6 +967,34 @@ private HashSet<string> GetPackageNamesPopulated(string[] pkgNames)
...
+                    pkgVersions.Add(foundPkgVersion);
+                    _packagesFound[foundPkgName] = pkgVersions;
+                    addedToHash = true;
+                }
+            }
+            else
+            {
+                _packagesFound.Add(foundPkg.Name, new List<string> { foundPkgVersion });
+                addedToHash = true;
+            }
```
Comment (anamnavi) [inline src/code/FindHelper.cs:992]:
```suggestion
            }
   
```

**Review by anamnavi — CHANGES_REQUESTED** [review]

File: src/code/FindHelper.cs [hunk 5]
```diff
@@ -1078,26 +1122,47 @@ private HashSet<string> GetPackageNamesPopulated(string[] pkgNames)
                         {
                             continue;
                         }
-                        
-                        string pkgHashKey = String.Format("{0}{1}", depPkg.Name, depPkg.Version.ToString());
 
-                        if (!foundPkgs.Contains(pkgHashKey))
+                        if (!_packagesFound.ContainsKey(depPkg.Name)) // todo version should be full version
```
Comment (anamnavi) [inline src/code/FindHelper.cs]:
```suggestion
                        if (!_packagesFound.ContainsKey(depPkg.Name))
```

File: src/code/FindHelper.cs [hunk 6]
```diff
@@ -1078,26 +1122,47 @@ private HashSet<string> GetPackageNamesPopulated(string[] pkgNames)
...
+                            }
+                        }
                     }
                 }
             }
 
-            string currentPkgHashKey = String.Format("{0}{1}", currentPkg.Name, currentPkg.Version.ToString());
-
-            if (!foundPkgs.Contains(currentPkgHashKey))
+            if (!_packagesFound.ContainsKey(currentPkg.Name))  // todo version should be full version
```
Comment (anamnavi) [inline src/code/FindHelper.cs]:
```suggestion
            if (!_packagesFound.ContainsKey(currentPkg.Name))
```

**Review by anamnavi — APPROVED** [review]
