### PR TITLE
Fix error message for DSCResource not found

### LINKED ISSUE #1298: Error message is not correct for unknown DSCResource in Find-PSResource
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://www.powershellgallery.com/packages/PSResourceGet)
- [X] Search the existing issues.

### Steps to reproduce

When trying to search against gallery and provide a non-existent resource name, the error message has "System.String[]" in the message. It should be the name of the resource provided for searching. This might be happening for other error message too.

### Expected behavior

```console
The resource name is in the error message
```

### Actual behavior

```console
PS> Find-PSResource -DscResourceName xWindowsUpdate
Find-PSResource: 'System.String[]' could not be found
```

### Error details

```console
Exception             :
    Type           : Microsoft.PowerShell.PSResourceGet.UtilClasses.PackageNotFoundException
    Message        : 'System.String[]' could not be found
    InnerException :
        Type    : Microsoft.PowerShell.PSResourceGet.UtilClasses.V2ResourceNotFoundException
        Message : Package does not exist on the server
        HResult : -2146233088
    HResult        : -2146233088
TargetObject          : Microsoft.PowerShell.PSResourceGet.Cmdlets.FindHelper
CategoryInfo          : NotSpecified: (Microsoft.PowerShel….Cmdlets.FindHelper:FindHelper) [Find-PSResource], PackageNotFoundException
FullyQualifiedErrorId : FindCmdOrDscToPSResourceObjFailure,Microsoft.PowerShell.PSResourceGet.Cmdlets.FindPSResource
InvocationInfo        :
    MyCommand        : Find-PSResource
    ScriptLineNumber : 1
    OffsetInLine     : 1
    HistoryId        : 20
    Line             : Find-PSResource -DscResourceName xWindowsUpdate
    PositionMessage  : At line:1 char:1
                       + Find-PSResource -DscResourceName xWindowsUpdate
                       + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    InvocationName   : Find-PSResource
    CommandOrigin    : Internal
ScriptStackTrace      : at <ScriptBlock>, <No file>: line 1
PipelineIterationInfo :
```

### Environment data

```powershell
ModuleType Version    PreRelease Name                                ExportedCommands
---------- -------    ---------- ----                                ----------------
Binary     0.5.23     beta23     Microsoft.PowerShell.PSResourceGet  {Find-PSResource, Get-InstalledPSResource, Get-PSResourceRepository, Get-PSScriptFileInfo…}

Name                           Value
----                           -----
PSVersion                      7.3.4
PSEdition                      Core
GitCommitId                    7.3.4
OS                             Linux 5.10.102.1-microsoft-standard-WSL2 #1 SMP Wed Mar 2 00:30:59 UTC 2022
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Visuals

_No response_

### PR DESCRIPTION
**Pull request by anamnavi**
When DSCResource or CommandName is not found the error message says, "'System.String[]' could not be found" instead of showing the actual value of those tags.

# PR Summary

## PR Context
Resolves #1298 

## PR Checklist

- [x] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [x] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.
- **[Breaking changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)**
    - [ ] None
    - **OR**
    - [ ] [Documentation needed]()
        - [ ] Issue filed: 
- **User-facing changes**
    - [ ] Not Applicable
    - **OR**
    - [ ] [Documentation needed]()
        - [ ] Issue filed: 
- **Testing - New and feature**
    - [ ] N/A or can only be tested interactively
    - **OR**
    - [ ] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
- **Tooling**
    - [ ] I have considered the user experience from a tooling perspective and don't believe tooling will be impacted.
    - **OR**
    - [ ] I have considered the user experience from a tooling perspective and enumerated concerns in the summary.

### CODE REVIEW

File: src/code/FindHelper.cs [hunk 1]
```diff
@@ -433,7 +435,7 @@ private IEnumerable<PSResourceInfo> SearchByNames(ServerApiCall currentServer, R
                             if (currentResult.exception != null && !currentResult.exception.Message.Equals(string.Empty))
                             {
                                 _cmdletPassedIn.WriteError(new ErrorRecord(
-                                            new PackageNotFoundException($"Package '{pkgName}' could not be found", currentResult.exception), 
+                                            new PackageNotFoundException($"Package with name '{pkgName}' could not be found in repository '{repository.Name}'", currentResult.exception),
```
Comment (alerickson) [inline src/code/FindHelper.cs:438]: I don't know if we need to add 'with name' here.  To me "Package with name 'Az' could not be found in repository 'PSGallery'" for example reads a little strange.  
I think something like "'Az' package could not be found in repository 'PSGallery'" sounds a little more natural.  Also wondering if we should change the word "package" to "PSResource".

File: src/code/FindHelper.cs [hunk 2]
```diff
@@ -479,8 +478,7 @@ private IEnumerable<PSResourceInfo> SearchByNames(ServerApiCall currentServer, R
                         {
                             if (currentResult.exception != null && !currentResult.exception.Message.Equals(string.Empty))
                             {
-                                // write warning?
-                                string message = _tag.Length == 0 ? $"Package '{pkgName}' could not be found." : $"Package '{pkgName}' with tags '{tagsAsString}' could not be found.";
+                                string message = _tag.Length == 0 ? $"Package with name '{pkgName}' could not be found in repository '{repository.Name}'." : $"Package with name '{pkgName}' and tags '{tagsAsString}' could not be found in repository '{repository.Name}'.";
```
Comment (alerickson) [inline src/code/FindHelper.cs:481]: Same thoughts as above for this message and the messages below.

**Review by alerickson — APPROVED** [review]
Just some comments on the error messages themselves.
