### PR TITLE
Integrate AzArtifacts Credential Provider

### LINKED ISSUE #1511: Modern authentication with NuGet feeds
### Summary of the new feature / enhancement

Currently, retrieving modules from a private NuGet feed is only possible with a username/password or a PAT.

We would like to perform authentication with an identity provider and OAuth.

As an example with an Azure Artifact feed: Register the feed -> Login with OAuth Device Code Flow.

### Proposed technical implementation details (optional)

_No response_

### LINKED ISSUE #1601: Using the Azure Artifacts Credential Provider with Azure Artifacts feed results in 401 (Not Authorized) error
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://www.powershellgallery.com/packages/Microsoft.PowerShell.PSResourceGet)
- [X] Search the existing issues.

### Steps to reproduce

1. Install the Azure Artifacts Credential Provider.
2. Setup the `VSS_NUGET_EXTERNAL_FEED_ENDPOINTS` environment variable using a valid Azure DevOps PAT.
3. Register the private Azure DevOps feed using `Register-PSResourceRepository -Name <RepoName> -Uri <FeedUrl> -Trusted`
4. Use `Install-PSResource` or `Find-PSResource` to find a module in the private feed. It returns back a `401 (Not Authorized)` error.

#### Details

It seems that `Install-PSResource` and `Find-PSResource` still do not work properly with Azure Artifacts and the [Azure Artifacts Credential Provider](https://github.com/microsoft/artifacts-credprovider) in [Microsoft.PowerShell.PSResourceGet](https://www.powershellgallery.com/packages/Microsoft.PowerShell.PSResourceGet) v1.0.3; they result in a `401 (Not Authorized)` error.

The `Install-Module` and `Find-Module` commands work properly though when registered with the same repository URI, so I know that the Azure Artifacts Credential Provider is setup properly.

The Azure Artifacts Credential Provider has been installed with the following command [as per the docs](https://github.com/microsoft/artifacts-credprovider?tab=readme-ov-file#automatic-powershell-script):

```
iex "& { $(irm https://aka.ms/install-artifacts-credprovider.ps1) } -AddNetfx
```

And a `VSS_NUGET_EXTERNAL_FEED_ENDPOINTS` system environment variable added using a valid Azure DevOps Personal Access Token, [as per the docs](https://github.com/microsoft/artifacts-credprovider?tab=readme-ov-file#azure-devops-server).

#### Tangentially related

What's worse is it seems that the latest prerelease version 3.0.23 of [PowerShellGet](https://www.powershellgallery.com/packages/PowerShellGet) has broken the `Install-Module` and `Find-Module` commands completely, and previous prerelease versions have been delisted; see https://github.com/PowerShell/PowerShellGet/issues/58. Luckily I still have PowerShellGet v3.0.12 installed so the commands still work on my local machine, but new servers that I'm setting up are not able to connect to our Azure Artifacts feed without the `-Credential` parameter.

I created the [AzureArtifactsPowerShellModuleHelper](https://github.com/deadlydog/AzureArtifactsPowerShellModuleHelper) module a while back to help solve this issue, but found that sometimes even with that module PowerShellGet 2.2.5 still couldn't access the feed and we'd need to use the prerelease v3 version. With v3.0.23 broken though, and older v3 versions delisted and thus can't be installed, there's not much we can do when v2.2.5 has issues. I was hoping that PSResourceGet would eliminate the need for using the AzureArtifactsPowerShellModuleHelper module and PowerShellGet.

### Expected behavior

The `Install-PSResource` and `Find-PSResource` cmdlets should automatically use the Azure Artifacts Credential Provider to provide credentials to connect to the private Azure DevOps Artifacts feed.

```console
Find-PSResource $MyPrivateModule -Repository $MyPrivateAzureArtifactsFeed
```

Should be able to find the module.

### Actual behavior

```console
Find-PSResource $MyPrivateModule -Repository $MyPrivateAzureArtifactsFeed

Find-PSResource: 'Response status code does not indicate success: 401 (Unauthorized).' Re-run the command with -Credential.
```

### Error details

```console
PS> Get-Error

Exception             :
    Type       : Microsoft.PowerShell.PSResourceGet.UtilClasses.UnauthorizedException
    TargetSite :
        Name          : MoveNext
        DeclaringType : Microsoft.PowerShell.PSResourceGet.Cmdlets.V2ServerAPICalls+<SendV2RequestAsync>d__38, Microsoft.PowerShell.PSResourceGet, Version=1.0.3.0, Culture=neutral, PublicKeyToken=null
        MemberType    : Method
        Module        : Microsoft.PowerShell.PSResourceGet.dll
    Message    : 'Response status code does not indicate success: 401 (Unauthorized).' Re-run the command with -Credential.
    Source     : Microsoft.PowerShell.PSResourceGet
    HResult    : -2146233088
    StackTrace :
   at Microsoft.PowerShell.PSResourceGet.Cmdlets.V2ServerAPICalls.SendV2RequestAsync(HttpRequestMessage message, HttpClient s_client)
   at Microsoft.PowerShell.PSResourceGet.Cmdlets.V2ServerAPICalls.HttpRequestCall(String requestUrlV2, ErrorRecord& errRecord)
TargetObject          : Microsoft.PowerShell.PSResourceGet.Cmdlets.V2ServerAPICalls
CategoryInfo          : InvalidResult: (Microsoft.PowerShel…ts.V2ServerAPICalls:V2ServerAPICalls) [Find-PSResource], UnauthorizedException
FullyQualifiedErrorId : UnauthorizedRequest,Microsoft.PowerShell.PSResourceGet.Cmdlets.FindPSResource
InvocationInfo        :
    MyCommand        : Find-PSResource
    ScriptLineNumber : 1
    OffsetInLine     : 1
    HistoryId        : 7
    Line             : Find-PSResource <REDACTED>.ServerConfiguration -Repository AzureArtifacts-<REDACTED>
    Statement        : Find-PSResource <REDACTED>.ServerConfiguration -Repository AzureArtifacts-<REDACTED>
    PositionMessage  : At line:1 char:1
                       + Find-PSResource <REDACTED>.ServerConfiguration -Repository AzureAr …
                       + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    InvocationName   : Find-PSResource
    CommandOrigin    : Internal
ScriptStackTrace      : at <ScriptBlock>, <No file>: line 1
PipelineIterationInfo :
```

### Environment data

```powershell
PS> Get-Module Microsoft.PowerShell.PSResourceGet; $PSVersionTable

ModuleType Version    PreRelease Name                                ExportedCommands
---------- -------    ---------- ----                                ----------------
Binary     1.0.3                 Microsoft.PowerShell.PSResourceGet  {Find-PSResource, Get-InstalledPSResource, Get-PSResourceRepository, Get-PSScriptFileInfo…}

Key   : PSVersion
Value : 7.4.1
Name  : PSVersion


Key   : PSEdition
Value : Core
Name  : PSEdition


Key   : GitCommitId
Value : 7.4.1
Name  : GitCommitId


Key   : OS
Value : Microsoft Windows 10.0.19045
Name  : OS


Key   : Platform
Value : Win32NT
Name  : Platform


Key   : PSCompatibleVersions
Value : {1.0, 2.0, 3.0, 4.0…}
Name  : PSCompatibleVersions


Key   : PSRemotingProtocolVersion
Value : 2.3
Name  : PSRemotingProtocolVersion


Key   : SerializationVersion
Value : 1.1.0.1
Name  : SerializationVersion


Key   : WSManStackVersion
Value : 3.0
Name  : WSManStackVersion
```

### Visuals

Here's a screenshot showing the issue, and that it works properly with PowerShellGet, but not PSResourceGet. If you need any other information for troubleshooting let me know; I'm happy to provide anything that can help get this issue resolved.

image

### LINKED ISSUE #1658: Add support for the ADO credential provider
### Summary of the new feature / enhancement

Using PATs is not difficult, requires rotation and is not desired in many situations. PSResourceGet should support the ADO cred provider in order to support Azure Identity for ADO. 

Related issues #1601 #1511 

### Proposed technical implementation details (optional)

_No response_

### PR DESCRIPTION
**Pull request by alerickson**
# PR Summary
This PR integrates the Azure Artifacts Credential Provider into PSResourceGet. 
**Information on the cred provider and how to install, discover, and use the cred provider is located here:** https://github.com/NuGet/Home/wiki/NuGet-cross-plat-authentication-plugin#plugin-installation-and-discovery.
Please use this link for setting up and configuring the cred provider for PSResourceGet as well.   Also see: https://github.com/microsoft/artifacts-credprovider for using environment variables with the Credential Provider.

This PR adds a new dynamic parameter to `Register-PSResourceRepository` and `Set-PSResourceRepository` called `-CredentialProvider`, which is an enum with values `None` and `AzArtifacts`.  The parameter only works with repositories that are _not_ `ContainerRegistry` repositories.  This is because the credential provider only works with Azure Artifact feeds, however Azure Artifact feeds can have any uri.  Instead of only allowing the parameter to be used with Azure Artifact feeds, we are not allowing use for feeds in which we _know_ we cannot use the credential provider for. 

PSResourceGet will automatically set the value `CredentialProvider` to `AzArtifacts` if it recognizes that the repository is definitely an Azure Artifacts feed.  This is done by checking to see if the uri contains `pkgs.dev.azure.com` or `pkgs.visualstudio.com`.  This check is done when registering a new repository or when PSResourceGet reads repositories from the `PSResourceRepository.xml` file. 

PSResourceGet looks for the credential provider any time network credentials are set.  The new priority ordering for credentials is:
&nbsp;&nbsp;&nbsp;&nbsp; 1. Credentials passed in via parameter `-Credential`.
&nbsp;&nbsp;&nbsp;&nbsp; 2. Credentials retrieved via the AzArtifacts Credential Provider.
&nbsp;&nbsp;&nbsp;&nbsp; 3. Credentials retrieved from SecretManagement.

The Credential Provider can be bypassed by setting the `-CredentialProvider` parameter to `None`.

If the `CredentialProvider` property is set to `AzArtifacts` for a repository, PSResourceGet will attempt to find the Credential Provider file on the machine in the following order:
&nbsp;&nbsp;&nbsp;&nbsp; 1. Checking the environment variable `NUGET_PLUGIN_PATHS`
&nbsp;&nbsp;&nbsp;&nbsp; 2. Checking the default locations: `$env:UserProfile\.nuget\plugins`
&nbsp;&nbsp;&nbsp;&nbsp; 3. Checking the fixed location where Visual Studio is installed:  `common7\IDE\CommonExtensions\Microsoft\NuGet`
More information on this discovery process can be found in the link above.

Once the Credential Provider is found, PSResourceGet calls the provider with the following arguments:
`CredentialProvider.Microsoft.exe -Uri <uri> -NonInteractive -IsRetry -F Json`
Or
`dotnet CredentialProvider.Microsoft.dll -Uri <uri> -NonInteractive -IsRetry -F Json`

Right now, this means that for Unix machines, there is a dependency on the dotnet cli to call the Credential Provider.

Once credentials are retrieved, they are used to make the network call, as is done when using the `-Credential` parameter or SecretManagement.

## PR Context
Resolves #1658
Resolves #1601 
Resolves #1511

## PR Checklist

- [x] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [x] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [ ] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.
- **[Breaking changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)**
    - [x] None
    - **OR**
    - [x] [Documentation needed]()
        - [ ] Issue filed: 
- **User-facing changes**
    - [ ] Not Applicable
    - **OR**
    - [x] [Documentation needed]()
        - [ ] Issue filed: 
- **Testing - New and feature**
    - [ ] N/A or can only be tested interactively
    - **OR**
    - [x] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
- **Tooling**
    - [x] I have considered the user experience from a tooling perspective and don't believe tooling will be impacted.
    - **OR**
    - [ ] I have considered the user experience from a tooling perspective and enumerated concerns in the summary.

### CODE REVIEW

**Comment by MatejKafka-MSFT** [comment]
Just wondering, what is the state of this PR? Is it abandoned, or can I expect PSResourceGet to get support for AzDO auth in the near future? :)

File: src/code/FindHelper.cs [hunk 1]
```diff
@@ -202,7 +202,16 @@ public IEnumerable<PSResourceInfo> FindByResourceName(
...
-                _networkCredential = Utils.SetNetworkCredential(currentRepository, _networkCredential, _cmdletPassedIn);
+
+                // Set network credentials via passed in credentials, AzArtifacts CredentialProvider, or SecretManagement.
+                if (currentRepository.CredentialProvider.Equals(PSRepositoryInfo.CredentialProviderType.AzArtifacts))
+                { 
+                    _networkCredential = Utils.SetCredentialProviderNetworkCredential(currentRepository, _networkCredential, _cmdletPassedIn);
+                }
+                else {
+                    _networkCredential = Utils.SetSecretManagementNetworkCredential(currentRepository, _networkCredential, _cmdletPassedIn);
+                }
```
Comment (adityapatwardhan) [inline src/code/FindHelper.cs]: Can this be put in a utility method, seems to be repeated.

File: src/code/RegisterPSResourceRepository.cs [hunk 2]
```diff
@@ -111,6 +113,25 @@ class RegisterPSResourceRepository : PSCmdlet
...
 
+        #region DynamicParameters
+
+        public object GetDynamicParameters()
+        {
+            // Dynamic parameter '-CredentialProvider' should not appear for PSGallery, or any container registry repository.
+            // It should also not appear when using the 'Repositories' parameter set.
+            if (ParameterSetName.Equals(PSGalleryParameterSet) || 
+                ParameterSetName.Equals(RepositoriesParameterSet) ||
+                Uri.EndsWith(".azurecr.io") || Uri.EndsWith(".azurecr.io/") || Uri.Contains("mcr.microsoft.com"))
```
Comment (adityapatwardhan) [inline src/code/RegisterPSResourceRepository.cs]: need to for GovCloudMCR as well?

File: src/code/SetPSResourceRepository.cs [hunk 3]
```diff
@@ -102,6 +104,27 @@ public SwitchParameter Trusted
...
+
+        public object GetDynamicParameters()
+        {
+            PSRepositoryInfo repository = RepositorySettings.Read(new[] { Name }, out string[] _).FirstOrDefault();
+            // Dynamic parameter '-CredentialProvider' should not appear for PSGallery, or any container registry repository.
+            // It should also not appear when using the 'Repositories' parameter set.
+            if (repository is not null && 
+                (repository.Name.Equals("PSGallery", StringComparison.OrdinalIgnoreCase) ||
+                ParameterSetName.Equals(RepositoriesParameterSet) ||
+                repository.Uri.AbsoluteUri.EndsWith(".azurecr.io") || repository.Uri.AbsoluteUri.EndsWith(".azurecr.io/") || repository.Uri.AbsoluteUri.Contains("mcr.microsoft.com")))
```
Comment (adityapatwardhan) [inline src/code/SetPSResourceRepository.cs]: same as above

File: src/code/Utils.cs [hunk 4]
```diff
@@ -1234,6 +1258,22 @@ internal static void GetMetadataFilesFromPath(string dirPath, string packageName
                 }
             }
         }
+
+        internal static string GetCaseInsensitiveFilePath(string directory, string fileName)
```
Comment (adityapatwardhan) [inline src/code/Utils.cs]: I prefer either throwing expectation, having a TryGetCaseInsensitiveFilePath which returns a null, rather than returning null. If you want to return null, then make the return type `string?` so it is explicit to the caller.

File: test/CredentialProvider.Tests.ps1 [hunk 5]
```diff
@@ -0,0 +1,81 @@
...
+    }
+
+    It "Find resource given specific Name and Repository" {
+        $res = Find-PSResource -Name $TestModuleName -Repository $ADORepoName -Verbose
+        $res.Name | Should -Be $TestModuleName
+    }
+    
+    It "Install resource given specific Name and Repository" {
+        Install-PSResource -Name $TestModuleName -Repository $ADORepoName
+
```
Comment (adityapatwardhan) [inline test/CredentialProvider.Tests.ps1]:
```suggestion
```

**Review by adityapatwardhan — CHANGES_REQUESTED** [review]

File: src/code/Utils.cs [hunk 6]
```diff
@@ -992,6 +996,37 @@ public static NetworkCredential SetCredentialProviderNetworkCredential(
...
+            }
+
+            return networkCreds;
+        }     
+
+        #endregion
+
+        #region Container Registry methods
+
+        public static bool IsContainerRegistry(string uri)
```
Comment (adityapatwardhan) [inline src/code/Utils.cs]: I think this would be better if it is part of the PSRespositoryInfo.cs. Seems like cleaner design since the method is specifically operating on the registry. The isMARRepository method is also there which can be reused in this methods implementation.

Also realized that we might have to add support for GitHub container registry. But that should be a separate PR.

File: src/code/Utils.cs [hunk 7]
```diff
@@ -992,6 +996,37 @@ public static NetworkCredential SetCredentialProviderNetworkCredential(
             return networkCredential;
         }
 
+        public static NetworkCredential SetNetworkCredentials(PSRepositoryInfo repository, NetworkCredential networkCredential, PSCmdlet cmdletPassedIn)
```
Comment (adityapatwardhan) [inline src/code/Utils.cs]: Another slight refactoring suggestion to consider for cleaner design. If the credential is tied to a repository, consider have that as a property on the PSRespositoryInfo object. So that you dont have to carry around the credential and the repository object in all calls to various methods.

File: src/code/Utils.cs [hunk 8]
```diff
@@ -1259,19 +1294,21 @@ internal static void GetMetadataFilesFromPath(string dirPath, string packageName
...
         {
+            fileFound = String.Empty;
             var files = Directory.GetFiles(directory);
             foreach (var file in files)
             {
                 if (string.Equals(Path.GetFileName(file), fileName, StringComparison.OrdinalIgnoreCase))
                 {
-                    return file;
+                    fileFound = file;
+                    return true;
```
Comment (adityapatwardhan) [inline src/code/Utils.cs:1275]: Add a break here to stop the loop after finding the file.

**Review by adityapatwardhan — CHANGES_REQUESTED** [review]

File: src/code/Utils.cs (hunk 8 above)
Comment (alerickson) [reply src/code/Utils.cs:1275]: Returning here should break the loop when it exists the method, right?

Comment (adityapatwardhan) [reply src/code/Utils.cs:1275]: Yes, you are correct.

**Review by adityapatwardhan — APPROVED** [review]

File: src/code/PSRepositoryInfo.cs [hunk 9]
```diff
@@ -104,9 +101,36 @@ public enum RepositoryProviderType
 
         internal bool IsMARRepository()
         {
-            return (ApiVersion == APIVersion.ContainerRegistry && Uri.Host.StartsWith("mcr.microsoft") );
+            return (ApiVersion == APIVersion.ContainerRegistry && Uri.Host.StartsWith("mcr.microsoft"));
+        }
+
+        public static bool IsContainerRegistry(string uri)
+        {
+            if (uri.EndsWith(".azurecr.io") || uri.EndsWith(".azurecr.io/") || uri.Contains("mcr.microsoft.com") || uri.StartsWith("mcr.microsoft"))
```
Comment (adityapatwardhan) [inline src/code/PSRepositoryInfo.cs]: nitpick.. can re-use the IsMARRepository function here.

Comment (adityapatwardhan) [reply src/code/PSRepositoryInfo.cs]: Also should check is the ApiVersion == APIVersion.ContainerRegistry

Comment (alerickson) [reply src/code/PSRepositoryInfo.cs]: Good point, let me add that

Comment (alerickson) [reply src/code/PSRepositoryInfo.cs]: Oh I just realized I can't use IsMARRepository() because IsContainerRegistry needs to be a static class since it gets called when creating dynamic parameters.  However, I am adding the ApiVersion check to IsContainerRegistry()

**Review by adityapatwardhan — APPROVED** [review]

**Comment by deadlydog** [comment]
Unfortunately, this still does not work and always returns 401 unauthorized errors. I provided evidence in #1601.
