### PR TITLE
For Publish operation to ACR, non-anonymous access token should be retrieved

### LINKED ISSUE #1906: Publish-PSResource uses anonymous token for push when anonymousPull is enabled on ACR
### Prerequisites

- [x] Write a descriptive title.
- [x] Make sure you are able to repro it on the [latest released version](https://www.powershellgallery.com/packages/Microsoft.PowerShell.PSResourceGet)
- [x] Search the existing issues.

### Steps to reproduce

Simular to #1828, but that got closed without it being resolved!

When anonymousPull is enabled on an Azure Container Registry (ACR) and the registry is registered as a PSResource repository, Publish-PSResource always retrieves an anonymous access token—even if valid Azure credentials are available (via Connect-AzAccount ). This causes push operations to fail with 401 Unauthorized.

Verbose Output Example:
```
Publish-PSResource -Repository <RepoName> -Path <PathToModuleFiles>

VERBOSE: Get access token for container registry server.
VERBOSE: Anonymous access token retrieved.
VERBOSE: Start uploading blob
Publish-PSResource: Error occured while starting to upload the blob location used for publishing to ContainerRegistry: Response status code does not indicate success: 401 (Unauthorized).
```

FYI!
- The account has ArcPush activated on the ACR.
- Login prompt does appear when Anonymous access is Disabled on the ACR, and the publish can be completed successfully.

### Expected behavior

```console
- Anonymous access should only be used for pull operations.
- For push, PSResourceGet should either provide a login prompt or attempt authenticated token acquisition if credentials or Azure context exist.
```

### Actual behavior

```console
Error 401 (Unauthorized), because Anonymous access token was used

VERBOSE: Get access token for container registry server.
VERBOSE: Anonymous access token retrieved.
VERBOSE: Start uploading blob
Publish-PSResource: One or more errors occurred. (Error occured while starting to upload the blob location used for publishing to ContainerRegistry: System.Net.Http.HttpRequestException 'Error occured while trying to retrieve response header: Error occured while trying to retrieve response: Response status code does not indicate success: 401 (Unauthorized).')
```

### Error details

```console
Exception             :
    Type            : System.AggregateException
    InnerExceptions :
        Type       : Microsoft.PowerShell.PSResourceGet.UtilClasses.UploadBlobException
        TargetSite :
            Name          : MoveNext
            DeclaringType : [Microsoft.PowerShell.PSResourceGet.ContainerRegistryServerAPICalls+<GetStartUploadBlobLoca
tion>d__71]
            MemberType    : Method
            Module        : Microsoft.PowerShell.PSResourceGet.dll
        Message    : Error occured while starting to upload the blob location used for publishing to ContainerRegistry:
 System.Net.Http.HttpRequestException 'Error occured while trying to retrieve response header: Error occured while tryi
ng to retrieve response: Response status code does not indicate success: 401 (Unauthorized).'
        Source     : Microsoft.PowerShell.PSResourceGet
        HResult    : -2146233088
        StackTrace :
   at Microsoft.PowerShell.PSResourceGet.ContainerRegistryServerAPICalls.GetStartUploadBlobLocation(String packageName,
 String containerRegistryAccessToken) in C:\__w\1\s\PSResourceGet\src\code\ContainerRegistryServerAPICalls.cs:line 1660
    Message         : One or more errors occurred. (Error occured while starting to upload the blob location used for p
ublishing to ContainerRegistry: System.Net.Http.HttpRequestException 'Error occured while trying to retrieve response h
eader: Error occured while trying to retrieve response: Response status code does not indicate success: 401 (Unauthoriz
ed).')
    TargetSite      :
        Name          : ThrowIfExceptional
        DeclaringType : [System.Threading.Tasks.Task]
        MemberType    : Method
        Module        : System.Private.CoreLib.dll
    InnerException  :
        Type       : Microsoft.PowerShell.PSResourceGet.UtilClasses.UploadBlobException
        TargetSite :
            Name          : MoveNext
            DeclaringType : [Microsoft.PowerShell.PSResourceGet.ContainerRegistryServerAPICalls+<GetStartUploadBlobLoca
tion>d__71]
            MemberType    : Method
            Module        : Microsoft.PowerShell.PSResourceGet.dll
        Message    : Error occured while starting to upload the blob location used for publishing to ContainerRegistry:
 System.Net.Http.HttpRequestException 'Error occured while trying to retrieve response header: Error occured while tryi
ng to retrieve response: Response status code does not indicate success: 401 (Unauthorized).'
        Source     : Microsoft.PowerShell.PSResourceGet
        HResult    : -2146233088
        StackTrace :
   at Microsoft.PowerShell.PSResourceGet.ContainerRegistryServerAPICalls.GetStartUploadBlobLocation(String packageName,
 String containerRegistryAccessToken) in C:\__w\1\s\PSResourceGet\src\code\ContainerRegistryServerAPICalls.cs:line 1660
    Source          : System.Private.CoreLib
    HResult         : -2146233088
    StackTrace      :
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at Microsoft.PowerShell.PSResourceGet.ContainerRegistryServerAPICalls.UploadNupkgFile(String packageNameLowercase, S
tring containerRegistryAccessToken, String fullNupkgFile, ErrorRecord& errRecord) in C:\__w\1\s\PSResourceGet\src\code\
ContainerRegistryServerAPICalls.cs:line 1294
TargetObject          : Microsoft.PowerShell.PSResourceGet.Cmdlets.PublishPSResource
CategoryInfo          : InvalidResult: (Microsoft.PowerShel…s.PublishPSResource:PublishPSResource) [Publish-PSResource]
, AggregateException
FullyQualifiedErrorId : StartUploadBlobLocationError,Microsoft.PowerShell.PSResourceGet.Cmdlets.PublishPSResource
InvocationInfo        :
    MyCommand        : Publish-PSResource
    ScriptLineNumber : 1
    OffsetInLine     : 1
    HistoryId        : 40
    Line             : Publish-PSResource -Repository <RepoName> -Path <PathToModuleFiles> -Verbose
    Statement        : Publish-PSResource -Repository <RepoName> -Path <PathToModuleFiles> -Verbose
    PositionMessage  : At line:1 char:1
                       + Publish-PSResource -Repository <RepoName> -Path "$env:UserProfil …
                       + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    InvocationName   : Publish-PSResource
    CommandOrigin    : Internal
ScriptStackTrace      : at <ScriptBlock>, <No file>: line 1
PipelineIterationInfo :
      0
      1
```

### Environment data

```powershell
- PSResourceGet version: 1.1.1.1
- Azure Container Registry with anonymousPull = true and Private Endpoint enabled
- Account has active ArcPush role
- Get-Host

Name             : ConsoleHost
Version          : 7.5.4
InstanceId       : e0061f15-1059-417f-bc00-c593e232dbde
UI               : System.Management.Automation.Internal.Host.InternalHostUserInterface
CurrentCulture   : nl-NL
CurrentUICulture : nl-NL
PrivateData      : Microsoft.PowerShell.ConsoleHost+ConsoleColorProxy
DebuggerEnabled  : True
IsRunspacePushed : False
Runspace         : System.Management.Automation.Runspaces.LocalRunspace
```

### Visuals

_No response_

### PR DESCRIPTION
**Pull request by anamnavi**
If a Container Registry has anonymous pull enabled, PSResourceGet was using that alone to determine that the registry is unauthenticated and therefore retrieving an anonymous access token. However, that doesn't account for push operation which would require permissions. This was causing registries with anonymous pull that had push operation being performed on it to result in a 401 error even if the user had ACRPush permissions. 

# PR Summary

## PR Context
Fixes #1906 #1828 

## PR Checklist

- [x] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [x] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.
- **[Breaking changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)**
    - [ ] None
    - **OR**
    - [ ] [Documentation needed]()
        - [ ] Issue filed: 
- **User-facing changes**
    - [ ] Not Applicable
    - **OR**
    - [ ] [Documentation needed]()
        - [ ] Issue filed: 
- **Testing - New and feature**
    - [ ] N/A or can only be tested interactively
    - **OR**
    - [ ] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
- **Tooling**
    - [ ] I have considered the user experience from a tooling perspective and don't believe tooling will be impacted.
    - **OR**
    - [ ] I have considered the user experience from a tooling perspective and enumerated concerns in the summary.

### CODE REVIEW

File: src/code/ContainerRegistryServerAPICalls.cs [hunk 1]
```diff
@@ -398,7 +398,9 @@ internal string GetContainerRegistryAccessToken(bool needCatalogAccess, out Erro
             }
             else
             {
-                bool isRepositoryUnauthenticated = IsContainerRegistryUnauthenticated(Repository.Uri.ToString(), needCatalogAccess, out errRecord, out accessToken);
+                bool isRepositoryUnauthenticated = isPushOperation ? false : IsContainerRegistryUnauthenticated(Repository.Uri.ToString(), needCatalogAccess, out errRecord, out accessToken);
```
Comment (adityapatwardhan) [inline src/code/ContainerRegistryServerAPICalls.cs:412]: Add a comment why we set the isRepositoryUnauthenticated as false when it is a push operation

File: test/PublishPSResourceTests/PublishPSResourceContainerRegistryServer.Tests.ps1 [hunk 2]
```diff
@@ -346,6 +346,25 @@ Describe "Test Publish-PSResource" -tags 'CI' {
         $results[0].Version | Should -Be $correctVersion
     }
 
+    It "Publish a package should always require authentication" {
+        $version = "15.0.0"
+        New-ModuleManifest -Path (Join-Path -Path $script:PublishModuleBase -ChildPath "$script:PublishModuleName.psd1") -ModuleVersion $version -Description "$script:PublishModuleName module"
+
+        $infoRecord = & { Publish-PSResource -Path $script:PublishModuleBase -Repository $ACRRepoName 6>&1 } | Where-Object { $_ -is [System.Management.Automation.InformationRecord] }
+
```
Comment (adityapatwardhan) [inline test/PublishPSResourceTests/PublishPSResourceContainerRegistryServer.Tests.ps1]: If you want to try reverting to using -InformationVariable

**Review by adityapatwardhan — APPROVED** [review]
