### PR TITLE
Bug fix for setting 'unknown' repository APIVersion

### LINKED ISSUE #1347: Set-PSResourceRepository the 'ApiVersion' parameter raises an exception if the value 'Unknown' is specified
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://www.powershellgallery.com/packages/PSResourceGet)
- [X] Search the existing issues.

### Steps to reproduce

```Powershell
Set-PSResourceRepository PSGallery -ApiVersion 'unknown'
```

Note:
This call works : 
```Powershell
Set-PSResourceRepository PSGallery -ApiVersion 'unknown' -Trusted
# or Set-PSResourceRepository PSGallery -ApiVersion 'unknown' -Priority 50

Get-psResourceRepository |select name,apiversion

Name        ApiVersion
----        ----------
PSGallery      unknown
PSRepoLocal    unknown
```

In the following case the error message indicates the value 'unknow' as allowed...
```Powershell
C:\temp> set-psResourceRepository PSRepoLocal -ApiVersion 'Test'
Set-PSResourceRepository : Impossible de lier le paramètre «ApiVersion». Impossible de convertir la valeur «Test» en
type «Microsoft.PowerShell.PSResourceGet.UtilClasses.PSRepositoryInfo+APIVersion». Erreur: «Impossible de faire
correspondre le nom d'identificateur Test à un nom d'énumérateur valide. Spécifiez l'un des noms d'énumérateur
suivants et réessayez :
unknown, v2, v3, local, nugetServer »
```

### Expected behavior

```console
?
The documentation is not up to date so I don't know if it's a bug or not.

```
According to this [code](https://github.com/PowerShell/PSResourceGet/blob/931115343784bdc1c716c46c99d9ecf2767c01f5/src/code/RepositorySettings.cs#L209) it seems to be correct but this confuses me :-)

### Actual behavior

```console
> set-psResourceRepository PSGallery -ApiVersion 'unknown'
set-psResourceRepository : Must set Uri, Priority, Trusted, ApiVersion, or CredentialInfo parameter
Au caractère Ligne:1 : 1
+ set-psResourceRepository PSGallery -ApiVersion 'unknown'
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument : (Microsoft.Power...ourceRepository:SetPSResourceRepository) [Set-PSRes
   ourceRepository], PSInvalidOperationException
    + FullyQualifiedErrorId : ErrorInNameParameterSet,Microsoft.PowerShell.PSResourceGet.Cmdlets.SetPSResourceRepository
```

### Error details

```console
$Error[0]|select *


PSMessageDetails      :
Exception             : System.Management.Automation.PSInvalidOperationException: Must set Uri, Priority, Trusted,
                        ApiVersion, or CredentialInfo parameter
                           à System.Management.Automation.MshCommandRuntime.ThrowTerminatingError(ErrorRecord
                        errorRecord)
TargetObject          : Microsoft.PowerShell.PSResourceGet.Cmdlets.SetPSResourceRepository
CategoryInfo          : InvalidArgument : (Microsoft.Power...ourceRepository:SetPSResourceRepository)
                        [Set-PSResourceRepository], PSInvalidOperationException
FullyQualifiedErrorId : ErrorInNameParameterSet,Microsoft.PowerShell.PSResourceGet.Cmdlets.SetPSResourceRepository
ErrorDetails          :
InvocationInfo        : System.Management.Automation.InvocationInfo
ScriptStackTrace      : à <ScriptBlock>, <Aucun fichier> : ligne 1
PipelineIterationInfo : {}
```

### Environment data

```powershell
ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Binary     0.5.23     Microsoft.PowerShell.PSResourceGet  {Find-PSResource, Get-InstalledPSResource, Get-PSResourceR...

Key   : PSVersion
Value : 5.1.19041.3031
Name  : PSVersion


Key   : PSEdition
Value : Desktop
Name  : PSEdition


Key   : PSCompatibleVersions
Value : {1.0, 2.0, 3.0, 4.0, 5.0, 5.1.19041.3031}
Name  : PSCompatibleVersions


Key   : BuildVersion
Value : 10.0.19041.3031
Name  : BuildVersion


Key   : CLRVersion
Value : 4.0.30319.42000
Name  : CLRVersion


Key   : WSManStackVersion
Value : 3.0
Name  : WSManStackVersion


Key   : PSRemotingProtocolVersion
Value : 2.3
Name  : PSRemotingProtocolVersion


Key   : SerializationVersion
Value : 1.1.0.1
Name  : SerializationVersion
```

### Visuals

_No response_

### PR DESCRIPTION
**Pull request by alerickson**
# PR Summary

Resolves #1347 

## PR Checklist

- [x] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [x] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.
- **[Breaking changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)**
    - [x] None
    - **OR**
    - [ ] [Documentation needed]()
        - [ ] Issue filed: 
- **User-facing changes**
    - [x] Not Applicable
    - **OR**
    - [ ] [Documentation needed]()
        - [ ] Issue filed: 
- **Testing - New and feature**
    - [ ] N/A or can only be tested interactively
    - **OR**
    - [x] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
- **Tooling**
    - [x] I have considered the user experience from a tooling perspective and don't believe tooling will be impacted.
    - **OR**
    - [ ] I have considered the user experience from a tooling perspective and enumerated concerns in the summary.

### CODE REVIEW

File: src/code/SetPSResourceRepository.cs [hunk 1]
```diff
@@ -111,6 +111,22 @@ protected override void BeginProcessing()
...
         protected override void ProcessRecord()
         {
+            // determine if either 1 of 5 values are attempting to be set: Uri, Priority, Trusted, APIVerison, CredentialInfo.
+            // if none are (i.e only Name parameter was provided, write error)
+            if (!MyInvocation.BoundParameters.ContainsKey(nameof(Uri)) &&
+                !MyInvocation.BoundParameters.ContainsKey(nameof(Priority)) &&
+                !MyInvocation.BoundParameters.ContainsKey(nameof(Trusted)) &&
+                !MyInvocation.BoundParameters.ContainsKey(nameof(ApiVersion)) &&
+                !MyInvocation.BoundParameters.ContainsKey(nameof(CredentialInfo)) &&
+                !MyInvocation.BoundParameters.ContainsKey(nameof(Repository)))
```
Comment (anamnavi) [inline src/code/SetPSResourceRepository.cs]: I'm not sure that checking if Repository parameter wasn't passed in makes sense in this situation. If the user only passed in a value for `-Repository` this condition would be false and no error written. Even though that means that no other parameters like `-Priority`, `-Trusted`, `-ApiVersion` or `-CredentialInfo` were passed in.

I think we shouldn't account for `-Repository` not passed in in this condition. Instead we could have a separate condition/error handling block of code after this that errors if `-Repository` was not passed in.

**Review by anamnavi — CHANGES_REQUESTED** [review]

File: src/code/SetPSResourceRepository.cs (hunk 1 above)
Comment (alerickson) [reply src/code/SetPSResourceRepository.cs]: I'm a bit confused, why put it into a separate condition/block?

If we remove line 121 
`Set-PSResourceRepository -Repository <input>` will always fail and never get to the second condition/block because it does not have values for `-Priority`, `-Trusted`, `-ApiVersion` or `-CredentialInfo`

Comment (anamnavi) [reply src/code/SetPSResourceRepository.cs]: actually, `-Name` and `-Repository` are mandatory for their respective parameter sets. So we don't need a condition for them at all as that validation will happen at parameter binding time.

Comment (anamnavi) [reply src/code/SetPSResourceRepository.cs]: `MyInvocation.BoundParameters.ContainsKey(nameof(Name))` or check name psset

**Review by anamnavi — APPROVED** [review]
LGTM
