### PR TITLE
fix find repo looping to not use highest priority repo matching

### LINKED ISSUE #1286: Find-PSResource error messages [needs design doc published]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://www.powershellgallery.com/packages/PSResourceGet)
- [X] Search the existing issues.

### Steps to reproduce

1 - Create a local repository ( file system) with the name 'PSRepoLocal' *  with the same priority of PSGallery repository
2 - Publish one or more versions of a module 'XYZ' into 'PSRepoLocal' repository
3 - Use 
```Powershell
Find-PSResource -Name 'XYZ'
```

`* Note : I have not tested with a repository name 'PSABC' that influences the search order.

### Expected behavior

```console
No error when a searched module does not exist in a repository.

I'm looking to find out where the module exists, not where the module doesn't exist.
```

### Actual behavior

```console
Throw an error when a searched module do not exist into a repository
```

### Error details

```console
$error[0]|select *


writeErrorStream      : True
PSMessageDetails      :
Exception             : System.Management.Automation.PSInvalidOperationException: Package with search criteria: Name
                        lowercase could not be found due to: Package does not exist on the server..
TargetObject          : Microsoft.PowerShell.PSResourceGet.Cmdlets.FindHelper
CategoryInfo          : NotSpecified: (Microsoft.Power...lets.FindHelper:FindHelper) [Find-PSResource],
                        PSInvalidOperationException
FullyQualifiedErrorId : FindNameResponseConversionFail,Microsoft.PowerShell.PSResourceGet.Cmdlets.FindPSResource
ErrorDetails          :
InvocationInfo        : System.Management.Automation.InvocationInfo
ScriptStackTrace      : à <ScriptBlock>, <Aucun fichier> : ligne 1
PipelineIterationInfo : {0, 1}




$StackTrace
   à System.Management.Automation.ParameterBinderController.ReparseUnboundArguments()
   à System.Management.Automation.CmdletParameterBinderController.BindCommandLineParametersNoValidation(Collection`1 arguments)
   à System.Management.Automation.CmdletParameterBinderController.BindCommandLineParameters(Collection`1 arguments)
   à System.Management.Automation.CommandProcessor.BindCommandLineParameters()
   à System.Management.Automation.CommandProcessor.Prepare(IDictionary psDefaultParameterValues)
   à System.Management.Automation.CommandProcessorBase.DoPrepare(IDictionary psDefaultParameterValues)
   à System.Management.Automation.Internal.PipelineProcessor.Start(Boolean incomingStream)
   à System.Management.Automation.Internal.PipelineProcessor.SynchronousExecuteEnumerate(Object input)
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   à System.Management.Automation.Internal.PipelineProcessor.SynchronousExecuteEnumerate(Object input)
   à System.Management.Automation.PipelineOps.InvokePipeline(Object input, Boolean ignoreInput, CommandParameterInternal[][] pipeElements, CommandBaseAst[] pipeElementAsts, CommandRedirection[][] commandRedirections, FunctionContext funcContext)
   à System.Management.Automation.Interpreter.ActionCallInstruction`6.Run(InterpretedFrame frame)
   à System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
```

### Environment data

```powershell
Get-Module Microsoft.PowerShell.PSResourceGet

ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Binary     0.5.22     Microsoft.PowerShell.PSResourceGet  {Find-PSResource, Get-InstalledPSResource, Get-PSResourceR...


$PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.1.19041.3031
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0, 5.0, 5.1.19041.3031}
BuildVersion                   10.0.19041.3031
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

### Visuals

image

### PR DESCRIPTION
**Pull request by anamnavi**
# PR Summary
Find-PSResource previously conducted search with highest priority repository matching. While searching through multiple repositories, it would write errors for the repositories it couldn't find the package from, and after it found it from a repository it would not continue searching.

Our search will now follow the below scenarios/rules:
* `Find-PSResource "pkg"` (without `-Repository`): search all repositories registered, return "pkg" from each repository where it is found, if "pkg" is not found in any repo report error
* `Find-PSResource "pkg" -Repository *Gallery`: search all repositories whose names match the pattern (i.e PSGallery, NuGetGallery), return "pkg" from each of these repositories where it exists, if "pkg" is not found in any repo report error
* `Find-PSResource "pkg" -Repository PSGallery`: search specific repository, return "pkg" from it if found, if not found report error
* `Find-PSResource "pkg" -Repository PSGallery, NuGetGallery`: search specific repositories, for each: repo return "pkg" if found but if not write error.

## PR Context
Resolves #1286 

## PR Checklist

- [ ] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [ ] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [ ] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [ ] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.
- **[Breaking changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)**
    - [ ] None
    - **OR**
    - [ ] [Documentation needed]()
        - [ ] Issue filed: 
- **User-facing changes**
    - [ ] Not Applicable
    - **OR**
    - [ ] [Documentation needed]()
        - [ ] Issue filed: 
- **Testing - New and feature**
    - [ ] N/A or can only be tested interactively
    - **OR**
    - [ ] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
- **Tooling**
    - [ ] I have considered the user experience from a tooling perspective and don't believe tooling will be impacted.
    - **OR**
    - [ ] I have considered the user experience from a tooling perspective and enumerated concerns in the summary.

### CODE REVIEW

File: src/code/InstallHelper.cs [hunk 1]
```diff
@@ -220,14 +220,14 @@ public InstallHelper(PSCmdlet cmdletPassedIn, NetworkCredential networkCredentia
...
 
-                if (repo.ApiVersion == PSRepositoryInfo.APIVersion.unknown)
-                {
-                    _cmdletPassedIn.ThrowTerminatingError(new ErrorRecord(
-                        new ArgumentException($"Repository {repoName} has unknown API Version."),
-                        "RepositoryAPIVersionUnknownError",
-                        ErrorCategory.InvalidOperation,
-                        this));
-                }
+                // if (repo.ApiVersion == PSRepositoryInfo.APIVersion.unknown)
```
Comment (anamnavi) [inline src/code/InstallHelper.cs:223]: I remove this as it is already accounted for on L201 above

File: test/FindPSResourceTests/FindPSResourceV2Server.Tests.ps1 [hunk 2]
```diff
@@ -404,23 +397,6 @@ Describe 'Test HTTP Find-PSResource for V2 Server Protocol' -tags 'CI' {
...
-
-    It "should not find resource given nonexistant Name and no specified repository" {
-        $res = Find-PSResource -Name NonExistantModule -ErrorVariable err -ErrorAction SilentlyContinue
-        $res | Should -BeNullOrEmpty
-        $err.Count | Should -Be 1
-        $err[0].FullyQualifiedErrorId | Should -BeExactly "PackageNotFound,Microsoft.PowerShell.PSResourceGet.Cmdlets.FindPSResource"
-        $res | Should -BeNullOrEmpty
-    }
-
-    It "should find resource and write error for other resource not found when multiple packages are specified" {
```
Comment (alerickson) [inline test/FindPSResourceTests/FindPSResourceV2Server.Tests.ps1:416]: I think we should add some more tests similar to this (ie multiple pkg names, wildcard in pkg name, etc.) into the RepositorySearching test file.

File: src/code/FindHelper.cs [hunk 3]
```diff
@@ -93,8 +96,41 @@ public FindHelper(CancellationToken cancellationToken, PSCmdlet cmdletPassedIn,
                                 ErrorCategory.InvalidArgument,
                                 this));
                 }
+
+                // Iff repository entries includes wildcards and nonwildcard names, write terminating error
```
Comment (alerickson) [inline src/code/FindHelper.cs]:
```suggestion
                // If repository entries includes wildcards and non-wildcard names, write terminating error
```

File: src/code/FindHelper.cs [hunk 4]
```diff
@@ -154,7 +188,8 @@ public FindHelper(CancellationToken cancellationToken, PSCmdlet cmdletPassedIn,
 
                 _cmdletPassedIn.WriteVerbose(string.Format("Searching in repository {0}", repositoriesToSearch[i].Name));
 
-                foreach (PSResourceInfo currentPkg in SearchByNames(currentServer, currentResponseUtil, currentRepository))
+                bool shouldReportErrorForEachRepo = !suppressErrors && !_repositoryNameContainsWildcard;
+                foreach (PSResourceInfo currentPkg in SearchByNames(currentServer, currentResponseUtil, currentRepository, shouldReportErrorForEachRepo: shouldReportErrorForEachRepo))
```
Comment (alerickson) [inline src/code/FindHelper.cs]:
```suggestion
                foreach (PSResourceInfo currentPkg in SearchByNames(currentServer, currentResponseUtil, currentRepository, shouldReportErrorForEachRepo))
```

File: src/code/FindHelper.cs [hunk 5]
```diff
@@ -469,21 +509,36 @@ private IEnumerable<PSResourceInfo> SearchByNames(ServerApiCall currentServer, R
...
+                            {
+                                _cmdletPassedIn.WriteVerbose(errRecord.Exception.Message);
+                            }
+
                             continue;
                         }
 
                         foreach (PSResourceResult currentResult in currentResponseUtil.ConvertToPSResourceResult(responseResults: responses))
                         {
+                            // Note: this currently catches for V2ServerApiCalls. TODO: eventually move off this.
```
Comment (alerickson) [inline src/code/FindHelper.cs]: Just curious what this comment means... what should we eventually move off of?

**Review by alerickson — APPROVED** [review]
Looks good, one larger suggestions is to use a ternary operator for all the error/verbose writing:

```
if (shouldReportErrorForEachRepo)
{
     _cmdletPassedIn.WriteError(errRecord);
 }
 else
 {
     _cmdletPassedIn.WriteVerbose(errRecord.Exception.Message);
 }
```

File: src/code/FindHelper.cs (hunk 5 above)
Comment (anamnavi) [reply src/code/FindHelper.cs]: Good catch, I'll create an issue for this. I meant that instead of us catching "package not found" kinda scenarios for V2 server at ResponseUtil.ConvertToPSResourceResult() time, I found a way to detect it at the ServerApiCall level. This would then be consistent for all server classes we support to error handle at that level I'd do that in a separate PR though

Comment (anamnavi) [reply src/code/FindHelper.cs]: Issue created: https://github.com/PowerShell/PSResourceGet/issues/1349
