### PR TITLE
ACR: Ensure versions returned are sorted and can be correctly compared if number of trailing zeroes differ

### LINKED ISSUE #1581: ACR: Versions are not in order
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://www.powershellgallery.com/packages/Microsoft.PowerShell.PSResourceGet)
- [X] Search the existing issues.

### Steps to reproduce

Versions (which are ACR tags) are not guaranteed to be in alphabetical or numerical order, just chronological wrt to when they were published. When performing search with globbing patterns, ensure versions are in order.

### Expected behavior

```console
Versions should be sorted into some order, so that they are returned in decreasing numerical order.
```

### Actual behavior

```console
Versions are in order of when they were published.
```

### Error details

_No response_

### Environment data

```powershell
all plaforms.
```

### Visuals

_No response_

### PR DESCRIPTION
**Pull request by anamnavi**
Versions stored in ACR are not present in numerical order, instead they use chronological order of when the repository tag (i.e version in our context) is published. This PR sorts tags (i.e versions) returned in FindACRImageTags().

The tag is a string, but we use it for version and version can be a NuGetVersion that may have different number of trailing 0's but the normalized version would be the same. So if a version "1.0.0" is published, the user input of version "1.0" or "1.0.0.0" should also match it but previously did not. This PR fixes this by finding the exact tag (i.e version) from the server and using that when we call GetACRMetadata().

Also add support for prerelease versions.

# PR Summary

## PR Context
Resolves #1581 #1582 #1584

## PR Checklist

- [x] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [x] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [ ] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.
- **[Breaking changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)**
    - [ ] None
    - **OR**
    - [ ] [Documentation needed]()
        - [ ] Issue filed: 
- **User-facing changes**
    - [ ] Not Applicable
    - **OR**
    - [ ] [Documentation needed]()
        - [ ] Issue filed: 
- **Testing - New and feature**
    - [ ] N/A or can only be tested interactively
    - **OR**
    - [ ] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
- **Tooling**
    - [ ] I have considered the user experience from a tooling perspective and don't believe tooling will be impacted.
    - **OR**
    - [ ] I have considered the user experience from a tooling perspective and enumerated concerns in the summary.

### CODE REVIEW

File: src/code/ACRServerAPICalls.cs [hunk 1]
```diff
@@ -1687,6 +1675,69 @@ private string CreateMetadataContent(string manifestFilePath, ResourceType resou
...
+                    }
+
+                    _cmdletPassedIn.WriteDebug($"'{packageName}' version parsed as '{pkgVersion}'");
+
+                    if (isSpecificVersionSearch)
+                    {
+                        if (pkgVersion.ToNormalizedString() == specificVersion.ToNormalizedString())
+                        {
+                            // NuGet.Versioning.SemanticVersion semanticVersionOfPkg = new SemanticVersion(pkgVersion.Major, pkgVersion.Minor, pkgVersion.Patch, pkgVersion.IsPrerelease ? pkgVersion.Release: String.Empty);
+                            // sortedPkgs.Add(semanticVersionOfPkg, pkgVersionElement.ToString());
```
Comment (adityapatwardhan) [inline src/code/ACRServerAPICalls.cs]:
```suggestion
```

File: src/code/ACRServerAPICalls.cs [hunk 2]
```diff
@@ -1687,6 +1675,69 @@ private string CreateMetadataContent(string manifestFilePath, ResourceType resou
...
+                            sortedPkgs.Add(pkgVersion, pkgVersionElement.ToString());
+                            break;
+                        }
+                    }
+                    else
+                    {
+                        if (versionRange.Satisfies(pkgVersion) && (!pkgVersion.IsPrerelease || includePrerelease))
+                        {
+                            // NuGet.Versioning.SemanticVersion semanticVersionOfPkg = new SemanticVersion(pkgVersion.Major, pkgVersion.Minor, pkgVersion.Patch, pkgVersion.IsPrerelease ? pkgVersion.Release: String.Empty);
+                            // sortedPkgs.Add(semanticVersionOfPkg, pkgVersionElement.ToString());
```
Comment (adityapatwardhan) [inline src/code/ACRServerAPICalls.cs]:
```suggestion
```

File: src/code/ACRServerAPICalls.cs [hunk 3]
```diff
@@ -1687,6 +1675,69 @@ private string CreateMetadataContent(string manifestFilePath, ResourceType resou
...
+                            sortedPkgs.Add(pkgVersion, pkgVersionElement.ToString());
+                        }
+                    }
+
```
Comment (adityapatwardhan) [inline src/code/ACRServerAPICalls.cs]:
```suggestion
```

File: src/code/ACRServerAPICalls.cs [hunk 4]
```diff
@@ -1687,6 +1675,69 @@ private string CreateMetadataContent(string manifestFilePath, ResourceType resou
...
+                }
+            }
+
+            return sortedPkgs;
```
Comment (adityapatwardhan) [inline src/code/ACRServerAPICalls.cs:1701]: Maybe we should just reverse here as we always need it in descending order.

File: src/code/ACRServerAPICalls.cs [hunk 5]
```diff
@@ -1687,6 +1675,69 @@ private string CreateMetadataContent(string manifestFilePath, ResourceType resou
...
+                            new InvalidOrEmptyResponse($"Response does not contain version element ('name') for package '{packageName}' in '{Repository.Name}'."),
+                            "FindNameFailure",
+                            ErrorCategory.InvalidResult,
+                            this);
+
+                        return null;
+                    }
+
+                    // determine if the package version that is a repository tag is a valid NuGetVersion
+                    if (!NuGetVersion.TryParse(pkgVersionElement.ToString(), out NuGetVersion pkgVersion))
```
Comment (adityapatwardhan) [inline src/code/ACRServerAPICalls.cs]: we seem to be doing `pkgVersionElement.ToString()` a few times. Can we just store it in a string as reuse the string.

File: src/code/ACRServerAPICalls.cs [hunk 6]
```diff
@@ -143,59 +143,30 @@ public override FindResults FindName(string packageName, bool includePrerelease,
...
                 return new FindResults(stringResponse: new string[] { }, hashtableResponse: emptyHashResponses, responseType: acrFindResponseType);
             }
 
             List<Hashtable> latestVersionResponse = new List<Hashtable>();
             List<JToken> allVersionsList = foundTags["tags"].ToList();
-            allVersionsList.Reverse();
 
-            foreach (var pkgVersionTagInfo in allVersionsList)
+            SortedDictionary<NuGet.Versioning.SemanticVersion, string> sortedQualifyingPkgs = GetPackagesWithRequiredVersion(allVersionsList, VersionType.VersionRange, VersionRange.All, specificVersion: null, packageName, includePrerelease, out errRecord);
+            var pkgsInDescendingOrder = sortedQualifyingPkgs.Reverse();
```
Comment (adityapatwardhan) [inline src/code/ACRServerAPICalls.cs]: Null reference exception when an error happens in GetPackagesWithRequiredVersion and it returns null

File: src/code/ACRServerAPICalls.cs [hunk 7]
```diff
@@ -143,59 +143,30 @@ public override FindResults FindName(string packageName, bool includePrerelease,
...
             {
                 return new FindResults(stringResponse: new string[] { }, hashtableResponse: emptyHashResponses, responseType: acrFindResponseType);
             }
 
             List<Hashtable> latestVersionResponse = new List<Hashtable>();
             List<JToken> allVersionsList = foundTags["tags"].ToList();
-            allVersionsList.Reverse();
 
-            foreach (var pkgVersionTagInfo in allVersionsList)
+            SortedDictionary<NuGet.Versioning.SemanticVersion, string> sortedQualifyingPkgs = GetPackagesWithRequiredVersion(allVersionsList, VersionType.VersionRange, VersionRange.All, specificVersion: null, packageName, includePrerelease, out errRecord);
```
Comment (adityapatwardhan) [inline src/code/ACRServerAPICalls.cs]: Check for errRecord befor doing anything

File: src/code/ACRServerAPICalls.cs [hunk 8]
```diff
@@ -143,59 +143,30 @@ public override FindResults FindName(string packageName, bool includePrerelease,
...
-                        Hashtable metadata = GetACRMetadata(registry, packageNameLowercase, pkgVersion, acrAccessToken, out errRecord);
-                        if (errRecord != null || metadata.Count == 0)
-                        {
-                            return new FindResults(stringResponse: new string[] { }, hashtableResponse: emptyHashResponses, responseType: acrFindResponseType);
-                        }
-
-                        latestVersionResponse.Add(metadata);
-                        break;
-                    }
+                    return new FindResults(stringResponse: new string[] { }, hashtableResponse: emptyHashResponses, responseType: acrFindResponseType);
```
Comment (adityapatwardhan) [inline src/code/ACRServerAPICalls.cs]: Add a comment to explain what is happening here.

File: src/code/ACRServerAPICalls.cs [hunk 9]
```diff
@@ -281,53 +252,28 @@ public override FindResults FindVersionGlobbing(string packageName, VersionRange
...
             {
                 return new FindResults(stringResponse: new string[] { }, hashtableResponse: emptyHashResponses, responseType: acrFindResponseType);
             }
 
             List<Hashtable> latestVersionResponse = new List<Hashtable>();
             List<JToken> allVersionsList = foundTags["tags"].ToList();
-            allVersionsList.Reverse();
-            foreach (var packageVersion in allVersionsList)
+            SortedDictionary<NuGet.Versioning.SemanticVersion, string> sortedQualifyingPkgs = GetPackagesWithRequiredVersion(allVersionsList, VersionType.VersionRange, versionRange, specificVersion: null, packageName, includePrerelease, out errRecord);
+            var pkgsInDescendingOrder = sortedQualifyingPkgs.Reverse();
```
Comment (adityapatwardhan) [inline src/code/ACRServerAPICalls.cs]: Same as above, check for errRecord and potential null reference exception

**Review by adityapatwardhan — CHANGES_REQUESTED** [review]

File: test/PublishPSResourceTests/PublishPSResourceACRServer.Tests.ps1 [hunk 10]
```diff
@@ -371,10 +371,9 @@ Describe "Test Publish-PSResource" -tags 'CI' {
         $results[0].Version | Should -Be $scriptVersion
     }
 
-    <# This test does not work currently due to a bug if the last digit is 0. Link to issue: https://github.com/PowerShell/PSResourceGet/issues/1582
     It "Should publish a script without lines in between comment blocks locally" {
         $scriptName = "ScriptWithoutEmptyLinesBetweenCommentBlocks"
-        $scriptVersion = "1.0.0"
+        $scriptVersion = "1.0"
```
Comment (alerickson) [inline test/PublishPSResourceTests/PublishPSResourceACRServer.Tests.ps1:376]: Just out of curiosity, does it only work if version is a 2 digit number? Should we open an issue for this?

File: src/code/PSResourceInfo.cs [hunk 11]
```diff
@@ -849,6 +852,36 @@ public sealed class PSResourceInfo
 
                     metadata["NormalizedVersion"] = parsedNormalizedVersion;
```
Comment (alerickson) [inline src/code/PSResourceInfo.cs]: This isn't a part of your changes, but just wondering if parsedNormalizedVersion should be parsedNormalizedVersion.ToNormalizedString(), because I don't think the value itself is normalized yet.

File: src/code/PSResourceInfo.cs [hunk 12]
```diff
@@ -849,6 +852,36 @@ public sealed class PSResourceInfo
...
+                    if (!NuGetVersion.TryParse(versionValue, out NuGetVersion parsedNormalizedVersion) && pkgVersion == null)
+                    {
+                        errorMsg = string.Format(
+                            CultureInfo.InvariantCulture,
+                            @"TryConvertFromACRJson: Cannot parse NormalizedVersion or System.Version from version in metadata.");
+
+                        return false;
+                    }
+
+                    metadata["NormalizedVersion"] = parsedNormalizedVersion;
```
Comment (alerickson) [inline src/code/PSResourceInfo.cs]: Same question as above here, should this be parsedNormalizedVersion.ToNormalizedString()?

File: src/code/ACRServerAPICalls.cs [hunk 13]
```diff
@@ -365,19 +314,31 @@ public override FindResults FindVersion(string packageName, string version, Reso
...
+            }
 
-            if (errRecord != null)
+            List<Hashtable> latestVersionResponse = new List<Hashtable>();
+            List<JToken> allVersionsList = foundTags["tags"].ToList();
+
+            SortedDictionary<NuGet.Versioning.SemanticVersion, string> sortedQualifyingPkgs = GetPackagesWithRequiredVersion(allVersionsList, VersionType.SpecificVersion, VersionRange.All, requiredVersion, packageName, includePrereleaseVersions, out errRecord);
+            var pkgsInDescendingOrder = sortedQualifyingPkgs.Reverse();
+
+            foreach(var pkgVersionTag in pkgsInDescendingOrder)
```
Comment (alerickson) [inline src/code/ACRServerAPICalls.cs]: Lines 327-339 happens get repeated 2 other times in this file, consider separating out into a method that can be called.

File: src/code/ACRServerAPICalls.cs [hunk 14]
```diff
@@ -711,10 +687,22 @@ internal Hashtable GetACRMetadata(string registry, string packageName, NuGetVers
                     return requiredVersionResponse;
                 }
 
-                if (!NuGetVersion.TryParse(pkgVersionElement.ToString(), out NuGetVersion pkgVersion))
+
```
Comment (alerickson) [inline src/code/ACRServerAPICalls.cs]:
```suggestion
```

File: src/code/ACRServerAPICalls.cs (hunk 8 above)
Comment (anamnavi) [reply src/code/ACRServerAPICalls.cs]: do you mean leave a comment about why we return from the error case? or a comment about why we reverse order of packages?

File: src/code/ACRServerAPICalls.cs (hunk 4 above)
Comment (anamnavi) [reply src/code/ACRServerAPICalls.cs:1701]: Since `.Reverse()` is a LINQ method the return type of the method would then become `IEnumerable<KeyValuePair<NuGet.Versioning.SemanticVersion, string>>` ...is that too messy to have? If not I can change the method return type and return a reversed collection.

File: src/code/PSResourceInfo.cs (hunk 11 above)
Comment (anamnavi) [reply src/code/PSResourceInfo.cs]: You're right, good catch! I added that fix. I also factored out some of the shared code.

File: src/code/ACRServerAPICalls.cs (hunk 4 above)
Comment (adityapatwardhan) [reply src/code/ACRServerAPICalls.cs:1701]: Keep it as is.

File: src/code/ACRServerAPICalls.cs (hunk 8 above)
Comment (adityapatwardhan) [reply src/code/ACRServerAPICalls.cs]: Do we always return an empty FindResult response when we dont find one. If it is consistent, then its ok. Maybe instead of a new FindResults() everytime have a static one.

**Review by adityapatwardhan — APPROVED** [review]

File: src/code/ACRServerAPICalls.cs (hunk 8 above)
Comment (anamnavi) [reply src/code/ACRServerAPICalls.cs]: We always return an empty FindResult, so this is consistent. But I agree having a static one would be way better. I can do that in a separate PR.

**Review by alerickson — APPROVED** [review]
