### PR TITLE
Uri bug fix

### LINKED ISSUE #496: Register-PSResourceRepository is not accepting UNCs or File:// uris for local, file share nuget repositories
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://www.powershellgallery.com/packages/PowerShellGet)
- [X] Search the existing issues.

### Steps to reproduce

When attempting to register a local file-share-based Nuget repository, I consistently get errors.  This works on `Register-PSRepository` from PowerShellGet 2.2.5 and earlier.

```PowerShell
PS>  Register-PSResourceRepository -Name HCGallery -url \\hcgg.rest.of.domain.name\lobroot\ITxx\team\NuGet\ -Trusted
Register-PSResourceRepository: The URL provided is not valid: Microsoft.PowerShell.Core\FileSystem::\\hcgg.rest.of.domain.name\lobroot\ITxx\team\NuGet\
PS>  Register-PSResourceRepository -Name HCGallery -url file:\\hcgg.rest.of.domain.name\lobroot\ITxx\team\NuGet\ -Trusted
Register-PSResourceRepository: The URL provided is not valid: file:\\hcgg.rest.of.domain.name\lobroot\ITxx\team\NuGet\ and must be of Uri Scheme: HTTP, HTTPS, FTP or File
PS>  Register-PSResourceRepository -Name HCGallery -url "file://hcgg/lobroot/ITxx/team/NuGet" -Trusted 
Register-PSResourceRepository: The URL provided is not valid: file://hcgg/lobroot/ITxx/team/NuGet and must be of Uri Scheme: HTTP, HTTPS, FTP or File
```

### Expected behavior

```console
PS> Register-PSResourceRepository -Name HCGallery -url \\hcgg.rest.of.domain.name\lobroot\ITxx\team\NuGet\ -Trusted

Name      Url                                      Trusted Priority
----      ---                                      ------- --------
HCGallery \\hcgg.rest.of.domain.name\lobroot\IT...    True       50

The local repository should be registered
```

### Actual behavior

```console
Register-PSResourceRepository: The URL provided is not valid: Microsoft.PowerShell.Core\FileSystem::\\hcgg.rest.of.domain.name\lobroot\ITxx\team\NuGet\

or 

Register-PSResourceRepository: The URL provided is not valid: file:\\hcgg.rest.of.domain.name\lobroot\ITxx\team\NuGet\ and must be of Uri Scheme: HTTP, HTTPS, FTP or File
```

### Error details

```console
Exception             :
    Type       : System.ArgumentException
    Message    : The URL provided is not valid:
Microsoft.PowerShell.Core\FileSystem::\\hcgg.rest.of.domain.name\lobroot\ITxx\team\NuGet\
    TargetSite :
        Name          : ThrowTerminatingError
        DeclaringType : System.Management.Automation.MshCommandRuntime, System.Management.Automation, Version=7.1.4.0,
Culture=neutral, PublicKeyToken=31bf3856ad364e35
        MemberType    : Method
        Module        : System.Management.Automation.dll
    StackTrace :
   at System.Management.Automation.MshCommandRuntime.ThrowTerminatingError(ErrorRecord errorRecord)
    Source     : System.Management.Automation
    HResult    : -2147024809
CategoryInfo          : InvalidArgument: (:) [Register-PSResourceRepository], ArgumentException
FullyQualifiedErrorId : InvalidUrl,Microsoft.PowerShell.PowerShellGet.Cmdlets.RegisterPSResourceRepository
InvocationInfo        :
    MyCommand        : Register-PSResourceRepository
    ScriptLineNumber : 1
    OffsetInLine     : 2
    HistoryId        : 62
    Line             :  Register-PSResourceRepository -Name HCGallery -url
\\hcgg.fr.co.hennepin.mn.us\lobroot\ITxx\team\NuGet\
    PositionMessage  : At line:1 char:2
                       +  Register-PSResourceRepository -Name HCGallery -url \\hcgg.rest.of.do …
                       +  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    InvocationName   : Register-PSResourceRepository
    CommandOrigin    : Internal
ScriptStackTrace      : at <ScriptBlock>, <No file>: line 1

Exception             :
    Type       : System.ArgumentException
    Message    : The URL provided is not valid: file:\\hcgg.rest.of.domain.name\lobroot\ITxx\team\NuGet and must be
of Uri Scheme: HTTP, HTTPS, FTP or File
    TargetSite :
        Name          : ThrowTerminatingError
        DeclaringType : System.Management.Automation.MshCommandRuntime, System.Management.Automation,
Version=7.1.4.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35
        MemberType    : Method
        Module        : System.Management.Automation.dll
    StackTrace :
   at System.Management.Automation.MshCommandRuntime.ThrowTerminatingError(ErrorRecord errorRecord)
    Source     : System.Management.Automation
    HResult    : -2147024809
CategoryInfo          : InvalidArgument: (:) [Register-PSResourceRepository], ArgumentException
FullyQualifiedErrorId : InvalidUrl,Microsoft.PowerShell.PowerShellGet.Cmdlets.RegisterPSResourceRepository
InvocationInfo        :
    MyCommand        : Register-PSResourceRepository
    ScriptLineNumber : 1
    OffsetInLine     : 2
    HistoryId        : 67
    Line             :  Register-PSResourceRepository -Name HCGallery -url
file:\\hcgg.fr.co.hennepin.mn.us\lobroot\ITxx\team\NuGet
    PositionMessage  : At line:1 char:2
                       +  Register-PSResourceRepository -Name HCGallery -url file:\\hcgg.rest. …
                       +  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    InvocationName   : Register-PSResourceRepository
    CommandOrigin    : Internal
ScriptStackTrace      : at <ScriptBlock>, <No file>: line
```

### Environment data

```powershell
ModuleType Version    PreRelease Name                                ExportedCommands
---------- -------    ---------- ----                                ----------------
Binary     3.0.11     beta       PowerShellGet                       {Find-PSResource, Get-InstalledPSResource, Get-PS…

Key   : PSVersion
Value : 7.1.4
Name  : PSVersion


Key   : PSEdition
Value : Core
Name  : PSEdition


Key   : GitCommitId
Value : 7.1.4
Name  : GitCommitId


Key   : OS
Value : Microsoft Windows 10.0.19042
Name  : OS


Key   : Platform
Value : Win32NT
Name  : Platform


Key   : PSCompatibleVersions
Value : {1.0, 2.0, 3.0, 4.0…}
Name  : PSCompatibleVersions


Key   : PSRemotingProtocolVersion
Value : 2.3
Name  : PSRemotingProtocolVersion


Key   : SerializationVersion
Value : 1.1.0.1
Name  : SerializationVersion


Key   : WSManStackVersion
Value : 3.0
Name  : WSManStackVersion
```

### Visuals

_No response_

### PR DESCRIPTION
**Pull request by alerickson**
# PR Summary
This PR addresses a bug that occurs when attempting to register certain types of repositories, for example, a local file share based NuGet repository. This PR allows for any repository URL that is of a valid URI scheme to be registered.

## PR Context
Resolves #496 

## PR Checklist

- [x] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [x] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.
- **[Breaking changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)**
    - [x] None
    - **OR**
    - [ ] [Documentation needed]()
        - [ ] Issue filed: 
- **User-facing changes**
    - [x] Not Applicable
    - **OR**
    - [ ] [Documentation needed]()
        - [ ] Issue filed: 
- **Testing - New and feature**
    - [ ] N/A or can only be tested interactively
    - **OR**
    - [x] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
- **Tooling**
    - [x] I have considered the user experience from a tooling perspective and don't believe tooling will be impacted.
    - **OR**
    - [ ] I have considered the user experience from a tooling perspective and enumerated concerns in the summary.

### CODE REVIEW

File: src/code/Utils.cs [hunk 1]
```diff
@@ -236,9 +236,8 @@ public static string[] GetStringArray(ArrayList list)
         {
             errorRecord = null;
 
-            if (!urlString.StartsWith(Uri.UriSchemeHttps) &&
-                !urlString.StartsWith(Uri.UriSchemeHttp) &&
-                !urlString.StartsWith(Uri.UriSchemeFtp))
+            bool tryCreateResult = Uri.TryCreate(urlString, UriKind.Absolute, out urlResult);
```
Comment (PaulHigin) [inline src/code/Utils.cs]: This will return `false` for a valid relative file path case.  There is duplicate code with the error handling.  Also we need to be consistent and use `Uri` instead of `Url`.

I think the code can be simplified by using early outs, something like:

```csharp
errorRecord = null;
if (Uri.TryCreate(urlString, UriKind.Absolute, out urlResult))
{
    return true;
}

// Check to see if the uri is a valid file path, and convert any relative path to full path.
Exception ex;
try
{ 
   var filePath = cmdletPassedIn.SessionState.Path.GetResolvedPSPathFromPSPath(urlString)[0].Path;
   if (Uri.TryCreate(filePath, UriKind.Absolute, out urlResult))
   {
       return true;
   }

   ex = new PSArgumentException($"Invalid Uri file path: {urlString}");
}
catch (Exception exx)
{
    ex = exx;
}

errorRecord = new ErrorRecord(
    new PSArgumentException(
        $"The provided Uri is not valid: {urlString}. It must be of Uri Scheme: HTTP, HTTPS, FTP or a file path",
        ex),
    "InvalidUri",
    ErrorCategory.InvalidArgument,
    cmdletPassedIn);

return false;
```

**Review by PaulHigin — CHANGES_REQUESTED** [review]

File: src/code/Utils.cs (hunk 1 above)
Comment (alerickson) [reply src/code/Utils.cs]: > This will return false for a valid relative file path case.

If it returns false it attempts to resolve the path in line 247.

>  There is duplicate code with the error handling. 

I agree,  I wasn't sure how to clean that section up.

> Also we need to be consistent and use Uri instead of Url.

I believe this is work for another PR since we have an issue open to change URL to URI, however I can start making the changes here. 
edit:  Just realized you're specifically referring to the variable that gets generated after TryCreate()-- that's updated now too.

I'll refactor the code to clean it up in a similar manner

**Review by PaulHigin — APPROVED** [review]
