### PR TITLE
Bug fix for saving dependency modules in version range format

### LINKED ISSUE #1313: `Save-PSResource -Name Az -Path <DestinationPath>` fails to install any modules
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://www.powershellgallery.com/packages/PSResourceGet)
- [X] Search the existing issues.

### Steps to reproduce

`Save-PSResource -Name Az -Path <DestinationPath>` fails to install any modules

### Expected behavior

```console
The Az module and dependent modules are installed
```

### Actual behavior

```console
An exception is thrown and no modules are installed
```

### Error details

```console
PS C:\> Get-Error

Exception             :
    Type           : Microsoft.PowerShell.PSResourceGet.UtilClasses.PackageNotFoundException
    Message        : Dependency package 'Az.Automation' with version range '[1.9.1, 1.9.1]' could not be found in repository 'PSGallery'
    InnerException :
        Type    : Microsoft.PowerShell.PSResourceGet.UtilClasses.V2ResourceNotFoundException
        Message : Package does not exist on the server
        HResult : -2146233088
    HResult        : -2146233088
TargetObject          : Microsoft.PowerShell.PSResourceGet.Cmdlets.FindHelper
CategoryInfo          : ObjectNotFound: (Microsoft.PowerShel….Cmdlets.FindHelper:FindHelper) [Save-PSResource], PackageNotFoundException
FullyQualifiedErrorId : DependencyPackageNotFound,Microsoft.PowerShell.PSResourceGet.Cmdlets.SavePSResource
InvocationInfo        :
    MyCommand        : Save-PSResource
    ScriptLineNumber : 1
    OffsetInLine     : 1
    HistoryId        : 37
    Line             : Save-PSResource -Name Az -Path C:\modules\543857739
    PositionMessage  : At line:1 char:1
                       + Save-PSResource -Name Az -Path C:\modules\543857739
                       + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    InvocationName   : Save-PSResource
    CommandOrigin    : Internal
ScriptStackTrace      : at <ScriptBlock>, <No file>: line 1
PipelineIterationInfo :
```

### Environment data

```powershell
PS C:\> Get-Module -list Microsoft.PowerShell.PSResourceGet ; $PSVersionTable | ft

    Directory: C:\Program Files\PowerShell\Modules

ModuleType Version    PreRelease Name                                PSEdition ExportedCommands
---------- -------    ---------- ----                                --------- ----------------
Binary     0.5.23     beta23     Microsoft.PowerShell.PSResourceGet  Core,Desk {Find-PSResource, Get-InstalledPSResource, Get-PSResourceRepository, Get-PSScriptFileInfo…}


Name                           Value
----                           -----
PSVersion                      7.3.6
PSEdition                      Core
GitCommitId                    7.3.6
OS                             Microsoft Windows 6.2.9200
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Visuals

```powershell
# This is the output of running Save-PSResource. As you can see below, no modules are saved to destination path. 

PS C:\modules> Save-PSResource -Name Az -Path C:\modules\543857739 -Verbose
VERBOSE: Parameters passed in >>> Name: 'Az'; VersionRange: ''; NuGetVersion: ''; VersionType: 'NoVersion'; Version: ''; Prerelease: 'False'; Repository: ''; AcceptLicense: 'True'; Quiet: 'False'; Reinstall: 'True'; TrustRepository: 'False'; NoClobber: 'False'; AsNupkg: 'False'; IncludeXml 'False'; SavePackage 'True'; TemporaryPath ''
VERBOSE: Attempting to search for packages in 'PSGallery'
VERBOSE: Performing the operation "Save-PSResource" on target "Package to save: 'Az', version: '10.1.0'".
VERBOSE: Performing the operation "Save-PSResource" on target "Package to install: 'Az', version: '10.1.0'".
VERBOSE: Deleting 'C:\Users\frangom\AppData\Local\Temp\cf9db787-8f49-464b-b9dc-4208c5506f6f\az\10.1.0\Az.nuspec'
VERBOSE: Deleting 'C:\Users\frangom\AppData\Local\Temp\cf9db787-8f49-464b-b9dc-4208c5506f6f\az\10.1.0\[Content_Types].xml'
VERBOSE: Deleting 'C:\Users\frangom\AppData\Local\Temp\cf9db787-8f49-464b-b9dc-4208c5506f6f\az\10.1.0\_rels'
VERBOSE: Deleting 'C:\Users\frangom\AppData\Local\Temp\cf9db787-8f49-464b-b9dc-4208c5506f6f\az\10.1.0\package'
VERBOSE: Performing the operation "Save-PSResource" on target "Package to save: 'Az.Accounts', version: '2.12.4'".
VERBOSE: Performing the operation "Save-PSResource" on target "Package to install: 'Az.Accounts', version: '2.12.4'".
VERBOSE: Deleting 'C:\Users\frangom\AppData\Local\Temp\cf9db787-8f49-464b-b9dc-4208c5506f6f\az.accounts\2.12.4\Az.Accounts.nuspec'
VERBOSE: Deleting 'C:\Users\frangom\AppData\Local\Temp\cf9db787-8f49-464b-b9dc-4208c5506f6f\az.accounts\2.12.4\[Content_Types].xml'
VERBOSE: Deleting 'C:\Users\frangom\AppData\Local\Temp\cf9db787-8f49-464b-b9dc-4208c5506f6f\az.accounts\2.12.4\_rels'
VERBOSE: Deleting 'C:\Users\frangom\AppData\Local\Temp\cf9db787-8f49-464b-b9dc-4208c5506f6f\az.accounts\2.12.4\package'
VERBOSE: Performing the operation "Save-PSResource" on target "Package to save: 'Az.Advisor', version: '2.0.0'".
VERBOSE: Performing the operation "Save-PSResource" on target "Package to install: 'Az.Advisor', version: '2.0.0'".
VERBOSE: Deleting 'C:\Users\frangom\AppData\Local\Temp\cf9db787-8f49-464b-b9dc-4208c5506f6f\az.advisor\2.0.0\Az.Advisor.nuspec'
VERBOSE: Deleting 'C:\Users\frangom\AppData\Local\Temp\cf9db787-8f49-464b-b9dc-4208c5506f6f\az.advisor\2.0.0\[Content_Types].xml'
VERBOSE: Deleting 'C:\Users\frangom\AppData\Local\Temp\cf9db787-8f49-464b-b9dc-4208c5506f6f\az.advisor\2.0.0\_rels'
VERBOSE: Deleting 'C:\Users\frangom\AppData\Local\Temp\cf9db787-8f49-464b-b9dc-4208c5506f6f\az.advisor\2.0.0\package'
VERBOSE: Performing the operation "Save-PSResource" on target "Package to save: 'Az.Aks', version: '5.5.1'".
VERBOSE: Performing the operation "Save-PSResource" on target "Package to install: 'Az.Aks', version: '5.5.1'".
VERBOSE: Deleting 'C:\Users\frangom\AppData\Local\Temp\cf9db787-8f49-464b-b9dc-4208c5506f6f\az.aks\5.5.1\Az.Aks.nuspec'
VERBOSE: Deleting 'C:\Users\frangom\AppData\Local\Temp\cf9db787-8f49-464b-b9dc-4208c5506f6f\az.aks\5.5.1\[Content_Types].xml'
VERBOSE: Deleting 'C:\Users\frangom\AppData\Local\Temp\cf9db787-8f49-464b-b9dc-4208c5506f6f\az.aks\5.5.1\_rels'
VERBOSE: Deleting 'C:\Users\frangom\AppData\Local\Temp\cf9db787-8f49-464b-b9dc-4208c5506f6f\az.aks\5.5.1\package'
VERBOSE: Performing the operation "Save-PSResource" on target "Package to save: 'Az.AnalysisServices', version: '1.1.4'".
VERBOSE: Performing the operation "Save-PSResource" on target "Package to install: 'Az.AnalysisServices', version: '1.1.4'".
VERBOSE: Deleting 'C:\Users\frangom\AppData\Local\Temp\cf9db787-8f49-464b-b9dc-4208c5506f6f\az.analysisservices\1.1.4\Az.AnalysisServices.nuspec'
VERBOSE: Deleting 'C:\Users\frangom\AppData\Local\Temp\cf9db787-8f49-464b-b9dc-4208c5506f6f\az.analysisservices\1.1.4\[Content_Types].xml'
VERBOSE: Deleting 'C:\Users\frangom\AppData\Local\Temp\cf9db787-8f49-464b-b9dc-4208c5506f6f\az.analysisservices\1.1.4\_rels'
VERBOSE: Deleting 'C:\Users\frangom\AppData\Local\Temp\cf9db787-8f49-464b-b9dc-4208c5506f6f\az.analysisservices\1.1.4\package'
VERBOSE: Performing the operation "Save-PSResource" on target "Package to save: 'Az.ApiManagement', version: '4.0.2'".
VERBOSE: Performing the operation "Save-PSResource" on target "Package to install: 'Az.ApiManagement', version: '4.0.2'".
VERBOSE: Deleting 'C:\Users\frangom\AppData\Local\Temp\cf9db787-8f49-464b-b9dc-4208c5506f6f\az.apimanagement\4.0.2\Az.ApiManagement.nuspec'
VERBOSE: Deleting 'C:\Users\frangom\AppData\Local\Temp\cf9db787-8f49-464b-b9dc-4208c5506f6f\az.apimanagement\4.0.2\[Content_Types].xml'
VERBOSE: Deleting 'C:\Users\frangom\AppData\Local\Temp\cf9db787-8f49-464b-b9dc-4208c5506f6f\az.apimanagement\4.0.2\_rels'
VERBOSE: Deleting 'C:\Users\frangom\AppData\Local\Temp\cf9db787-8f49-464b-b9dc-4208c5506f6f\az.apimanagement\4.0.2\package'
VERBOSE: Performing the operation "Save-PSResource" on target "Package to save: 'Az.AppConfiguration', version: '1.2.0'".
VERBOSE: Performing the operation "Save-PSResource" on target "Package to install: 'Az.AppConfiguration', version: '1.2.0'".
VERBOSE: Deleting 'C:\Users\frangom\AppData\Local\Temp\cf9db787-8f49-464b-b9dc-4208c5506f6f\az.appconfiguration\1.2.0\Az.AppConfiguration.nuspec'
VERBOSE: Deleting 'C:\Users\frangom\AppData\Local\Temp\cf9db787-8f49-464b-b9dc-4208c5506f6f\az.appconfiguration\1.2.0\[Content_Types].xml'
VERBOSE: Deleting 'C:\Users\frangom\AppData\Local\Temp\cf9db787-8f49-464b-b9dc-4208c5506f6f\az.appconfiguration\1.2.0\_rels'
VERBOSE: Deleting 'C:\Users\frangom\AppData\Local\Temp\cf9db787-8f49-464b-b9dc-4208c5506f6f\az.appconfiguration\1.2.0\package'
VERBOSE: Performing the operation "Save-PSResource" on target "Package to save: 'Az.ApplicationInsights', version: '2.2.2'".
VERBOSE: Performing the operation "Save-PSResource" on target "Package to install: 'Az.ApplicationInsights', version: '2.2.2'".
VERBOSE: Deleting 'C:\Users\frangom\AppData\Local\Temp\cf9db787-8f49-464b-b9dc-4208c5506f6f\az.applicationinsights\2.2.2\Az.ApplicationInsights.nuspec'
VERBOSE: Deleting 'C:\Users\frangom\AppData\Local\Temp\cf9db787-8f49-464b-b9dc-4208c5506f6f\az.applicationinsights\2.2.2\[Content_Types].xml'
VERBOSE: Deleting 'C:\Users\frangom\AppData\Local\Temp\cf9db787-8f49-464b-b9dc-4208c5506f6f\az.applicationinsights\2.2.2\_rels'
VERBOSE: Deleting 'C:\Users\frangom\AppData\Local\Temp\cf9db787-8f49-464b-b9dc-4208c5506f6f\az.applicationinsights\2.2.2\package'
VERBOSE: Performing the operation "Save-PSResource" on target "Package to save: 'Az.Attestation', version: '2.0.0'".
VERBOSE: Performing the operation "Save-PSResource" on target "Package to install: 'Az.Attestation', version: '2.0.0'".
VERBOSE: Deleting 'C:\Users\frangom\AppData\Local\Temp\cf9db787-8f49-464b-b9dc-4208c5506f6f\az.attestation\2.0.0\Az.Attestation.nuspec'
VERBOSE: Deleting 'C:\Users\frangom\AppData\Local\Temp\cf9db787-8f49-464b-b9dc-4208c5506f6f\az.attestation\2.0.0\[Content_Types].xml'
VERBOSE: Deleting 'C:\Users\frangom\AppData\Local\Temp\cf9db787-8f49-464b-b9dc-4208c5506f6f\az.attestation\2.0.0\_rels'
VERBOSE: Deleting 'C:\Users\frangom\AppData\Local\Temp\cf9db787-8f49-464b-b9dc-4208c5506f6f\az.attestation\2.0.0\package'
VERBOSE: Performing the operation "Save-PSResource" on target "Package to save: 'Az.Automanage', version: '1.0.0'".
VERBOSE: Performing the operation "Save-PSResource" on target "Package to install: 'Az.Automanage', version: '1.0.0'".
VERBOSE: Deleting 'C:\Users\frangom\AppData\Local\Temp\cf9db787-8f49-464b-b9dc-4208c5506f6f\az.automanage\1.0.0\Az.Automanage.nuspec'
VERBOSE: Deleting 'C:\Users\frangom\AppData\Local\Temp\cf9db787-8f49-464b-b9dc-4208c5506f6f\az.automanage\1.0.0\[Content_Types].xml'
VERBOSE: Deleting 'C:\Users\frangom\AppData\Local\Temp\cf9db787-8f49-464b-b9dc-4208c5506f6f\az.automanage\1.0.0\_rels'
VERBOSE: Deleting 'C:\Users\frangom\AppData\Local\Temp\cf9db787-8f49-464b-b9dc-4208c5506f6f\az.automanage\1.0.0\package'
Save-PSResource: Dependency package 'Az.Automation' with version range '[1.9.1, 1.9.1]' could not be found in repository 'PSGallery'
VERBOSE: Performing the operation "Save-PSResource" on target "Package to save: 'Az.Batch', version: '3.4.0'".
VERBOSE: Performing the operation "Save-PSResource" on target "Package to install: 'Az.Batch', version: '3.4.0'".
VERBOSE: Deleting 'C:\Users\frangom\AppData\Local\Temp\cf9db787-8f49-464b-b9dc-4208c5506f6f\az.batch\3.4.0\Az.Batch.nuspec'
VERBOSE: Deleting 'C:\Users\frangom\AppData\Local\Temp\cf9db787-8f49-464b-b9dc-4208c5506f6f\az.batch\3.4.0\[Content_Types].xml'
VERBOSE: Deleting 'C:\Users\frangom\AppData\Local\Temp\cf9db787-8f49-464b-b9dc-4208c5506f6f\az.batch\3.4.0\_rels'
VERBOSE: Deleting 'C:\Users\frangom\AppData\Local\Temp\cf9db787-8f49-464b-b9dc-4208c5506f6f\az.batch\3.4.0\package'
VERBOSE: Performing the operation "Save-PSResource" on target "Package to save: 'Az.Billing', version: '2.0.3'".
VERBOSE: Performing the operation "Save-PSResource" on target "Package to install: 'Az.Billing', version: '2.0.3'".
VERBOSE: Deleting 'C:\Users\frangom\AppData\Local\Temp\cf9db787-8f49-464b-b9dc-4208c5506f6f\az.billing\2.0.3\Az.Billing.nuspec'
VERBOSE: Deleting 'C:\Users\frangom\AppData\Local\Temp\cf9db787-8f49-464b-b9dc-4208c5506f6f\az.billing\2.0.3\[Content_Types].xml'
VERBOSE: Deleting 'C:\Users\frangom\AppData\Local\Temp\cf9db787-8f49-464b-b9dc-4208c5506f6f\az.billing\2.0.3\_rels'
VERBOSE: Deleting 'C:\Users\frangom\AppData\Local\Temp\cf9db787-8f49-464b-b9dc-4208c5506f6f\az.billing\2.0.3\package'
VERBOSE: Performing the operation "Save-PSResource" on target "Package to save: 'Az.Cdn', version: '3.1.0'".
VERBOSE: Performing the operation "Save-PSResource" on target "Package to install: 'Az.Cdn', version: '3.1.0'".
VERBOSE: Deleting 'C:\Users\frangom\AppData\Local\Temp\cf9db787-8f49-464b-b9dc-4208c5506f6f\az.cdn\3.1.0\Az.Cdn.nuspec'
VERBOSE: Deleting 'C:\Users\frangom\AppData\Local\Temp\cf9db787-8f49-464b-b9dc-4208c5506f6f\az.cdn\3.1.0\[Content_Types].xml'
VERBOSE: Deleting 'C:\Users\frangom\AppData\Local\Temp\cf9db787-8f49-464b-b9dc-4208c5506f6f\az.cdn\3.1.0\_rels'
VERBOSE: Deleting 'C:\Users\frangom\AppData\Local\Temp\cf9db787-8f49-464b-b9dc-4208c5506f6f\az.cdn\3.1.0\package'
VERBOSE: Performing the operation "Save-PSResource" on target "Package to save: 'Az.CloudService', version: '1.2.0'".
VERBOSE: Performing the operation "Save-PSResource" on target "Package to install: 'Az.CloudService', version: '1.2.0'".
VERBOSE: Deleting 'C:\Users\frangom\AppData\Local\Temp\cf9db787-8f49-464b-b9dc-4208c5506f6f\az.cloudservice\1.2.0\Az.CloudService.nuspec'
VERBOSE: Deleting 'C:\Users\frangom\AppData\Local\Temp\cf9db787-8f49-464b-b9dc-4208c5506f6f\az.cloudservice\1.2.0\[Content_Types].xml'
VERBOSE: Deleting 'C:\Users\frangom\AppData\Local\Temp\cf9db787-8f49-464b-b9dc-4208c5506f6f\az.cloudservice\1.2.0\_rels'
VERBOSE: Deleting 'C:\Users\frangom\AppData\Local\Temp\cf9db787-8f49-464b-b9dc-4208c5506f6f\az.cloudservice\1.2.0\package'
VERBOSE: Performing the operation "Save-PSResource" on target "Package to save: 'Az.CognitiveServices', version: '1.14.0'".
VERBOSE: Performing the operation "Save-PSResource" on target "Package to install: 'Az.CognitiveServices', version: '1.14.0'".
VERBOSE: Deleting 'C:\Users\frangom\AppData\Local\Temp\cf9db787-8f49-464b-b9dc-4208c5506f6f\az.cognitiveservices\1.14.0\Az.CognitiveServices.nuspec'
VERBOSE: Deleting 'C:\Users\frangom\AppData\Local\Temp\cf9db787-8f49-464b-b9dc-4208c5506f6f\az.cognitiveservices\1.14.0\[Content_Types].xml'
VERBOSE: Deleting 'C:\Users\frangom\AppData\Local\Temp\cf9db787-8f49-464b-b9dc-4208c5506f6f\az.cognitiveservices\1.14.0\_rels'
VERBOSE: Deleting 'C:\Users\frangom\AppData\Local\Temp\cf9db787-8f49-464b-b9dc-4208c5506f6f\az.cognitiveservices\1.14.0\package'
VERBOSE: Performing the operation "Save-PSResource" on target "Package to save: 'Az.Compute', version: '6.1.0'".
VERBOSE: Performing the operation "Save-PSResource" on target "Package to install: 'Az.Compute', version: '6.1.0'".
VERBOSE: Deleting 'C:\Users\frangom\AppData\Local\Temp\cf9db787-8f49-464b-b9dc-4208c5506f6f\az.compute\6.1.0\Az.Compute.nuspec'
VERBOSE: Deleting 'C:\Users\frangom\AppData\Local\Temp\cf9db787-8f49-464b-b9dc-4208c5506f6f\az.compute\6.1.0\[Content_Types].xml'
VERBOSE: Deleting 'C:\Users\frangom\AppData\Local\Temp\cf9db787-8f49-464b-b9dc-4208c5506f6f\az.compute\6.1.0\_rels'
VERBOSE: Deleting 'C:\Users\frangom\AppData\Local\Temp\cf9db787-8f49-464b-b9dc-4208c5506f6f\az.compute\6.1.0\package'
VERBOSE: Performing the operation "Save-PSResource" on target "Package to save: 'Az.ConfidentialLedger', version: '1.0.0'".
VERBOSE: Performing the operation "Save-PSResource" on target "Package to install: 'Az.ConfidentialLedger', version: '1.0.0'".
VERBOSE: Deleting 'C:\Users\frangom\AppData\Local\Temp\cf9db787-8f49-464b-b9dc-4208c5506f6f\az.confidentialledger\1.0.0\Az.ConfidentialLedger.nuspec'
VERBOSE: Deleting 'C:\Users\frangom\AppData\Local\Temp\cf9db787-8f49-464b-b9dc-4208c5506f6f\az.confidentialledger\1.0.0\[Content_Types].xml'
VERBOSE: Deleting 'C:\Users\frangom\AppData\Local\Temp\cf9db787-8f49-464b-b9dc-4208c5506f6f\az.confidentialledger\1.0.0\_rels'
VERBOSE: Deleting 'C:\Users\frangom\AppData\Local\Temp\cf9db787-8f49-464b-b9dc-4208c5506f6f\az.confidentialledger\1.0.0\package'
VERBOSE: Performing the operation "Save-PSResource" on target "Package to save: 'Az.ContainerInstance', version: '3.2.0'".
VERBOSE: Performing the operation "Save-PSResource" on target "Package to install: 'Az.ContainerInstance', version: '3.2.0'".
VERBOSE: Deleting 'C:\Users\frangom\AppData\Local\Temp\cf9db787-8f49-464b-b9dc-4208c5506f6f\az.containerinstance\3.2.0\Az.ContainerInstance.nuspec'
VERBOSE: Deleting 'C:\Users\frangom\AppData\Local\Temp\cf9db787-8f49-464b-b9dc-4208c5506f6f\az.containerinstance\3.2.0\[Content_Types].xml'
VERBOSE: Deleting 'C:\Users\frangom\AppData\Local\Temp\cf9db787-8f49-464b-b9dc-4208c5506f6f\az.containerinstance\3.2.0\_rels'
VERBOSE: Deleting 'C:\Users\frangom\AppData\Local\Temp\cf9db787-8f49-464b-b9dc-4208c5506f6f\az.containerinstance\3.2.0\package'
VERBOSE: Performing the operation "Save-PSResource" on target "Package to save: 'Az.ContainerRegistry', version: '4.0.0'".
VERBOSE: Performing the operation "Save-PSResource" on target "Package to install: 'Az.ContainerRegistry', version: '4.0.0'".
VERBOSE: Deleting 'C:\Users\frangom\AppData\Local\Temp\cf9db787-8f49-464b-b9dc-4208c5506f6f\az.containerregistry\4.0.0\Az.ContainerRegistry.nuspec'
VERBOSE: Deleting 'C:\Users\frangom\AppData\Local\Temp\cf9db787-8f49-464b-b9dc-4208c5506f6f\az.containerregistry\4.0.0\[Content_Types].xml'
VERBOSE: Deleting 'C:\Users\frangom\AppData\Local\Temp\cf9db787-8f49-464b-b9dc-4208c5506f6f\az.containerregistry\4.0.0\_rels'
VERBOSE: Deleting 'C:\Users\frangom\AppData\Local\Temp\cf9db787-8f49-464b-b9dc-4208c5506f6f\az.containerregistry\4.0.0\package'
VERBOSE: Performing the operation "Save-PSResource" on target "Package to save: 'Az.CosmosDB', version: '1.11.1'".
VERBOSE: Performing the operation "Save-PSResource" on target "Package to install: 'Az.CosmosDB', version: '1.11.1'".
VERBOSE: Deleting 'C:\Users\frangom\AppData\Local\Temp\cf9db787-8f49-464b-b9dc-4208c5506f6f\az.cosmosdb\1.11.1\Az.CosmosDB.nuspec'
VERBOSE: Deleting 'C:\Users\frangom\AppData\Local\Temp\cf9db787-8f49-464b-b9dc-4208c5506f6f\az.cosmosdb\1.11.1\[Content_Types].xml'
VERBOSE: Deleting 'C:\Users\frangom\AppData\Local\Temp\cf9db787-8f49-464b-b9dc-4208c5506f6f\az.cosmosdb\1.11.1\_rels'
VERBOSE: Deleting 'C:\Users\frangom\AppData\Local\Temp\cf9db787-8f49-464b-b9dc-4208c5506f6f\az.cosmosdb\1.11.1\package'
VERBOSE: Performing the operation "Save-PSResource" on target "Package to save: 'Az.DataBoxEdge', version: '1.1.0'".
VERBOSE: Performing the operation "Save-PSResource" on target "Package to install: 'Az.DataBoxEdge', version: '1.1.0'".
VERBOSE: Deleting 'C:\Users\frangom\AppData\Local\Temp\cf9db787-8f49-464b-b9dc-4208c5506f6f\az.databoxedge\1.1.0\Az.DataBoxEdge.nuspec'
VERBOSE: Deleting 'C:\Users\frangom\AppData\Local\Temp\cf9db787-8f49-464b-b9dc-4208c5506f6f\az.databoxedge\1.1.0\[Content_Types].xml'
VERBOSE: Deleting 'C:\Users\frangom\AppData\Local\Temp\cf9db787-8f49-464b-b9dc-4208c5506f6f\az.databoxedge\1.1.0\_rels'
VERBOSE: Deleting 'C:\Users\frangom\AppData\Local\Temp\cf9db787-8f49-464b-b9dc-4208c5506f6f\az.databoxedge\1.1.0\package'
VERBOSE: Performing the operation "Save-PSResource" on target "Package to save: 'Az.Databricks', version: '1.6.0'".
VERBOSE: Performing the operation "Save-PSResource" on target "Package to install: 'Az.Databricks', version: '1.6.0'".
VERBOSE: Deleting 'C:\Users\frangom\AppData\Local\Temp\cf9db787-8f49-464b-b9dc-4208c5506f6f\az.databricks\1.6.0\Az.Databricks.nuspec'
VERBOSE: Deleting 'C:\Users\frangom\AppData\Local\Temp\cf9db787-8f49-464b-b9dc-4208c5506f6f\az.databricks\1.6.0\[Content_Types].xml'
VERBOSE: Deleting 'C:\Users\frangom\AppData\Local\Temp\cf9db787-8f49-464b-b9dc-4208c5506f6f\az.databricks\1.6.0\_rels'
VERBOSE: Deleting 'C:\Users\frangom\AppData\Local\Temp\cf9db787-8f49-464b-b9dc-4208c5506f6f\az.databricks\1.6.0\package'
VERBOSE: Performing the operation "Save-PSResource" on target "Package to save: 'Az.DataFactory', version: '1.16.13'".
VERBOSE: Performing the operation "Save-PSResource" on target "Package to install: 'Az.DataFactory', version: '1.16.13'".
VERBOSE: Deleting 'C:\Users\frangom\AppData\Local\Temp\cf9db787-8f49-464b-b9dc-4208c5506f6f\az.datafactory\1.16.13\Az.DataFactory.nuspec'
VERBOSE: Deleting 'C:\Users\frangom\AppData\Local\Temp\cf9db787-8f49-464b-b9dc-4208c5506f6f\az.datafactory\1.16.13\[Content_Types].xml'
VERBOSE: Deleting 'C:\Users\frangom\AppData\Local\Temp\cf9db787-8f49-464b-b9dc-4208c5506f6f\az.datafactory\1.16.13\_rels'
VERBOSE: Deleting 'C:\Users\frangom\AppData\Local\Temp\cf9db787-8f49-464b-b9dc-4208c5506f6f\az.datafactory\1.16.13\package'
VERBOSE: Performing the operation "Save-PSResource" on target "Package to save: 'Az.DataLakeAnalytics', version: '1.0.2'".
VERBOSE: Performing the operation "Save-PSResource" on target "Package to install: 'Az.DataLakeAnalytics', version: '1.0.2'".
VERBOSE: Deleting 'C:\Users\frangom\AppData\Local\Temp\cf9db787-8f49-464b-b9dc-4208c5506f6f\az.datalakeanalytics\1.0.2\Az.DataLakeAnalytics.nuspec'
VERBOSE: Deleting 'C:\Users\frangom\AppData\Local\Temp\cf9db787-8f49-464b-b9dc-4208c5506f6f\az.datalakeanalytics\1.0.2\[Content_Types].xml'
VERBOSE: Deleting 'C:\Users\frangom\AppData\Local\Temp\cf9db787-8f49-464b-b9dc-4208c5506f6f\az.datalakeanalytics\1.0.2\_rels'
VERBOSE: Deleting 'C:\Users\frangom\AppData\Local\Temp\cf9db787-8f49-464b-b9dc-4208c5506f6f\az.datalakeanalytics\1.0.2\package'
VERBOSE: Performing the operation "Save-PSResource" on target "Package to save: 'Az.DataLakeStore', version: '1.3.0'".
VERBOSE: Performing the operation "Save-PSResource" on target "Package to install: 'Az.DataLakeStore', version: '1.3.0'".
VERBOSE: Deleting 'C:\Users\frangom\AppData\Local\Temp\cf9db787-8f49-464b-b9dc-4208c5506f6f\az.datalakestore\1.3.0\Az.DataLakeStore.nuspec'
VERBOSE: Deleting 'C:\Users\frangom\AppData\Local\Temp\cf9db787-8f49-464b-b9dc-4208c5506f6f\az.datalakestore\1.3.0\[Content_Types].xml'
VERBOSE: Deleting 'C:\Users\frangom\AppData\Local\Temp\cf9db787-8f49-464b-b9dc-4208c5506f6f\az.datalakestore\1.3.0\_rels'
VERBOSE: Deleting 'C:\Users\frangom\AppData\Local\Temp\cf9db787-8f49-464b-b9dc-4208c5506f6f\az.datalakestore\1.3.0\package'
VERBOSE: Performing the operation "Save-PSResource" on target "Package to save: 'Az.DataProtection', version: '2.0.0'".
VERBOSE: Performing the operation "Save-PSResource" on target "Package to install: 'Az.DataProtection', version: '2.0.0'".
VERBOSE: Deleting 'C:\Users\frangom\AppData\Local\Temp\cf9db787-8f49-464b-b9dc-4208c5506f6f\az.dataprotection\2.0.0\Az.DataProtection.nuspec'
VERBOSE: Deleting 'C:\Users\frangom\AppData\Local\Temp\cf9db787-8f49-464b-b9dc-4208c5506f6f\az.dataprotection\2.0.0\[Content_Types].xml'
VERBOSE: Deleting 'C:\Users\frangom\AppData\Local\Temp\cf9db787-8f49-464b-b9dc-4208c5506f6f\az.dataprotection\2.0.0\_rels'
VERBOSE: Deleting 'C:\Users\frangom\AppData\Local\Temp\cf9db787-8f49-464b-b9dc-4208c5506f6f\az.dataprotection\2.0.0\package'
VERBOSE: Performing the operation "Save-PSResource" on target "Package to save: 'Az.DataShare', version: '1.0.1'".
VERBOSE: Performing the operation "Save-PSResource" on target "Package to install: 'Az.DataShare', version: '1.0.1'".
VERBOSE: Deleting 'C:\Users\frangom\AppData\Local\Temp\cf9db787-8f49-464b-b9dc-4208c5506f6f\az.datashare\1.0.1\Az.DataShare.nuspec'
VERBOSE: Deleting 'C:\Users\frangom\AppData\Local\Temp\cf9db787-8f49-464b-b9dc-4208c5506f6f\az.datashare\1.0.1\[Content_Types].xml'
VERBOSE: Deleting 'C:\Users\frangom\AppData\Local\Temp\cf9db787-8f49-464b-b9dc-4208c5506f6f\az.datashare\1.0.1\_rels'
VERBOSE: Deleting 'C:\Users\frangom\AppData\Local\Temp\cf9db787-8f49-464b-b9dc-4208c5506f6f\az.datashare\1.0.1\package'
VERBOSE: Performing the operation "Save-PSResource" on target "Package to save: 'Az.DesktopVirtualization', version: '4.0.0'".
VERBOSE: Performing the operation "Save-PSResource" on target "Package to install: 'Az.DesktopVirtualization', version: '4.0.0'".
VERBOSE: Deleting 'C:\Users\frangom\AppData\Local\Temp\cf9db787-8f49-464b-b9dc-4208c5506f6f\az.desktopvirtualization\4.0.0\Az.DesktopVirtualization.nuspec'
VERBOSE: Deleting 'C:\Users\frangom\AppData\Local\Temp\cf9db787-8f49-464b-b9dc-4208c5506f6f\az.desktopvirtualization\4.0.0\[Content_Types].xml'
VERBOSE: Deleting 'C:\Users\frangom\AppData\Local\Temp\cf9db787-8f49-464b-b9dc-4208c5506f6f\az.desktopvirtualization\4.0.0\_rels'
VERBOSE: Deleting 'C:\Users\frangom\AppData\Local\Temp\cf9db787-8f49-464b-b9dc-4208c5506f6f\az.desktopvirtualization\4.0.0\package'
VERBOSE: Performing the operation "Save-PSResource" on target "Package to save: 'Az.DeploymentManager', version: '1.1.0'".
VERBOSE: Performing the operation "Save-PSResource" on target "Package to install: 'Az.DeploymentManager', version: '1.1.0'".
VERBOSE: Deleting 'C:\Users\frangom\AppData\Local\Temp\cf9db787-8f49-464b-b9dc-4208c5506f6f\az.deploymentmanager\1.1.0\Az.DeploymentManager.nuspec'
VERBOSE: Deleting 'C:\Users\frangom\AppData\Local\Temp\cf9db787-8f49-464b-b9dc-4208c5506f6f\az.deploymentmanager\1.1.0\[Content_Types].xml'
VERBOSE: Deleting 'C:\Users\frangom\AppData\Local\Temp\cf9db787-8f49-464b-b9dc-4208c5506f6f\az.deploymentmanager\1.1.0\_rels'
VERBOSE: Deleting 'C:\Users\frangom\AppData\Local\Temp\cf9db787-8f49-464b-b9dc-4208c5506f6f\az.deploymentmanager\1.1.0\package'
VERBOSE: Performing the operation "Save-PSResource" on target "Package to save: 'Az.DevTestLabs', version: '1.0.2'".
VERBOSE: Performing the operation "Save-PSResource" on target "Package to install: 'Az.DevTestLabs', version: '1.0.2'".
VERBOSE: Deleting 'C:\Users\frangom\AppData\Local\Temp\cf9db787-8f49-464b-b9dc-4208c5506f6f\az.devtestlabs\1.0.2\Az.DevTestLabs.nuspec'
VERBOSE: Deleting 'C:\Users\frangom\AppData\Local\Temp\cf9db787-8f49-464b-b9dc-4208c5506f6f\az.devtestlabs\1.0.2\[Content_Types].xml'
VERBOSE: Deleting 'C:\Users\frangom\AppData\Local\Temp\cf9db787-8f49-464b-b9dc-4208c5506f6f\az.devtestlabs\1.0.2\_rels'
VERBOSE: Deleting 'C:\Users\frangom\AppData\Local\Temp\cf9db787-8f49-464b-b9dc-4208c5506f6f\az.devtestlabs\1.0.2\package'
VERBOSE: Performing the operation "Save-PSResource" on target "Package to save: 'Az.Dns', version: '1.1.2'".
VERBOSE: Performing the operation "Save-PSResource" on target "Package to install: 'Az.Dns', version: '1.1.2'".
VERBOSE: Deleting 'C:\Users\frangom\AppData\Local\Temp\cf9db787-8f49-464b-b9dc-4208c5506f6f\az.dns\1.1.2\Az.Dns.nuspec'
VERBOSE: Deleting 'C:\Users\frangom\AppData\Local\Temp\cf9db787-8f49-464b-b9dc-4208c5506f6f\az.dns\1.1.2\[Content_Types].xml'
VERBOSE: Deleting 'C:\Users\frangom\AppData\Local\Temp\cf9db787-8f49-464b-b9dc-4208c5506f6f\az.dns\1.1.2\_rels'
VERBOSE: Deleting 'C:\Users\frangom\AppData\Local\Temp\cf9db787-8f49-464b-b9dc-4208c5506f6f\az.dns\1.1.2\package'
VERBOSE: Performing the operation "Save-PSResource" on target "Package to save: 'Az.EventGrid', version: '1.6.0'".
VERBOSE: Performing the operation "Save-PSResource" on target "Package to install: 'Az.EventGrid', version: '1.6.0'".
VERBOSE: Deleting 'C:\Users\frangom\AppData\Local\Temp\cf9db787-8f49-464b-b9dc-4208c5506f6f\az.eventgrid\1.6.0\Az.EventGrid.nuspec'
VERBOSE: Deleting 'C:\Users\frangom\AppData\Local\Temp\cf9db787-8f49-464b-b9dc-4208c5506f6f\az.eventgrid\1.6.0\[Content_Types].xml'
VERBOSE: Deleting 'C:\Users\frangom\AppData\Local\Temp\cf9db787-8f49-464b-b9dc-4208c5506f6f\az.eventgrid\1.6.0\_rels'
VERBOSE: Deleting 'C:\Users\frangom\AppData\Local\Temp\cf9db787-8f49-464b-b9dc-4208c5506f6f\az.eventgrid\1.6.0\package'
VERBOSE: Performing the operation "Save-PSResource" on target "Package to save: 'Az.EventHub', version: '4.0.0'".
VERBOSE: Performing the operation "Save-PSResource" on target "Package to install: 'Az.EventHub', version: '4.0.0'".
VERBOSE: Deleting 'C:\Users\frangom\AppData\Local\Temp\cf9db787-8f49-464b-b9dc-4208c5506f6f\az.eventhub\4.0.0\Az.EventHub.nuspec'
VERBOSE: Deleting 'C:\Users\frangom\AppData\Local\Temp\cf9db787-8f49-464b-b9dc-4208c5506f6f\az.eventhub\4.0.0\[Content_Types].xml'
VERBOSE: Deleting 'C:\Users\frangom\AppData\Local\Temp\cf9db787-8f49-464b-b9dc-4208c5506f6f\az.eventhub\4.0.0\_rels'
VERBOSE: Deleting 'C:\Users\frangom\AppData\Local\Temp\cf9db787-8f49-464b-b9dc-4208c5506f6f\az.eventhub\4.0.0\package'
VERBOSE: Performing the operation "Save-PSResource" on target "Package to save: 'Az.FrontDoor', version: '1.10.0'".
VERBOSE: Performing the operation "Save-PSResource" on target "Package to install: 'Az.FrontDoor', version: '1.10.0'".
VERBOSE: Deleting 'C:\Users\frangom\AppData\Local\Temp\cf9db787-8f49-464b-b9dc-4208c5506f6f\az.frontdoor\1.10.0\Az.FrontDoor.nuspec'
VERBOSE: Deleting 'C:\Users\frangom\AppData\Local\Temp\cf9db787-8f49-464b-b9dc-4208c5506f6f\az.frontdoor\1.10.0\[Content_Types].xml'
VERBOSE: Deleting 'C:\Users\frangom\AppData\Local\Temp\cf9db787-8f49-464b-b9dc-4208c5506f6f\az.frontdoor\1.10.0\_rels'
VERBOSE: Deleting 'C:\Users\frangom\AppData\Local\Temp\cf9db787-8f49-464b-b9dc-4208c5506f6f\az.frontdoor\1.10.0\package'
VERBOSE: Performing the operation "Save-PSResource" on target "Package to save: 'Az.Functions', version: '4.0.6'".
VERBOSE: Performing the operation "Save-PSResource" on target "Package to install: 'Az.Functions', version: '4.0.6'".
VERBOSE: Deleting 'C:\Users\frangom\AppData\Local\Temp\cf9db787-8f49-464b-b9dc-4208c5506f6f\az.functions\4.0.6\Az.Functions.nuspec'
VERBOSE: Deleting 'C:\Users\frangom\AppData\Local\Temp\cf9db787-8f49-464b-b9dc-4208c5506f6f\az.functions\4.0.6\[Content_Types].xml'
VERBOSE: Deleting 'C:\Users\frangom\AppData\Local\Temp\cf9db787-8f49-464b-b9dc-4208c5506f6f\az.functions\4.0.6\_rels'
VERBOSE: Deleting 'C:\Users\frangom\AppData\Local\Temp\cf9db787-8f49-464b-b9dc-4208c5506f6f\az.functions\4.0.6\package'
VERBOSE: Performing the operation "Save-PSResource" on target "Package to save: 'Az.HDInsight', version: '6.0.0'".
VERBOSE: Performing the operation "Save-PSResource" on target "Package to install: 'Az.HDInsight', version: '6.0.0'".
VERBOSE: Deleting 'C:\Users\frangom\AppData\Local\Temp\cf9db787-8f49-464b-b9dc-4208c5506f6f\az.hdinsight\6.0.0\Az.HDInsight.nuspec'
VERBOSE: Deleting 'C:\Users\frangom\AppData\Local\Temp\cf9db787-8f49-464b-b9dc-4208c5506f6f\az.hdinsight\6.0.0\[Content_Types].xml'
VERBOSE: Deleting 'C:\Users\frangom\AppData\Local\Temp\cf9db787-8f49-464b-b9dc-4208c5506f6f\az.hdinsight\6.0.0\_rels'
VERBOSE: Deleting 'C:\Users\frangom\AppData\Local\Temp\cf9db787-8f49-464b-b9dc-4208c5506f6f\az.hdinsight\6.0.0\package'
VERBOSE: Performing the operation "Save-PSResource" on target "Package to save: 'Az.HealthcareApis', version: '2.0.0'".
VERBOSE: Performing the operation "Save-PSResource" on target "Package to install: 'Az.HealthcareApis', version: '2.0.0'".
VERBOSE: Deleting 'C:\Users\frangom\AppData\Local\Temp\cf9db787-8f49-464b-b9dc-4208c5506f6f\az.healthcareapis\2.0.0\Az.HealthcareApis.nuspec'
VERBOSE: Deleting 'C:\Users\frangom\AppData\Local\Temp\cf9db787-8f49-464b-b9dc-4208c5506f6f\az.healthcareapis\2.0.0\[Content_Types].xml'
VERBOSE: Deleting 'C:\Users\frangom\AppData\Local\Temp\cf9db787-8f49-464b-b9dc-4208c5506f6f\az.healthcareapis\2.0.0\_rels'
VERBOSE: Deleting 'C:\Users\frangom\AppData\Local\Temp\cf9db787-8f49-464b-b9dc-4208c5506f6f\az.healthcareapis\2.0.0\package'
VERBOSE: Performing the operation "Save-PSResource" on target "Package to save: 'Az.IotHub', version: '2.7.5'".
VERBOSE: Performing the operation "Save-PSResource" on target "Package to install: 'Az.IotHub', version: '2.7.5'".
VERBOSE: Deleting 'C:\Users\frangom\AppData\Local\Temp\cf9db787-8f49-464b-b9dc-4208c5506f6f\az.iothub\2.7.5\Az.IotHub.nuspec'
VERBOSE: Deleting 'C:\Users\frangom\AppData\Local\Temp\cf9db787-8f49-464b-b9dc-4208c5506f6f\az.iothub\2.7.5\[Content_Types].xml'
VERBOSE: Deleting 'C:\Users\frangom\AppData\Local\Temp\cf9db787-8f49-464b-b9dc-4208c5506f6f\az.iothub\2.7.5\_rels'
VERBOSE: Deleting 'C:\Users\frangom\AppData\Local\Temp\cf9db787-8f49-464b-b9dc-4208c5506f6f\az.iothub\2.7.5\package'
VERBOSE: Performing the operation "Save-PSResource" on target "Package to save: 'Az.KeyVault', version: '4.10.0'".
VERBOSE: Performing the operation "Save-PSResource" on target "Package to install: 'Az.KeyVault', version: '4.10.0'".
VERBOSE: Deleting 'C:\Users\frangom\AppData\Local\Temp\cf9db787-8f49-464b-b9dc-4208c5506f6f\az.keyvault\4.10.0\Az.KeyVault.nuspec'
VERBOSE: Deleting 'C:\Users\frangom\AppData\Local\Temp\cf9db787-8f49-464b-b9dc-4208c5506f6f\az.keyvault\4.10.0\[Content_Types].xml'
VERBOSE: Deleting 'C:\Users\frangom\AppData\Local\Temp\cf9db787-8f49-464b-b9dc-4208c5506f6f\az.keyvault\4.10.0\_rels'
VERBOSE: Deleting 'C:\Users\frangom\AppData\Local\Temp\cf9db787-8f49-464b-b9dc-4208c5506f6f\az.keyvault\4.10.0\package'
VERBOSE: Performing the operation "Save-PSResource" on target "Package to save: 'Az.Kusto', version: '2.2.0'".
VERBOSE: Performing the operation "Save-PSResource" on target "Package to install: 'Az.Kusto', version: '2.2.0'".
VERBOSE: Deleting 'C:\Users\frangom\AppData\Local\Temp\cf9db787-8f49-464b-b9dc-4208c5506f6f\az.kusto\2.2.0\Az.Kusto.nuspec'
VERBOSE: Deleting 'C:\Users\frangom\AppData\Local\Temp\cf9db787-8f49-464b-b9dc-4208c5506f6f\az.kusto\2.2.0\[Content_Types].xml'
VERBOSE: Deleting 'C:\Users\frangom\AppData\Local\Temp\cf9db787-8f49-464b-b9dc-4208c5506f6f\az.kusto\2.2.0\_rels'
VERBOSE: Deleting 'C:\Users\frangom\AppData\Local\Temp\cf9db787-8f49-464b-b9dc-4208c5506f6f\az.kusto\2.2.0\package'
VERBOSE: Performing the operation "Save-PSResource" on target "Package to save: 'Az.LoadTesting', version: '1.0.0'".
VERBOSE: Performing the operation "Save-PSResource" on target "Package to install: 'Az.LoadTesting', version: '1.0.0'".
VERBOSE: Deleting 'C:\Users\frangom\AppData\Local\Temp\cf9db787-8f49-464b-b9dc-4208c5506f6f\az.loadtesting\1.0.0\Az.LoadTesting.nuspec'
VERBOSE: Deleting 'C:\Users\frangom\AppData\Local\Temp\cf9db787-8f49-464b-b9dc-4208c5506f6f\az.loadtesting\1.0.0\[Content_Types].xml'
VERBOSE: Deleting 'C:\Users\frangom\AppData\Local\Temp\cf9db787-8f49-464b-b9dc-4208c5506f6f\az.loadtesting\1.0.0\_rels'
VERBOSE: Deleting 'C:\Users\frangom\AppData\Local\Temp\cf9db787-8f49-464b-b9dc-4208c5506f6f\az.loadtesting\1.0.0\package'
VERBOSE: Performing the operation "Save-PSResource" on target "Package to save: 'Az.LogicApp', version: '1.5.0'".
VERBOSE: Performing the operation "Save-PSResource" on target "Package to install: 'Az.LogicApp', version: '1.5.0'".
VERBOSE: Deleting 'C:\Users\frangom\AppData\Local\Temp\cf9db787-8f49-464b-b9dc-4208c5506f6f\az.logicapp\1.5.0\Az.LogicApp.nuspec'
VERBOSE: Deleting 'C:\Users\frangom\AppData\Local\Temp\cf9db787-8f49-464b-b9dc-4208c5506f6f\az.logicapp\1.5.0\[Content_Types].xml'
VERBOSE: Deleting 'C:\Users\frangom\AppData\Local\Temp\cf9db787-8f49-464b-b9dc-4208c5506f6f\az.logicapp\1.5.0\_rels'
VERBOSE: Deleting 'C:\Users\frangom\AppData\Local\Temp\cf9db787-8f49-464b-b9dc-4208c5506f6f\az.logicapp\1.5.0\package'
VERBOSE: Performing the operation "Save-PSResource" on target "Package to save: 'Az.MachineLearning', version: '1.1.3'".
VERBOSE: Performing the operation "Save-PSResource" on target "Package to install: 'Az.MachineLearning', version: '1.1.3'".
VERBOSE: Deleting 'C:\Users\frangom\AppData\Local\Temp\cf9db787-8f49-464b-b9dc-4208c5506f6f\az.machinelearning\1.1.3\Az.MachineLearning.nuspec'
VERBOSE: Deleting 'C:\Users\frangom\AppData\Local\Temp\cf9db787-8f49-464b-b9dc-4208c5506f6f\az.machinelearning\1.1.3\[Content_Types].xml'
VERBOSE: Deleting 'C:\Users\frangom\AppData\Local\Temp\cf9db787-8f49-464b-b9dc-4208c5506f6f\az.machinelearning\1.1.3\_rels'
VERBOSE: Deleting 'C:\Users\frangom\AppData\Local\Temp\cf9db787-8f49-464b-b9dc-4208c5506f6f\az.machinelearning\1.1.3\package'
VERBOSE: Performing the operation "Save-PSResource" on target "Package to save: 'Az.MachineLearningServices', version: '1.0.0'".
VERBOSE: Performing the operation "Save-PSResource" on target "Package to install: 'Az.MachineLearningServices', version: '1.0.0'".
VERBOSE: Deleting 'C:\Users\frangom\AppData\Local\Temp\cf9db787-8f49-464b-b9dc-4208c5506f6f\az.machinelearningservices\1.0.0\Az.MachineLearningServices.nuspec'
VERBOSE: Deleting 'C:\Users\frangom\AppData\Local\Temp\cf9db787-8f49-464b-b9dc-4208c5506f6f\az.machinelearningservices\1.0.0\[Content_Types].xml'
VERBOSE: Deleting 'C:\Users\frangom\AppData\Local\Temp\cf9db787-8f49-464b-b9dc-4208c5506f6f\az.machinelearningservices\1.0.0\_rels'
VERBOSE: Deleting 'C:\Users\frangom\AppData\Local\Temp\cf9db787-8f49-464b-b9dc-4208c5506f6f\az.machinelearningservices\1.0.0\package'
VERBOSE: Performing the operation "Save-PSResource" on target "Package to save: 'Az.Maintenance', version: '1.2.1'".
VERBOSE: Performing the operation "Save-PSResource" on target "Package to install: 'Az.Maintenance', version: '1.2.1'".
VERBOSE: Deleting 'C:\Users\frangom\AppData\Local\Temp\cf9db787-8f49-464b-b9dc-4208c5506f6f\az.maintenance\1.2.1\Az.Maintenance.nuspec'
VERBOSE: Deleting 'C:\Users\frangom\AppData\Local\Temp\cf9db787-8f49-464b-b9dc-4208c5506f6f\az.maintenance\1.2.1\[Content_Types].xml'
VERBOSE: Deleting 'C:\Users\frangom\AppData\Local\Temp\cf9db787-8f49-464b-b9dc-4208c5506f6f\az.maintenance\1.2.1\_rels'
VERBOSE: Deleting 'C:\Users\frangom\AppData\Local\Temp\cf9db787-8f49-464b-b9dc-4208c5506f6f\az.maintenance\1.2.1\package'
VERBOSE: Performing the operation "Save-PSResource" on target "Package to save: 'Az.ManagedServiceIdentity', version: '1.1.1'".
VERBOSE: Performing the operation "Save-PSResource" on target "Package to install: 'Az.ManagedServiceIdentity', version: '1.1.1'".
VERBOSE: Deleting 'C:\Users\frangom\AppData\Local\Temp\cf9db787-8f49-464b-b9dc-4208c5506f6f\az.managedserviceidentity\1.1.1\Az.ManagedServiceIdentity.nuspec'
VERBOSE: Deleting 'C:\Users\frangom\AppData\Local\Temp\cf9db787-8f49-464b-b9dc-4208c5506f6f\az.managedserviceidentity\1.1.1\[Content_Types].xml'
VERBOSE: Deleting 'C:\Users\frangom\AppData\Local\Temp\cf9db787-8f49-464b-b9dc-4208c5506f6f\az.managedserviceidentity\1.1.1\_rels'
VERBOSE: Deleting 'C:\Users\frangom\AppData\Local\Temp\cf9db787-8f49-464b-b9dc-4208c5506f6f\az.managedserviceidentity\1.1.1\package'
VERBOSE: Performing the operation "Save-PSResource" on target "Package to save: 'Az.ManagedServices', version: '3.0.0'".
VERBOSE: Performing the operation "Save-PSResource" on target "Package to install: 'Az.ManagedServices', version: '3.0.0'".
VERBOSE: Deleting 'C:\Users\frangom\AppData\Local\Temp\cf9db787-8f49-464b-b9dc-4208c5506f6f\az.managedservices\3.0.0\Az.ManagedServices.nuspec'
VERBOSE: Deleting 'C:\Users\frangom\AppData\Local\Temp\cf9db787-8f49-464b-b9dc-4208c5506f6f\az.managedservices\3.0.0\[Content_Types].xml'
VERBOSE: Deleting 'C:\Users\frangom\AppData\Local\Temp\cf9db787-8f49-464b-b9dc-4208c5506f6f\az.managedservices\3.0.0\_rels'
VERBOSE: Deleting 'C:\Users\frangom\AppData\Local\Temp\cf9db787-8f49-464b-b9dc-4208c5506f6f\az.managedservices\3.0.0\package'
VERBOSE: Performing the operation "Save-PSResource" on target "Package to save: 'Az.MarketplaceOrdering', version: '2.0.0'".
VERBOSE: Performing the operation "Save-PSResource" on target "Package to install: 'Az.MarketplaceOrdering', version: '2.0.0'".
VERBOSE: Deleting 'C:\Users\frangom\AppData\Local\Temp\cf9db787-8f49-464b-b9dc-4208c5506f6f\az.marketplaceordering\2.0.0\Az.MarketplaceOrdering.nuspec'
VERBOSE: Deleting 'C:\Users\frangom\AppData\Local\Temp\cf9db787-8f49-464b-b9dc-4208c5506f6f\az.marketplaceordering\2.0.0\[Content_Types].xml'
VERBOSE: Deleting 'C:\Users\frangom\AppData\Local\Temp\cf9db787-8f49-464b-b9dc-4208c5506f6f\az.marketplaceordering\2.0.0\_rels'
VERBOSE: Deleting 'C:\Users\frangom\AppData\Local\Temp\cf9db787-8f49-464b-b9dc-4208c5506f6f\az.marketplaceordering\2.0.0\package'
VERBOSE: Performing the operation "Save-PSResource" on target "Package to save: 'Az.Media', version: '1.1.1'".
VERBOSE: Performing the operation "Save-PSResource" on target "Package to install: 'Az.Media', version: '1.1.1'".
VERBOSE: Deleting 'C:\Users\frangom\AppData\Local\Temp\cf9db787-8f49-464b-b9dc-4208c5506f6f\az.media\1.1.1\Az.Media.nuspec'
VERBOSE: Deleting 'C:\Users\frangom\AppData\Local\Temp\cf9db787-8f49-464b-b9dc-4208c5506f6f\az.media\1.1.1\[Content_Types].xml'
VERBOSE: Deleting 'C:\Users\frangom\AppData\Local\Temp\cf9db787-8f49-464b-b9dc-4208c5506f6f\az.media\1.1.1\_rels'
VERBOSE: Deleting 'C:\Users\frangom\AppData\Local\Temp\cf9db787-8f49-464b-b9dc-4208c5506f6f\az.media\1.1.1\package'
VERBOSE: Performing the operation "Save-PSResource" on target "Package to save: 'Az.Migrate', version: '2.2.0'".
VERBOSE: Performing the operation "Save-PSResource" on target "Package to install: 'Az.Migrate', version: '2.2.0'".
VERBOSE: Deleting 'C:\Users\frangom\AppData\Local\Temp\cf9db787-8f49-464b-b9dc-4208c5506f6f\az.migrate\2.2.0\Az.Migrate.nuspec'
VERBOSE: Deleting 'C:\Users\frangom\AppData\Local\Temp\cf9db787-8f49-464b-b9dc-4208c5506f6f\az.migrate\2.2.0\[Content_Types].xml'
VERBOSE: Deleting 'C:\Users\frangom\AppData\Local\Temp\cf9db787-8f49-464b-b9dc-4208c5506f6f\az.migrate\2.2.0\_rels'
VERBOSE: Deleting 'C:\Users\frangom\AppData\Local\Temp\cf9db787-8f49-464b-b9dc-4208c5506f6f\az.migrate\2.2.0\package'
VERBOSE: Performing the operation "Save-PSResource" on target "Package to save: 'Az.Monitor', version: '4.5.0'".
VERBOSE: Performing the operation "Save-PSResource" on target "Package to install: 'Az.Monitor', version: '4.5.0'".
VERBOSE: Deleting 'C:\Users\frangom\AppData\Local\Temp\cf9db787-8f49-464b-b9dc-4208c5506f6f\az.monitor\4.5.0\Az.Monitor.nuspec'
VERBOSE: Deleting 'C:\Users\frangom\AppData\Local\Temp\cf9db787-8f49-464b-b9dc-4208c5506f6f\az.monitor\4.5.0\[Content_Types].xml'
VERBOSE: Deleting 'C:\Users\frangom\AppData\Local\Temp\cf9db787-8f49-464b-b9dc-4208c5506f6f\az.monitor\4.5.0\_rels'
VERBOSE: Deleting 'C:\Users\frangom\AppData\Local\Temp\cf9db787-8f49-464b-b9dc-4208c5506f6f\az.monitor\4.5.0\package'
VERBOSE: Performing the operation "Save-PSResource" on target "Package to save: 'Az.MySql', version: '1.1.1'".
VERBOSE: Performing the operation "Save-PSResource" on target "Package to install: 'Az.MySql', version: '1.1.1'".
VERBOSE: Deleting 'C:\Users\frangom\AppData\Local\Temp\cf9db787-8f49-464b-b9dc-4208c5506f6f\az.mysql\1.1.1\Az.MySql.nuspec'
VERBOSE: Deleting 'C:\Users\frangom\AppData\Local\Temp\cf9db787-8f49-464b-b9dc-4208c5506f6f\az.mysql\1.1.1\[Content_Types].xml'
VERBOSE: Deleting 'C:\Users\frangom\AppData\Local\Temp\cf9db787-8f49-464b-b9dc-4208c5506f6f\az.mysql\1.1.1\_rels'
VERBOSE: Deleting 'C:\Users\frangom\AppData\Local\Temp\cf9db787-8f49-464b-b9dc-4208c5506f6f\az.mysql\1.1.1\package'
VERBOSE: Performing the operation "Save-PSResource" on target "Package to save: 'Az.Network', version: '6.1.0'".
VERBOSE: Performing the operation "Save-PSResource" on target "Package to install: 'Az.Network', version: '6.1.0'".
VERBOSE: Deleting 'C:\Users\frangom\AppData\Local\Temp\cf9db787-8f49-464b-b9dc-4208c5506f6f\az.network\6.1.0\Az.Network.nuspec'
VERBOSE: Deleting 'C:\Users\frangom\AppData\Local\Temp\cf9db787-8f49-464b-b9dc-4208c5506f6f\az.network\6.1.0\[Content_Types].xml'
VERBOSE: Deleting 'C:\Users\frangom\AppData\Local\Temp\cf9db787-8f49-464b-b9dc-4208c5506f6f\az.network\6.1.0\_rels'
VERBOSE: Deleting 'C:\Users\frangom\AppData\Local\Temp\cf9db787-8f49-464b-b9dc-4208c5506f6f\az.network\6.1.0\package'
VERBOSE: Performing the operation "Save-PSResource" on target "Package to save: 'Az.NotificationHubs', version: '1.1.1'".
VERBOSE: Performing the operation "Save-PSResource" on target "Package to install: 'Az.NotificationHubs', version: '1.1.1'".
VERBOSE: Deleting 'C:\Users\frangom\AppData\Local\Temp\cf9db787-8f49-464b-b9dc-4208c5506f6f\az.notificationhubs\1.1.1\Az.NotificationHubs.nuspec'
VERBOSE: Deleting 'C:\Users\frangom\AppData\Local\Temp\cf9db787-8f49-464b-b9dc-4208c5506f6f\az.notificationhubs\1.1.1\[Content_Types].xml'
VERBOSE: Deleting 'C:\Users\frangom\AppData\Local\Temp\cf9db787-8f49-464b-b9dc-4208c5506f6f\az.notificationhubs\1.1.1\_rels'
VERBOSE: Deleting 'C:\Users\frangom\AppData\Local\Temp\cf9db787-8f49-464b-b9dc-4208c5506f6f\az.notificationhubs\1.1.1\package'
VERBOSE: Performing the operation "Save-PSResource" on target "Package to save: 'Az.OperationalInsights', version: '3.2.0'".
VERBOSE: Performing the operation "Save-PSResource" on target "Package to install: 'Az.OperationalInsights', version: '3.2.0'".
VERBOSE: Deleting 'C:\Users\frangom\AppData\Local\Temp\cf9db787-8f49-464b-b9dc-4208c5506f6f\az.operationalinsights\3.2.0\Az.OperationalInsights.nuspec'
VERBOSE: Deleting 'C:\Users\frangom\AppData\Local\Temp\cf9db787-8f49-464b-b9dc-4208c5506f6f\az.operationalinsights\3.2.0\[Content_Types].xml'
VERBOSE: Deleting 'C:\Users\frangom\AppData\Local\Temp\cf9db787-8f49-464b-b9dc-4208c5506f6f\az.operationalinsights\3.2.0\_rels'
VERBOSE: Deleting 'C:\Users\frangom\AppData\Local\Temp\cf9db787-8f49-464b-b9dc-4208c5506f6f\az.operationalinsights\3.2.0\package'
VERBOSE: Performing the operation "Save-PSResource" on target "Package to save: 'Az.PolicyInsights', version: '1.6.1'".
VERBOSE: Performing the operation "Save-PSResource" on target "Package to install: 'Az.PolicyInsights', version: '1.6.1'".
VERBOSE: Deleting 'C:\Users\frangom\AppData\Local\Temp\cf9db787-8f49-464b-b9dc-4208c5506f6f\az.policyinsights\1.6.1\Az.PolicyInsights.nuspec'
VERBOSE: Deleting 'C:\Users\frangom\AppData\Local\Temp\cf9db787-8f49-464b-b9dc-4208c5506f6f\az.policyinsights\1.6.1\[Content_Types].xml'
VERBOSE: Deleting 'C:\Users\frangom\AppData\Local\Temp\cf9db787-8f49-464b-b9dc-4208c5506f6f\az.policyinsights\1.6.1\_rels'
VERBOSE: Deleting 'C:\Users\frangom\AppData\Local\Temp\cf9db787-8f49-464b-b9dc-4208c5506f6f\az.policyinsights\1.6.1\package'
VERBOSE: Performing the operation "Save-PSResource" on target "Package to save: 'Az.PostgreSql', version: '1.1.0'".
VERBOSE: Performing the operation "Save-PSResource" on target "Package to install: 'Az.PostgreSql', version: '1.1.0'".
VERBOSE: Deleting 'C:\Users\frangom\AppData\Local\Temp\cf9db787-8f49-464b-b9dc-4208c5506f6f\az.postgresql\1.1.0\Az.PostgreSql.nuspec'
VERBOSE: Deleting 'C:\Users\frangom\AppData\Local\Temp\cf9db787-8f49-464b-b9dc-4208c5506f6f\az.postgresql\1.1.0\[Content_Types].xml'
VERBOSE: Deleting 'C:\Users\frangom\AppData\Local\Temp\cf9db787-8f49-464b-b9dc-4208c5506f6f\az.postgresql\1.1.0\_rels'
VERBOSE: Deleting 'C:\Users\frangom\AppData\Local\Temp\cf9db787-8f49-464b-b9dc-4208c5506f6f\az.postgresql\1.1.0\package'
VERBOSE: Performing the operation "Save-PSResource" on target "Package to save: 'Az.PowerBIEmbedded', version: '1.2.1'".
VERBOSE: Performing the operation "Save-PSResource" on target "Package to install: 'Az.PowerBIEmbedded', version: '1.2.1'".
VERBOSE: Deleting 'C:\Users\frangom\AppData\Local\Temp\cf9db787-8f49-464b-b9dc-4208c5506f6f\az.powerbiembedded\1.2.1\Az.PowerBIEmbedded.nuspec'
VERBOSE: Deleting 'C:\Users\frangom\AppData\Local\Temp\cf9db787-8f49-464b-b9dc-4208c5506f6f\az.powerbiembedded\1.2.1\[Content_Types].xml'
VERBOSE: Deleting 'C:\Users\frangom\AppData\Local\Temp\cf9db787-8f49-464b-b9dc-4208c5506f6f\az.powerbiembedded\1.2.1\_rels'
VERBOSE: Deleting 'C:\Users\frangom\AppData\Local\Temp\cf9db787-8f49-464b-b9dc-4208c5506f6f\az.powerbiembedded\1.2.1\package'
VERBOSE: Performing the operation "Save-PSResource" on target "Package to save: 'Az.PrivateDns', version: '1.0.3'".
VERBOSE: Performing the operation "Save-PSResource" on target "Package to install: 'Az.PrivateDns', version: '1.0.3'".
VERBOSE: Deleting 'C:\Users\frangom\AppData\Local\Temp\cf9db787-8f49-464b-b9dc-4208c5506f6f\az.privatedns\1.0.3\Az.PrivateDns.nuspec'
VERBOSE: Deleting 'C:\Users\frangom\AppData\Local\Temp\cf9db787-8f49-464b-b9dc-4208c5506f6f\az.privatedns\1.0.3\[Content_Types].xml'
VERBOSE: Deleting 'C:\Users\frangom\AppData\Local\Temp\cf9db787-8f49-464b-b9dc-4208c5506f6f\az.privatedns\1.0.3\_rels'
VERBOSE: Deleting 'C:\Users\frangom\AppData\Local\Temp\cf9db787-8f49-464b-b9dc-4208c5506f6f\az.privatedns\1.0.3\package'
VERBOSE: Performing the operation "Save-PSResource" on target "Package to save: 'Az.RecoveryServices', version: '6.5.0'".
VERBOSE: Performing the operation "Save-PSResource" on target "Package to install: 'Az.RecoveryServices', version: '6.5.0'".
VERBOSE: Deleting 'C:\Users\frangom\AppData\Local\Temp\cf9db787-8f49-464b-b9dc-4208c5506f6f\az.recoveryservices\6.5.0\Az.RecoveryServices.nuspec'
VERBOSE: Deleting 'C:\Users\frangom\AppData\Local\Temp\cf9db787-8f49-464b-b9dc-4208c5506f6f\az.recoveryservices\6.5.0\[Content_Types].xml'
VERBOSE: Deleting 'C:\Users\frangom\AppData\Local\Temp\cf9db787-8f49-464b-b9dc-4208c5506f6f\az.recoveryservices\6.5.0\_rels'
VERBOSE: Deleting 'C:\Users\frangom\AppData\Local\Temp\cf9db787-8f49-464b-b9dc-4208c5506f6f\az.recoveryservices\6.5.0\package'
VERBOSE: Performing the operation "Save-PSResource" on target "Package to save: 'Az.RedisCache', version: '1.8.0'".
VERBOSE: Performing the operation "Save-PSResource" on target "Package to install: 'Az.RedisCache', version: '1.8.0'".
VERBOSE: Deleting 'C:\Users\frangom\AppData\Local\Temp\cf9db787-8f49-464b-b9dc-4208c5506f6f\az.rediscache\1.8.0\Az.RedisCache.nuspec'
VERBOSE: Deleting 'C:\Users\frangom\AppData\Local\Temp\cf9db787-8f49-464b-b9dc-4208c5506f6f\az.rediscache\1.8.0\[Content_Types].xml'
VERBOSE: Deleting 'C:\Users\frangom\AppData\Local\Temp\cf9db787-8f49-464b-b9dc-4208c5506f6f\az.rediscache\1.8.0\_rels'
VERBOSE: Deleting 'C:\Users\frangom\AppData\Local\Temp\cf9db787-8f49-464b-b9dc-4208c5506f6f\az.rediscache\1.8.0\package'
VERBOSE: Performing the operation "Save-PSResource" on target "Package to save: 'Az.RedisEnterpriseCache', version: '1.2.0'".
VERBOSE: Performing the operation "Save-PSResource" on target "Package to install: 'Az.RedisEnterpriseCache', version: '1.2.0'".
VERBOSE: Deleting 'C:\Users\frangom\AppData\Local\Temp\cf9db787-8f49-464b-b9dc-4208c5506f6f\az.redisenterprisecache\1.2.0\Az.RedisEnterpriseCache.nuspec'
VERBOSE: Deleting 'C:\Users\frangom\AppData\Local\Temp\cf9db787-8f49-464b-b9dc-4208c5506f6f\az.redisenterprisecache\1.2.0\[Content_Types].xml'
VERBOSE: Deleting 'C:\Users\frangom\AppData\Local\Temp\cf9db787-8f49-464b-b9dc-4208c5506f6f\az.redisenterprisecache\1.2.0\_rels'
VERBOSE: Deleting 'C:\Users\frangom\AppData\Local\Temp\cf9db787-8f49-464b-b9dc-4208c5506f6f\az.redisenterprisecache\1.2.0\package'
VERBOSE: Performing the operation "Save-PSResource" on target "Package to save: 'Az.Relay', version: '2.0.0'".
VERBOSE: Performing the operation "Save-PSResource" on target "Package to install: 'Az.Relay', version: '2.0.0'".
VERBOSE: Deleting 'C:\Users\frangom\AppData\Local\Temp\cf9db787-8f49-464b-b9dc-4208c5506f6f\az.relay\2.0.0\Az.Relay.nuspec'
VERBOSE: Deleting 'C:\Users\frangom\AppData\Local\Temp\cf9db787-8f49-464b-b9dc-4208c5506f6f\az.relay\2.0.0\[Content_Types].xml'
VERBOSE: Deleting 'C:\Users\frangom\AppData\Local\Temp\cf9db787-8f49-464b-b9dc-4208c5506f6f\az.relay\2.0.0\_rels'
VERBOSE: Deleting 'C:\Users\frangom\AppData\Local\Temp\cf9db787-8f49-464b-b9dc-4208c5506f6f\az.relay\2.0.0\package'
VERBOSE: Performing the operation "Save-PSResource" on target "Package to save: 'Az.ResourceMover', version: '1.1.0'".
VERBOSE: Performing the operation "Save-PSResource" on target "Package to install: 'Az.ResourceMover', version: '1.1.0'".
VERBOSE: Deleting 'C:\Users\frangom\AppData\Local\Temp\cf9db787-8f49-464b-b9dc-4208c5506f6f\az.resourcemover\1.1.0\Az.ResourceMover.nuspec'
VERBOSE: Deleting 'C:\Users\frangom\AppData\Local\Temp\cf9db787-8f49-464b-b9dc-4208c5506f6f\az.resourcemover\1.1.0\[Content_Types].xml'
VERBOSE: Deleting 'C:\Users\frangom\AppData\Local\Temp\cf9db787-8f49-464b-b9dc-4208c5506f6f\az.resourcemover\1.1.0\_rels'
VERBOSE: Deleting 'C:\Users\frangom\AppData\Local\Temp\cf9db787-8f49-464b-b9dc-4208c5506f6f\az.resourcemover\1.1.0\package'
VERBOSE: Performing the operation "Save-PSResource" on target "Package to save: 'Az.Resources', version: '6.8.0'".
VERBOSE: Performing the operation "Save-PSResource" on target "Package to install: 'Az.Resources', version: '6.8.0'".
VERBOSE: Deleting 'C:\Users\frangom\AppData\Local\Temp\cf9db787-8f49-464b-b9dc-4208c5506f6f\az.resources\6.8.0\Az.Resources.nuspec'
VERBOSE: Deleting 'C:\Users\frangom\AppData\Local\Temp\cf9db787-8f49-464b-b9dc-4208c5506f6f\az.resources\6.8.0\[Content_Types].xml'
VERBOSE: Deleting 'C:\Users\frangom\AppData\Local\Temp\cf9db787-8f49-464b-b9dc-4208c5506f6f\az.resources\6.8.0\_rels'
VERBOSE: Deleting 'C:\Users\frangom\AppData\Local\Temp\cf9db787-8f49-464b-b9dc-4208c5506f6f\az.resources\6.8.0\package'
VERBOSE: Performing the operation "Save-PSResource" on target "Package to save: 'Az.Security', version: '1.4.0'".
VERBOSE: Performing the operation "Save-PSResource" on target "Package to install: 'Az.Security', version: '1.4.0'".
VERBOSE: Deleting 'C:\Users\frangom\AppData\Local\Temp\cf9db787-8f49-464b-b9dc-4208c5506f6f\az.security\1.4.0\Az.Security.nuspec'
VERBOSE: Deleting 'C:\Users\frangom\AppData\Local\Temp\cf9db787-8f49-464b-b9dc-4208c5506f6f\az.security\1.4.0\[Content_Types].xml'
VERBOSE: Deleting 'C:\Users\frangom\AppData\Local\Temp\cf9db787-8f49-464b-b9dc-4208c5506f6f\az.security\1.4.0\_rels'
VERBOSE: Deleting 'C:\Users\frangom\AppData\Local\Temp\cf9db787-8f49-464b-b9dc-4208c5506f6f\az.security\1.4.0\package'
VERBOSE: Performing the operation "Save-PSResource" on target "Package to save: 'Az.SecurityInsights', version: '3.0.1'".
VERBOSE: Performing the operation "Save-PSResource" on target "Package to install: 'Az.SecurityInsights', version: '3.0.1'".
VERBOSE: Deleting 'C:\Users\frangom\AppData\Local\Temp\cf9db787-8f49-464b-b9dc-4208c5506f6f\az.securityinsights\3.0.1\Az.SecurityInsights.nuspec'
VERBOSE: Deleting 'C:\Users\frangom\AppData\Local\Temp\cf9db787-8f49-464b-b9dc-4208c5506f6f\az.securityinsights\3.0.1\[Content_Types].xml'
VERBOSE: Deleting 'C:\Users\frangom\AppData\Local\Temp\cf9db787-8f49-464b-b9dc-4208c5506f6f\az.securityinsights\3.0.1\_rels'
VERBOSE: Deleting 'C:\Users\frangom\AppData\Local\Temp\cf9db787-8f49-464b-b9dc-4208c5506f6f\az.securityinsights\3.0.1\package'
VERBOSE: Performing the operation "Save-PSResource" on target "Package to save: 'Az.ServiceBus', version: '3.0.0'".
VERBOSE: Performing the operation "Save-PSResource" on target "Package to install: 'Az.ServiceBus', version: '3.0.0'".
VERBOSE: Deleting 'C:\Users\frangom\AppData\Local\Temp\cf9db787-8f49-464b-b9dc-4208c5506f6f\az.servicebus\3.0.0\Az.ServiceBus.nuspec'
VERBOSE: Deleting 'C:\Users\frangom\AppData\Local\Temp\cf9db787-8f49-464b-b9dc-4208c5506f6f\az.servicebus\3.0.0\[Content_Types].xml'
VERBOSE: Deleting 'C:\Users\frangom\AppData\Local\Temp\cf9db787-8f49-464b-b9dc-4208c5506f6f\az.servicebus\3.0.0\_rels'
VERBOSE: Deleting 'C:\Users\frangom\AppData\Local\Temp\cf9db787-8f49-464b-b9dc-4208c5506f6f\az.servicebus\3.0.0\package'
VERBOSE: Performing the operation "Save-PSResource" on target "Package to save: 'Az.ServiceFabric', version: '3.2.0'".
VERBOSE: Performing the operation "Save-PSResource" on target "Package to install: 'Az.ServiceFabric', version: '3.2.0'".
VERBOSE: Deleting 'C:\Users\frangom\AppData\Local\Temp\cf9db787-8f49-464b-b9dc-4208c5506f6f\az.servicefabric\3.2.0\Az.ServiceFabric.nuspec'
VERBOSE: Deleting 'C:\Users\frangom\AppData\Local\Temp\cf9db787-8f49-464b-b9dc-4208c5506f6f\az.servicefabric\3.2.0\[Content_Types].xml'
VERBOSE: Deleting 'C:\Users\frangom\AppData\Local\Temp\cf9db787-8f49-464b-b9dc-4208c5506f6f\az.servicefabric\3.2.0\_rels'
VERBOSE: Deleting 'C:\Users\frangom\AppData\Local\Temp\cf9db787-8f49-464b-b9dc-4208c5506f6f\az.servicefabric\3.2.0\package'
VERBOSE: Performing the operation "Save-PSResource" on target "Package to save: 'Az.SignalR', version: '2.0.0'".
VERBOSE: Performing the operation "Save-PSResource" on target "Package to install: 'Az.SignalR', version: '2.0.0'".
VERBOSE: Deleting 'C:\Users\frangom\AppData\Local\Temp\cf9db787-8f49-464b-b9dc-4208c5506f6f\az.signalr\2.0.0\Az.SignalR.nuspec'
VERBOSE: Deleting 'C:\Users\frangom\AppData\Local\Temp\cf9db787-8f49-464b-b9dc-4208c5506f6f\az.signalr\2.0.0\[Content_Types].xml'
VERBOSE: Deleting 'C:\Users\frangom\AppData\Local\Temp\cf9db787-8f49-464b-b9dc-4208c5506f6f\az.signalr\2.0.0\_rels'
VERBOSE: Deleting 'C:\Users\frangom\AppData\Local\Temp\cf9db787-8f49-464b-b9dc-4208c5506f6f\az.signalr\2.0.0\package'
VERBOSE: Performing the operation "Save-PSResource" on target "Package to save: 'Az.Sql', version: '4.8.0'".
VERBOSE: Performing the operation "Save-PSResource" on target "Package to install: 'Az.Sql', version: '4.8.0'".
VERBOSE: Deleting 'C:\Users\frangom\AppData\Local\Temp\cf9db787-8f49-464b-b9dc-4208c5506f6f\az.sql\4.8.0\Az.Sql.nuspec'
VERBOSE: Deleting 'C:\Users\frangom\AppData\Local\Temp\cf9db787-8f49-464b-b9dc-4208c5506f6f\az.sql\4.8.0\[Content_Types].xml'
VERBOSE: Deleting 'C:\Users\frangom\AppData\Local\Temp\cf9db787-8f49-464b-b9dc-4208c5506f6f\az.sql\4.8.0\_rels'
VERBOSE: Deleting 'C:\Users\frangom\AppData\Local\Temp\cf9db787-8f49-464b-b9dc-4208c5506f6f\az.sql\4.8.0\package'
VERBOSE: Performing the operation "Save-PSResource" on target "Package to save: 'Az.SqlVirtualMachine', version: '2.0.0'".
VERBOSE: Performing the operation "Save-PSResource" on target "Package to install: 'Az.SqlVirtualMachine', version: '2.0.0'".
VERBOSE: Deleting 'C:\Users\frangom\AppData\Local\Temp\cf9db787-8f49-464b-b9dc-4208c5506f6f\az.sqlvirtualmachine\2.0.0\Az.SqlVirtualMachine.nuspec'
VERBOSE: Deleting 'C:\Users\frangom\AppData\Local\Temp\cf9db787-8f49-464b-b9dc-4208c5506f6f\az.sqlvirtualmachine\2.0.0\[Content_Types].xml'
VERBOSE: Deleting 'C:\Users\frangom\AppData\Local\Temp\cf9db787-8f49-464b-b9dc-4208c5506f6f\az.sqlvirtualmachine\2.0.0\_rels'
VERBOSE: Deleting 'C:\Users\frangom\AppData\Local\Temp\cf9db787-8f49-464b-b9dc-4208c5506f6f\az.sqlvirtualmachine\2.0.0\package'
VERBOSE: Performing the operation "Save-PSResource" on target "Package to save: 'Az.StackHCI', version: '2.0.0'".
VERBOSE: Performing the operation "Save-PSResource" on target "Package to install: 'Az.StackHCI', version: '2.0.0'".
VERBOSE: Deleting 'C:\Users\frangom\AppData\Local\Temp\cf9db787-8f49-464b-b9dc-4208c5506f6f\az.stackhci\2.0.0\Az.StackHCI.nuspec'
VERBOSE: Deleting 'C:\Users\frangom\AppData\Local\Temp\cf9db787-8f49-464b-b9dc-4208c5506f6f\az.stackhci\2.0.0\[Content_Types].xml'
VERBOSE: Deleting 'C:\Users\frangom\AppData\Local\Temp\cf9db787-8f49-464b-b9dc-4208c5506f6f\az.stackhci\2.0.0\_rels'
VERBOSE: Deleting 'C:\Users\frangom\AppData\Local\Temp\cf9db787-8f49-464b-b9dc-4208c5506f6f\az.stackhci\2.0.0\package'
VERBOSE: Performing the operation "Save-PSResource" on target "Package to save: 'Az.Storage', version: '5.8.0'".
VERBOSE: Performing the operation "Save-PSResource" on target "Package to install: 'Az.Storage', version: '5.8.0'".
VERBOSE: Deleting 'C:\Users\frangom\AppData\Local\Temp\cf9db787-8f49-464b-b9dc-4208c5506f6f\az.storage\5.8.0\Az.Storage.nuspec'
VERBOSE: Deleting 'C:\Users\frangom\AppData\Local\Temp\cf9db787-8f49-464b-b9dc-4208c5506f6f\az.storage\5.8.0\[Content_Types].xml'
VERBOSE: Deleting 'C:\Users\frangom\AppData\Local\Temp\cf9db787-8f49-464b-b9dc-4208c5506f6f\az.storage\5.8.0\_rels'
VERBOSE: Deleting 'C:\Users\frangom\AppData\Local\Temp\cf9db787-8f49-464b-b9dc-4208c5506f6f\az.storage\5.8.0\package'
VERBOSE: Performing the operation "Save-PSResource" on target "Package to save: 'Az.StorageMover', version: '1.0.1'".
VERBOSE: Performing the operation "Save-PSResource" on target "Package to install: 'Az.StorageMover', version: '1.0.1'".
VERBOSE: Deleting 'C:\Users\frangom\AppData\Local\Temp\cf9db787-8f49-464b-b9dc-4208c5506f6f\az.storagemover\1.0.1\Az.StorageMover.nuspec'
VERBOSE: Deleting 'C:\Users\frangom\AppData\Local\Temp\cf9db787-8f49-464b-b9dc-4208c5506f6f\az.storagemover\1.0.1\[Content_Types].xml'
VERBOSE: Deleting 'C:\Users\frangom\AppData\Local\Temp\cf9db787-8f49-464b-b9dc-4208c5506f6f\az.storagemover\1.0.1\_rels'
VERBOSE: Deleting 'C:\Users\frangom\AppData\Local\Temp\cf9db787-8f49-464b-b9dc-4208c5506f6f\az.storagemover\1.0.1\package'
VERBOSE: Performing the operation "Save-PSResource" on target "Package to save: 'Az.StorageSync', version: '2.0.0'".
VERBOSE: Performing the operation "Save-PSResource" on target "Package to install: 'Az.StorageSync', version: '2.0.0'".
VERBOSE: Deleting 'C:\Users\frangom\AppData\Local\Temp\cf9db787-8f49-464b-b9dc-4208c5506f6f\az.storagesync\2.0.0\Az.StorageSync.nuspec'
VERBOSE: Deleting 'C:\Users\frangom\AppData\Local\Temp\cf9db787-8f49-464b-b9dc-4208c5506f6f\az.storagesync\2.0.0\[Content_Types].xml'
VERBOSE: Deleting 'C:\Users\frangom\AppData\Local\Temp\cf9db787-8f49-464b-b9dc-4208c5506f6f\az.storagesync\2.0.0\_rels'
VERBOSE: Deleting 'C:\Users\frangom\AppData\Local\Temp\cf9db787-8f49-464b-b9dc-4208c5506f6f\az.storagesync\2.0.0\package'
VERBOSE: Performing the operation "Save-PSResource" on target "Package to save: 'Az.StreamAnalytics', version: '2.0.0'".
VERBOSE: Performing the operation "Save-PSResource" on target "Package to install: 'Az.StreamAnalytics', version: '2.0.0'".
VERBOSE: Deleting 'C:\Users\frangom\AppData\Local\Temp\cf9db787-8f49-464b-b9dc-4208c5506f6f\az.streamanalytics\2.0.0\Az.StreamAnalytics.nuspec'
VERBOSE: Deleting 'C:\Users\frangom\AppData\Local\Temp\cf9db787-8f49-464b-b9dc-4208c5506f6f\az.streamanalytics\2.0.0\[Content_Types].xml'
VERBOSE: Deleting 'C:\Users\frangom\AppData\Local\Temp\cf9db787-8f49-464b-b9dc-4208c5506f6f\az.streamanalytics\2.0.0\_rels'
VERBOSE: Deleting 'C:\Users\frangom\AppData\Local\Temp\cf9db787-8f49-464b-b9dc-4208c5506f6f\az.streamanalytics\2.0.0\package'
VERBOSE: Performing the operation "Save-PSResource" on target "Package to save: 'Az.Support', version: '1.0.0'".
VERBOSE: Performing the operation "Save-PSResource" on target "Package to install: 'Az.Support', version: '1.0.0'".
VERBOSE: Deleting 'C:\Users\frangom\AppData\Local\Temp\cf9db787-8f49-464b-b9dc-4208c5506f6f\az.support\1.0.0\Az.Support.nuspec'
VERBOSE: Deleting 'C:\Users\frangom\AppData\Local\Temp\cf9db787-8f49-464b-b9dc-4208c5506f6f\az.support\1.0.0\[Content_Types].xml'
VERBOSE: Deleting 'C:\Users\frangom\AppData\Local\Temp\cf9db787-8f49-464b-b9dc-4208c5506f6f\az.support\1.0.0\_rels'
VERBOSE: Deleting 'C:\Users\frangom\AppData\Local\Temp\cf9db787-8f49-464b-b9dc-4208c5506f6f\az.support\1.0.0\package'
VERBOSE: Performing the operation "Save-PSResource" on target "Package to save: 'Az.Synapse', version: '3.0.1'".
VERBOSE: Performing the operation "Save-PSResource" on target "Package to install: 'Az.Synapse', version: '3.0.1'".
VERBOSE: Deleting 'C:\Users\frangom\AppData\Local\Temp\cf9db787-8f49-464b-b9dc-4208c5506f6f\az.synapse\3.0.1\Az.Synapse.nuspec'
VERBOSE: Deleting 'C:\Users\frangom\AppData\Local\Temp\cf9db787-8f49-464b-b9dc-4208c5506f6f\az.synapse\3.0.1\[Content_Types].xml'
VERBOSE: Deleting 'C:\Users\frangom\AppData\Local\Temp\cf9db787-8f49-464b-b9dc-4208c5506f6f\az.synapse\3.0.1\_rels'
VERBOSE: Deleting 'C:\Users\frangom\AppData\Local\Temp\cf9db787-8f49-464b-b9dc-4208c5506f6f\az.synapse\3.0.1\package'
VERBOSE: Performing the operation "Save-PSResource" on target "Package to save: 'Az.TrafficManager', version: '1.2.1'".
VERBOSE: Performing the operation "Save-PSResource" on target "Package to install: 'Az.TrafficManager', version: '1.2.1'".
VERBOSE: Deleting 'C:\Users\frangom\AppData\Local\Temp\cf9db787-8f49-464b-b9dc-4208c5506f6f\az.trafficmanager\1.2.1\Az.TrafficManager.nuspec'
VERBOSE: Deleting 'C:\Users\frangom\AppData\Local\Temp\cf9db787-8f49-464b-b9dc-4208c5506f6f\az.trafficmanager\1.2.1\[Content_Types].xml'
VERBOSE: Deleting 'C:\Users\frangom\AppData\Local\Temp\cf9db787-8f49-464b-b9dc-4208c5506f6f\az.trafficmanager\1.2.1\_rels'
VERBOSE: Deleting 'C:\Users\frangom\AppData\Local\Temp\cf9db787-8f49-464b-b9dc-4208c5506f6f\az.trafficmanager\1.2.1\package'
VERBOSE: Performing the operation "Save-PSResource" on target "Package to save: 'Az.Websites', version: '3.0.1'".
VERBOSE: Performing the operation "Save-PSResource" on target "Package to install: 'Az.Websites', version: '3.0.1'".
VERBOSE: Deleting 'C:\Users\frangom\AppData\Local\Temp\cf9db787-8f49-464b-b9dc-4208c5506f6f\az.websites\3.0.1\Az.Websites.nuspec'
VERBOSE: Deleting 'C:\Users\frangom\AppData\Local\Temp\cf9db787-8f49-464b-b9dc-4208c5506f6f\az.websites\3.0.1\[Content_Types].xml'
VERBOSE: Deleting 'C:\Users\frangom\AppData\Local\Temp\cf9db787-8f49-464b-b9dc-4208c5506f6f\az.websites\3.0.1\_rels'
VERBOSE: Deleting 'C:\Users\frangom\AppData\Local\Temp\cf9db787-8f49-464b-b9dc-4208c5506f6f\az.websites\3.0.1\package'
VERBOSE: Attempting to delete 'C:\Users\frangom\AppData\Local\Temp\cf9db787-8f49-464b-b9dc-4208c5506f6f'
VERBOSE: Successfully deleted 'C:\Users\frangom\AppData\Local\Temp\cf9db787-8f49-464b-b9dc-4208c5506f6f'
PS C:\modules> ls .\543857739\
PS C:\modules> 
```

### PR DESCRIPTION
**Pull request by alerickson**
# PR Summary
Bug fix for finding a module with version specified as a version range (eg. "[1.2.2, 1.2.2]").  

## PR Context
Resolves #1313 

## PR Checklist

- [x] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [x] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.
- **[Breaking changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)**
    - [x] None
    - **OR**
    - [ ] [Documentation needed]()
        - [ ] Issue filed: 
- **User-facing changes**
    - [x] Not Applicable
    - **OR**
    - [ ] [Documentation needed]()
        - [ ] Issue filed: 
- **Testing - New and feature**
    - [ ] N/A or can only be tested interactively
    - **OR**
    - [x] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
- **Tooling**
    - [x] I have considered the user experience from a tooling perspective and don't believe tooling will be impacted.
    - **OR**
    - [ ] I have considered the user experience from a tooling perspective and enumerated concerns in the summary.

### CODE REVIEW

File: src/code/V2ServerAPICalls.cs [hunk 1]
```diff
@@ -807,7 +807,8 @@ private string FindVersionGlobbing(string packageName, VersionRange versionRange
                 string operation = versionRange.IsMaxInclusive ? "le" : "lt";
                 // Adding 1 because we want to retrieve all the prerelease versions for the max version and PSGallery views prerelease as higher than its stable
                 // eg 3.0.0-prerelease > 3.0.0
-                string maxString = $"{versionRange.MaxVersion.Major}.{versionRange.MaxVersion.Minor + 1}";
+                string maxString = includePrerelease ? $"{versionRange.MaxVersion.Major}.{versionRange.MaxVersion.Minor + 1}" :
+                                $"{versionRange.MinVersion.ToNormalizedString()}";
```
Comment (adityapatwardhan) [inline src/code/V2ServerAPICalls.cs]:
```suggestion
                                $"{versionRange.MinVersion.ToNormalizedString()}";
                                
```

**Review by adityapatwardhan — APPROVED** [review]

**Comment by adityapatwardhan** [comment]
@alerickson please look at CI failure

**Comment by alerickson** [comment]
@adityapatwardhan just fixed it, the 'MinVersion' should have been 'MaxVersion'
