### PR TITLE
Remove warning when installing dependencies

### LINKED ISSUE #731: Install-PSResource writes warning about dependency already installed
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://www.powershellgallery.com/packages/PowerShellGet)
- [X] Search the existing issues.

### Steps to reproduce

`Install-PSResource` writes warning about dependency already installed.

### Expected behavior

```console
No warning
```

### Actual behavior

```console
PS C:\> Get-PSResource -Name Microsoft.PowerShell.SecretManagement, Microsoft.PowerShell.SecretStore

Name                                  Version Prerelease Repository Description
----                                  ------- ---------- ---------- -----------
Microsoft.PowerShell.SecretManagement 1.1.2.0            PSGallery  …

PS C:\> Install-PSResource Microsoft.PowerShell.SecretStore -TrustRepository
WARNING: Resource 'Microsoft.PowerShell.SecretManagement' with version '1.1.2.0' is already installed.  If you would like to reinstall, please run the cmdlet again with the -Reinstall parameter
```

### Error details

_No response_

### Environment data

```powershell
Name          Version
----          -------
PowerShellGet 3.0.14

Name                           Value
----                           -----
PSVersion                      7.2.5
PSEdition                      Core
GitCommitId                    7.2.5
OS                             Microsoft Windows 10.0.19043
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Visuals

_No response_

### PR DESCRIPTION
**Pull request by alerickson**
# PR Summary
When dependencies are being installed `Install-PSResource` emits warning about dependency already installed.  This PR changes the warning to be a verbose message for dependencies only.  If the package being installed is the parent package, a warning will still be emitted. 

## PR Context

Resolves #731 

## PR Checklist

- [x] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [x] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.
- **[Breaking changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)**
    - [x] None
    - **OR**
    - [ ] [Documentation needed]()
        - [ ] Issue filed: 
- **User-facing changes**
    - [x] Not Applicable
    - **OR**
    - [ ] [Documentation needed]()
        - [ ] Issue filed: 
- **Testing - New and feature**
    - [x] N/A or can only be tested interactively
    - **OR**
    - [ ] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
- **Tooling**
    - [x] I have considered the user experience from a tooling perspective and don't believe tooling will be impacted.
    - **OR**
    - [ ] I have considered the user experience from a tooling perspective and enumerated concerns in the summary.

### CODE REVIEW

File: src/code/InstallHelper.cs [hunk 1]
```diff
@@ -273,7 +273,7 @@ public InstallHelper(PSCmdlet cmdletPassedIn)
         }
 
         // Check if any of the pkg versions are already installed, if they are we'll remove them from the list of packages to install
-        private List<PSResourceInfo> FilterByInstalledPkgs(List<PSResourceInfo> packages)
+        private List<PSResourceInfo> FilterByInstalledPkgs(List<PSResourceInfo> packages, List<string> pkgNamesToInstall)
```
Comment (PaulHigin) [inline src/code/InstallHelper.cs]: There is no need to pass in `pkgNamesToInstall` since it is just a reference to `_pkgNamesToInstall` class field that is already accessible.

File: src/code/InstallHelper.cs [hunk 2]
```diff
@@ -310,12 +310,21 @@ private List<PSResourceInfo> FilterByInstalledPkgs(List<PSResourceInfo> packages
...
+                    }
+                    else {
+                        _cmdletPassedIn.WriteVerbose(
+                            string.Format("Dependency resource '{0}' with version '{1}' is already installed.  If you would like to reinstall, please run the cmdlet again with the -Reinstall parameter",
+                            pkg.Name,
+                            pkg.Version));
+                    }
 
+                    // Remove from tracking list of packages to install.
                     _pkgNamesToInstall.RemoveAll(x => x.Equals(pkg.Name, StringComparison.InvariantCultureIgnoreCase));
```
Comment (PaulHigin) [inline src/code/InstallHelper.cs]: It seems like `_pkgNamesToInstall` should be a HashSet, since it should not include any duplicates and will be much faster for tracking/removing packages as they are installed.  And we can get rid of these heavy handed LINQ calls.

File: src/code/InstallHelper.cs [hunk 3]
```diff
@@ -310,12 +310,21 @@ private List<PSResourceInfo> FilterByInstalledPkgs(List<PSResourceInfo> packages
                 }
                 else
                 {
-                    // Remove from tracking list of packages to install.
-                    _cmdletPassedIn.WriteWarning(
-                        string.Format("Resource '{0}' with version '{1}' is already installed.  If you would like to reinstall, please run the cmdlet again with the -Reinstall parameter",
-                        pkg.Name,
-                        pkg.Version));
+                    // Only write warning if the package is not a dependency package being installed.
+                    if (pkgNamesToInstall.Contains(pkg.Name)) {
```
Comment (PaulHigin) [inline src/code/InstallHelper.cs]: Since we have to differentiate between packages to install, and package dependency packages to install, maybe we should keep two objects to track them separately instead of mixing them into one bucket.

**Review by PaulHigin — CHANGES_REQUESTED** [review]

**Review by PaulHigin — APPROVED** [review]
