### PR TITLE
Fix -NoClobber bug in Install-PSResource

### LINKED ISSUE #676: -NoClobber is not working properly
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://www.powershellgallery.com/packages/PowerShellGet)
- [X] Search the existing issues.

### Steps to reproduce

image

### Expected behavior

```console
Should just install
```

### Actual behavior

```console
Gives a warning that the package is not found
```

### Error details

```console
Exception             :
    Type    : System.ArgumentException
    Message : Package 'Ships' with requested version range (, ) could not be installed as it was not
found in any registered repositories
    HResult : -2147024809
CategoryInfo          : ObjectNotFound: (:) [Install-PSResource], ArgumentException
FullyQualifiedErrorId : ResourceNotFoundError,Microsoft.PowerShell.PowerShellGet.Cmdlets.InstallPSResource
InvocationInfo        :
    MyCommand        : Install-PSResource
    ScriptLineNumber : 1
    OffsetInLine     : 1
    HistoryId        : 90
    Line             : Install-PSResource Ships -Repository PSGallery -NoClobber -Reinstall
    PositionMessage  : At line:1 char:1
                       + Install-PSResource Ships -Repository PSGallery -NoClobber -Reinstall
                       + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    InvocationName   : Install-PSResource
    CommandOrigin    : Internal
ScriptStackTrace      : at <ScriptBlock>, <No file>: line 1
PipelineIterationInfo :
```

### Environment data

```powershell
PS C:\demos> Get-Module PowerShellGet; $PSVersionTable

ModuleType Version    PreRelease Name                                ExportedCommands
---------- -------    ---------- ----                                ----------------
Binary     3.0.14     beta14     PowerShellGet                       {Find-PSResource, Get-PSResource, Ge…

Key   : PSVersion
Value : 7.2.4
Name  : PSVersion


Key   : PSEdition
Value : Core
Name  : PSEdition


Key   : GitCommitId
Value : 7.2.4
Name  : GitCommitId


Key   : OS
Value : Microsoft Windows 10.0.19043
Name  : OS


Key   : Platform
Value : Win32NT
Name  : Platform


Key   : PSCompatibleVersions
Value : {1.0, 2.0, 3.0, 4.0…}
Name  : PSCompatibleVersions


Key   : PSRemotingProtocolVersion
Value : 2.3
Name  : PSRemotingProtocolVersion


Key   : SerializationVersion
Value : 1.1.0.1
Name  : SerializationVersion


Key   : WSManStackVersion
Value : 3.0
Name  : WSManStackVersion
```

### Visuals

_No response_

### PR DESCRIPTION
**Pull request by alerickson**
# PR Summary
`-NoClobber` parameter for `Install-PSResource` was not working properly.  I made a small bug fix there and added an early out if the package to be installed does not have any cmdlets (ie there's no potential for clobbering).

## PR Context

Resolves #676 

## PR Checklist

- [ ] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [ ] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [ ] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [ ] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.
- **[Breaking changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)**
    - [ ] None
    - **OR**
    - [ ] [Documentation needed]()
        - [ ] Issue filed: 
- **User-facing changes**
    - [ ] Not Applicable
    - **OR**
    - [ ] [Documentation needed]()
        - [ ] Issue filed: 
- **Testing - New and feature**
    - [ ] N/A or can only be tested interactively
    - **OR**
    - [ ] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
- **Tooling**
    - [ ] I have considered the user experience from a tooling perspective and don't believe tooling will be impacted.
    - **OR**
    - [ ] I have considered the user experience from a tooling perspective and enumerated concerns in the summary.

### CODE REVIEW

File: src/code/InstallHelper.cs [hunk 1]
```diff
@@ -754,19 +754,24 @@ private bool DetectClobber(string pkgName, Hashtable parsedMetadataHashtable)
...
 
             foreach (var pkg in pkgsAlreadyInstalled)
             {
                 List<string> duplicateCmdlets = new List<string>();
                 List<string> duplicateCmds = new List<string>();
-                // See if any of the cmdlets or commands in the pkg we're trying to install exist within a package that's already installed
+                // See if any of the cmdlets or commands in the pkg we're trying to install exist within a package that's already installed.
                 if (pkg.Includes.Cmdlet != null && pkg.Includes.Cmdlet.Any())
                 {
                     duplicateCmdlets = listOfCmdlets.Where(cmdlet => pkg.Includes.Cmdlet.Contains(cmdlet)).ToList();
```
Comment (PaulHigin) [inline src/code/InstallHelper.cs]: Please remove unneeded white space here and below.

File: src/code/InstallHelper.cs [hunk 2]
```diff
@@ -754,19 +754,24 @@ private bool DetectClobber(string pkgName, Hashtable parsedMetadataHashtable)
...
-            // user parsed metadata hash
+            // User parsed metadata hash.
             List<string> listOfCmdlets = new List<string>();
             foreach (var cmdletName in parsedMetadataHashtable["CmdletsToExport"] as object[])
             {
                 listOfCmdlets.Add(cmdletName as string);
+            }
 
+            // Exit early if there's no cmdlets in the package to be installed.
+            if (listOfCmdlets.Count == 0)
```
Comment (PaulHigin) [inline src/code/InstallHelper.cs]: `listOfCmdlets` should be a HashSet (with case insensitive compare) instead of a List, for more efficient searches.
Also, I think this method can do an early return on first command name collision found.  The user just needs to know there is at least one name collision with an existing installed module, and then decide if they are going to allow the install or not.  This would make the detection process much faster.

**Review by PaulHigin — CHANGES_REQUESTED** [review]

File: src/code/InstallHelper.cs (hunk 2 above)
Comment (alerickson) [reply src/code/InstallHelper.cs]: In v2 we display every cmdlet that causes a clobber (so the user knows what exactly they're potentially going to be clobbering).  We don't clobber by default anymore, so if a user opts-in to check clobbering it might be beneficial to have the list of cmdlets that will be clobbered.

Comment (alerickson) [reply src/code/InstallHelper.cs]: I've added the early out in the latest commit.

**Review by PaulHigin — APPROVED** [review]
