### PR TITLE
Bug fix for RequireLicenseAcceptance in Publish-PSResource

### LINKED ISSUE #1109: Error with 'requireLicenseAcceptance' element when publishing
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://www.powershellgallery.com/packages/PowerShellGet)
- [X] Search the existing issues.

### Steps to reproduce

```

Publish-PSResource -Path C:\Users\adity\Documents\PowerShell\Modules\Microsoft.PowerShell.WhatsNew\0.4.0\Microsoft.PowerShell.WhatsNew.psd1 -Repository local
Publish-PSResource: Unexpected error packing into .nupkg: 'The '[http://schemas.microsoft.com/packaging/2011/08/nuspec.xsd:requireLicenseAcceptance'](http://schemas.microsoft.com/packaging/2011/08/nuspec.xsd:requireLicenseAcceptance%27) element is invalid - The value 'False' is invalid according to its datatype '[http://www.w3.org/2001/XMLSchema:boolean'](http://www.w3.org/2001/XMLSchema:boolean%27) - The string 'False' is not a valid Boolean value. This validation error occurred in a 'requireLicenseAcceptance' element.'.

```

### Expected behavior

```console
N/A
```

### Actual behavior

```console
N/A
```

### Error details

_No response_

### Environment data

```powershell
N/A
```

### Visuals

_No response_

### PR DESCRIPTION
**Pull request by alerickson**
# PR Summary
`RequireLicenseAcceptance` value is a string that needs to be lowercase in order for it to later be converted into a boolean value correctly.  Previously this value was converted to a string and that value was later converted to a boolean.  For example, parsing 'False' threw the following error:

``` powershell
 The value 'False' is invalid according to its datatype '[http://www.w3.org/2001/XMLSchema:boolean'](http://www.w3.org/2001/XMLSchema:boolean%27) - The string 'False' is not a valid Boolean value. This validation error occurred in a 'requireLicenseAcceptance' element.'
```
but the value 'false' threw no error. 

This PR ensures the string value is always lowercase .

## PR Context
Resolves #1109 

## PR Checklist

- [x] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [x] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.
- **[Breaking changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)**
    - [x] None
    - **OR**
    - [ ] [Documentation needed]()
        - [ ] Issue filed: 
- **User-facing changes**
    - [x] Not Applicable
    - **OR**
    - [ ] [Documentation needed]()
        - [ ] Issue filed: 
- **Testing - New and feature**
    - [x] N/A or can only be tested interactively
    - **OR**
    - [ ] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
- **Tooling**
    - [x] I have considered the user experience from a tooling perspective and don't believe tooling will be impacted.
    - **OR**
    - [ ] I have considered the user experience from a tooling perspective and enumerated concerns in the summary.

### CODE REVIEW

File: src/code/PublishPSResource.cs [hunk 1]
```diff
@@ -575,7 +575,8 @@ protected override void EndProcessing()
                         }
 
                         // defaults to false
-                        string requireLicenseAcceptance = psData.ContainsKey("requirelicenseacceptance") ? psData["requirelicenseacceptance"].ToString() : "false";
+                        // boolean value needs to be a lowercase string for it to be correctly parsed
```
Comment (anamnavi) [inline src/code/PublishPSResource.cs]: Just a nitpick in case this sounds clearer
```suggestion
                        // Value for requireAcceptLicense key needs to be a lowercase string representation of the boolean for it to be correctly parsed from psData file.

```

**Review by anamnavi — APPROVED** [review]
LGTM, just a nitpick about wording

File: src/code/PublishPSResource.cs (hunk 1 above)
Comment (anamnavi) [reply src/code/PublishPSResource.cs]: Or what you have in the PR description sounds a bit clearer as a requirement too :)

"RequireLicenseAcceptance value is a string that needs to be lowercase in order for it to later be converted into a boolean value correctly"
