### PR TITLE
Use runspace to acquire version to avoid CLM issues

### LINKED ISSUE #1676: WDAC blocking PSResourceGet because of Dot sourcing in Find-PSResource
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://www.powershellgallery.com/packages/Microsoft.PowerShell.PSResourceGet)
- [X] Search the existing issues.

### Steps to reproduce

PowerShell 7.3.4 and 5.1
PSResourceGet 
Setup PSResourceRepository
Use Find-PSResource command

### Expected behavior

```console
Finds resource
```

### Actual behavior

```console
Throws error
```

### Error details

```console
Find-PSResource: The type initializer for 'Microsoft.PowerShell.PSResourceGet.Cmdlets.UserAgentInfo' threw an exception.

ErrorRecord                 : Cannot dot-source this command because it was defined in a different language mode. To invoke this command without importing its contents, omit the '.' operator.
WasThrownFromThrowStatement : False
TargetSite                  : System.Collections.ObjectModel.Collection`1[System.Management.Automation.PSObject] Invoke(System.Collections.IEnumerable)
Message                     : Cannot dot-source this command because it was defined in a different language mode. To invoke this command without importing its contents, omit the '.' operator.
Data                        : {}
InnerException              : System.NotSupportedException: Cannot dot-source this command because it was defined in a different language mode. To invoke this command without importing its contents, omit the '.' operator.
HelpLink                    : 
Source                      : System.Management.Automation
HResult                     : -2146233087
StackTrace                  :    at System.Management.Automation.Runspaces.PipelineBase.Invoke(IEnumerable input)
                                 at System.Management.Automation.PowerShell.Worker.ConstructPipelineAndDoWork(Runspace rs, Boolean performSyncInvoke)
                                 at System.Management.Automation.PowerShell.CoreInvokeHelper[TInput,TOutput](PSDataCollection`1 input, PSDataCollection`1 output, PSInvocationSettings settings)
                                 at System.Management.Automation.PowerShell.CoreInvoke[TInput,TOutput](PSDataCollection`1 input, PSDataCollection`1 output, PSInvocationSettings settings)
                                 at System.Management.Automation.PowerShell.Invoke[T]()
                                 at Microsoft.PowerShell.PSResourceGet.Cmdlets.UserAgentInfo..cctor()

Get-Variable: Cannot find a variable with the name 'PackageManagementProvider'.

Get-Variable: Cannot find a variable with the name 'SourceLocation'.

Get-Variable: Cannot find a variable with the name 'PackageManagementProvider'.

Get-Variable: Cannot find a variable with the name 'SourceLocation'.
```

### Environment data

```powershell
Directory: C:\program files\powershell\7\Modules
 
ModuleType Version    PreRelease Name                                PSEdition ExportedCommands
---------- -------    ---------- ----                                --------- ----------------
Binary     1.0.4.1               Microsoft.PowerShell.PSResourceGet  Core,Desk {Find-PSResource, Get-InstalledPSResourc…
 
 
Name                           Value
----                           -----
PSVersion                      7.4.3
PSEdition                      Core
GitCommitId                    7.4.3
OS                             Microsoft Windows 10.0.22631
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Visuals

n/A

### PR DESCRIPTION
**Pull request by adityapatwardhan**
# PR Summary

This pull request introduces a new helper method to retrieve the user agent string and simplifies how the PowerShell version is determined for user agent construction. The changes improve maintainability and reliability by reducing the use of PowerShell scripts and exposing a direct way to access the user agent string.

User agent string handling:

* Added a new static method `GetUserString` to `InternalHooks` that returns the user agent string via `UserAgentInfo.UserAgentString()`.

PowerShell version detection:

* Updated the static constructor of `UserAgentInfo` to retrieve the PowerShell version using `Runspace.DefaultRunspace.Version` instead of executing a PowerShell script, simplifying and making the version detection more robust.

## PR Context

Fixes #1676

## PR Checklist

- [ ] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [ ] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [ ] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [ ] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.
- **[Breaking changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)**
    - [ ] None
    - **OR**
    - [ ] [Documentation needed]()
        - [ ] Issue filed: 
- **User-facing changes**
    - [ ] Not Applicable
    - **OR**
    - [ ] [Documentation needed]()
        - [ ] Issue filed: 
- **Testing - New and feature**
    - [ ] N/A or can only be tested interactively
    - **OR**
    - [ ] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
- **Tooling**
    - [ ] I have considered the user experience from a tooling perspective and don't believe tooling will be impacted.
    - **OR**
    - [ ] I have considered the user experience from a tooling perspective and enumerated concerns in the summary.

### CODE REVIEW

File: src/code/ServerFactory.cs [hunk 1]
```diff
@@ -12,11 +12,7 @@ internal static class UserAgentInfo
     {
         static UserAgentInfo()
         {
-            using (System.Management.Automation.PowerShell ps = System.Management.Automation.PowerShell.Create(RunspaceMode.CurrentRunspace))
-            {
-                _psVersion = ps.AddScript("$PSVersionTable").Invoke<Hashtable>()[0]["PSVersion"].ToString();
-            }
-
+            _psVersion = System.Management.Automation.Runspaces.Runspace.DefaultRunspace.Version.ToString();
```
Comment (anamnavi) [inline src/code/ServerFactory.cs:15]: do we potentially need the null coalescing operator for any of these properties?

**Review by anamnavi — APPROVED** [review]
LGTM, left a comment
