### PR TITLE
Bug fix for Publish-PSResource deleting a temp dir that contains a readonly file

### LINKED ISSUE #526: publishing with Publish-PSResource results in an error when cleaning up files in .../AppData/Local/Temp
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://www.powershellgallery.com/packages/PowerShellGet)
- [X] Search the existing issues.

### Steps to reproduce

I just tried publishing a module to our MyGet Repository like normal `Publish-PSResource -Path <path> -ApiKey <apikey> -Repository MyGetRepo -Verbose`

It spits out some verbose output and successfully publishes the package as it should, but spits out 
```
Publish-PSResource : Access to the path 'pack-d3e381d11619a1adddda03baa0a25bf84f875077.idx' is denied.
At line:1 char:1
+ Publish-PSResource -Path <path> -ApiKey <apikey> ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Publish-PSResource], UnauthorizedAccessException
    + FullyQualifiedErrorId : System.UnauthorizedAccessException,Microsoft.PowerShell.PowerShellGet.Cmdlets.PublishPSResource
```

I have double-checked in my filesystem as well as with our sys admin that I do have the correct permissions applied, but it's still having issues.

Just for extra verbosity on my part here is the verbose output from running the command
```
VERBOSE: Performing the operation "Publish-PSResource" on target "Publish resource 'C:\GitHub\<modulename>' from the machine.".
VERBOSE: Creating new nuspec file.
VERBOSE: The newly created nuspec is: C:\Users\<me>\AppData\Local\Temp\de27e325-239e-4383-b343-1e76f76b0823\<modulename>.nuspec
VERBOSE: Successfully packed the resource into a .nupkg
VERBOSE: Successfully published the resource to <url>
VERBOSE: Deleting temporary directory 'C:\Users\<me>\AppData\Local\Temp\de27e325-239e-4383-b343-1e76f76b0823'
Publish-PSResource : Access to the path 'pack-d3e381d11619a1adddda03baa0a25bf84f875077.idx' is denied.
At line:1 char:1
+ Publish-PSResource -Path <path> -ApiKey <apikey> ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Publish-PSResource], UnauthorizedAccessException
    + FullyQualifiedErrorId : System.UnauthorizedAccessException,Microsoft.PowerShell.PowerShellGet.Cmdlets.PublishPSResource
```

### Expected behavior

```console
I expect that it will delete the entire \Temp\<guid> directory and all if its contents.
```

### Actual behavior

```console
It fails to delete `\Temp\<guid>\.git\objects\pack\pack-d3e381d11619a1adddda03baa0a25bf84f875077.idx` and `\Temp\<guid>\.git\objects\pack\pack-d3e381d11619a1adddda03baa0a25bf84f875077.pack`.
```

### Error details

```console
Publish-PSResource : Access to the path 'pack-d3e381d11619a1adddda03baa0a25bf84f875077.idx' is denied.
At line:1 char:1
+ Publish-PSResource -Path C:\GitHub\PowershellModuleUpdater -ApiKey '8 ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Publish-PSResource], UnauthorizedAccessException
    + FullyQualifiedErrorId : System.UnauthorizedAccessException,Microsoft.PowerShell.PowerShellGet.Cmdlets.PublishPSResource
```

### Environment data

```powershell
Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Binary     3.0.11     powershellget                       {Find-PSResource, Get-InstalledPSResource, Get-PSResourceRepository, Install-PSResource...}
Script     2.2.5      PowerShellGet                       {Find-Command, Find-DscResource, Find-Module, Find-RoleCapability...}

Key   : PSVersion
Value : 5.1.22000.282
Name  : PSVersion
Key   : CLRVersion
Value : 4.0.30319.42000
Name  : CLRVersion


Key   : WSManStackVersion
Value : 3.0
Name  : WSManStackVersion


Key   : PSRemotingProtocolVersion
Value : 2.3
Name  : PSRemotingProtocolVersion


Key   : SerializationVersion
Value : 1.1.0.1
Name  : SerializationVersion
```

### Visuals

_No response_

### PR DESCRIPTION
**Pull request by alerickson**
# PR Summary
Publish-PSResource moves a module it is going to publish into a temp directory and then after publishing attempts to delete the temp directory it created. Occasionally there are files that have permissions that do not allow PSGet to delete, thus it's not able to fully delete the temp directory it created.  This PR attempts to set the file permissions when a file throws an access denied error. 

## PR Context
Resolves #526 

## PR Checklist

- [x] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [x] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.
- **[Breaking changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)**
    - [x] None
    - **OR**
    - [ ] [Documentation needed]()
        - [ ] Issue filed: 
- **User-facing changes**
    - [x] Not Applicable
    - **OR**
    - [ ] [Documentation needed]()
        - [ ] Issue filed: 
- **Testing - New and feature**
    - [ ] N/A or can only be tested interactively
    - **OR**
    - [x] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
- **Tooling**
    - [x] I have considered the user experience from a tooling perspective and don't believe tooling will be impacted.
    - **OR**
    - [ ] I have considered the user experience from a tooling perspective and enumerated concerns in the summary.

### CODE REVIEW

File: src/code/PublishPSResource.cs [hunk 1]
```diff
@@ -413,7 +413,23 @@ protected override void ProcessRecord()
...
-                Directory.Delete(outputDir, recursive:true);
+
+                try
+                {
+                    Directory.Delete(outputDir, recursive: true);
+                }
+                catch (UnauthorizedAccessException)
+                {
+                    // If an exception was thrown due to an access denied exception, attempt to change file attributes to normal
+                    string[] filesLeftToDelete = Directory.GetFiles(outputDir);
```
Comment (PaulHigin) [inline src/code/PublishPSResource.cs]: This won't get files from subdirectories.  But we should always be using the `Utils.DeleteDirectory()` anyway. 
https://github.com/PowerShell/PowerShellGet/blob/4632fa59f32110e743910a3ac05c5f8f669cbfee/src/code/Utils.cs#L568

I think we should add code there to ensure each file has the right attributes for deletion.  Instead of try/catch we should first check file attribute and ensure it is not ReadOnly.

**Review by PaulHigin — CHANGES_REQUESTED** [review]

**Review by anamnavi — APPROVED** [review]

File: src/code/Utils.cs [hunk 2]
```diff
@@ -565,6 +565,12 @@ public static void DeleteDirectory(string dirPath)
         {
             foreach (var dirFilePath in Directory.GetFiles(dirPath))
             {
+                FileAttributes attribute = File.GetAttributes(dirFilePath);
```
Comment (PaulHigin) [inline src/code/Utils.cs]: Since the `FileAttributes` enumeration is a bitfield we need to use bitwise operators.  Also I think we just need to check for the 'ReadOnly' flag:
```csharp
var attributes = File.GetAttributes(dirFilePath);
if (attributes.HasFlag(FileAttributes.ReadOnly))
{
    // Remove 'ReadOnly' attribute so the file can be deleted.
    attributes &= ~FileAttributes.ReadOnly;
    File.SetAttributes(dirFilePath, attributes);
}

File.Delete(dirFilePath);

```

**Review by PaulHigin — CHANGES_REQUESTED** [review]

**Review by PaulHigin — APPROVED** [review]
One small change, you could save the file attributes in a variable and avoid calling GetAttributes() twice.
