### PR TITLE
Fix JFrog's NuGet Artifactory (v2 endpoint) bug

### LINKED ISSUE #1416: Artifactory v2 feed does not work
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://www.powershellgallery.com/packages/Microsoft.PowerShell.PSResourceGet)
- [X] Search the existing issues.

### Steps to reproduce

If you register a NuGet Artifactory repository it defaults to unknown ApiVersion and if you set it manually to v2 cmdlets will not work.

```powershell
Name           : psgallery-remote
Uri            : https://<server>/api/nuget/powershell-nuget-public-remote
Trusted        : True
Priority       : 50
CredentialInfo :
ApiVersion     : v2


find-pSResource anypackage -Repository psgallery-remote

Name Version Prerelease Repository       Description
---- ------- ---------- ----------       -----------
     0.5.1              psgallery-remote Use various package managers with a single set of commands.

save-PSResource anypackage -Repository psgallery-remote -Path ~
Save-PSResource: Object reference not set to an instance of an object.
```

### Expected behavior

```console
v2 Artifactory feed works
```

### Actual behavior

```console
Various errors like missing package name in find and failing to save.
```

### Error details

```console
Exception             :
    Type       : System.NullReferenceException
    TargetSite :
        Name          : HttpRequestCallForContent
        DeclaringType : Microsoft.PowerShell.PSResourceGet.Cmdlets.V2ServerAPICalls,
Microsoft.PowerShell.PSResourceGet, Version=0.9.0.0, Culture=neutral, PublicKeyToken=null
        MemberType    : Method
        Module        : Microsoft.PowerShell.PSResourceGet.dll
    Message    : Object reference not set to an instance of an object.
    Source     : Microsoft.PowerShell.PSResourceGet
    HResult    : -2147467261
    StackTrace :
   at Microsoft.PowerShell.PSResourceGet.Cmdlets.V2ServerAPICalls.HttpRequestCallForContent(String requestUrlV2,
ErrorRecord& errRecord)
   at Microsoft.PowerShell.PSResourceGet.Cmdlets.V2ServerAPICalls.InstallName(String packageName, Boolean
includePrerelease, ErrorRecord& errRecord)
   at Microsoft.PowerShell.PSResourceGet.Cmdlets.InstallHelper.InstallPackage(VersionType searchVersionType,
NuGetVersion specificVersion, VersionRange versionRange, String pkgNameToInstall, PSRepositoryInfo repository,
ServerApiCall currentServer, ResponseUtil currentResponseUtil, String tempInstallPath, Hashtable packagesHash,
ErrorRecord& errRecord)
   at Microsoft.PowerShell.PSResourceGet.Cmdlets.InstallHelper.InstallPackages(String[] pkgNamesToInstall,
PSRepositoryInfo repository, ServerApiCall currentServer, ResponseUtil currentResponseUtil, ScopeType scope, Boolean
skipDependencyCheck, FindHelper findHelper)
   at Microsoft.PowerShell.PSResourceGet.Cmdlets.InstallHelper.ProcessRepositories(String[] repository, Boolean
trustRepository, Boolean skipDependencyCheck, ScopeType scope)
   at Microsoft.PowerShell.PSResourceGet.Cmdlets.InstallHelper.BeginInstallPackages(String[] names, VersionRange
versionRange, NuGetVersion nugetVersion, VersionType versionType, String versionString, Boolean prerelease, String[]
repository, Boolean acceptLicense, Boolean quiet, Boolean reinstall, Boolean force, Boolean trustRepository, Boolean
noClobber, Boolean asNupkg, Boolean includeXml, Boolean skipDependencyCheck, Boolean authenticodeCheck, Boolean
savePkg, List`1 pathsToInstallPkg, Nullable`1 scope, String tmpPath, HashSet`1 pkgsInstalled)
   at Microsoft.PowerShell.PSResourceGet.Cmdlets.SavePSResource.ProcessSaveHelper(String[] pkgNames, String
pkgVersion, Boolean pkgPrerelease, String[] pkgRepository)
   at Microsoft.PowerShell.PSResourceGet.Cmdlets.SavePSResource.ProcessRecord()
   at System.Management.Automation.CommandProcessor.ProcessRecord()
CategoryInfo          : NotSpecified: (:) [Save-PSResource], NullReferenceException
FullyQualifiedErrorId : System.NullReferenceException,Microsoft.PowerShell.PSResourceGet.Cmdlets.SavePSResource
InvocationInfo        :
    MyCommand        : Save-PSResource
    ScriptLineNumber : 1
    OffsetInLine     : 1
    HistoryId        : 7
    Line             : save-PSResource anypackage -Repository psgallery-remote -Path ~
    Statement        : save-PSResource anypackage -Repository psgallery-remote -Path ~
    PositionMessage  : At line:1 char:1
                       + save-PSResource anypackage -Repository psgallery-remote -Path ~
                       + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    InvocationName   : save-PSResource
    CommandOrigin    : Internal
ScriptStackTrace      : at <ScriptBlock>, <No file>: line 1
```

### Environment data

```powershell
7.4-preview5
```

### Visuals

_No response_

### PR DESCRIPTION
**Pull request by alerickson**
# PR Summary
Fixes a few bugs related to the v2 endpoint for JFrog's NuGet Artifactory repositories:

*  `Find` was not able to find a package in a repo.  It previously errored out saying package could not be found.  This was due to the request query being created adding the filter `"Id eq '<packageName>'"` (eg: `https://test.jfrog.io/artifactory/api/nuget/nuget/FindPackagesById()?id='<packageName>'&$filter=IsLatestVersion and Id eq '<packageName>'`), however the server have information for an 'Id' property.  What other repositories call `Id` Jfrog calls `Title`, however filtering on title returns a 405, so I've removed the filter altogether for JFrog repos.  The filter cannot be removed for other v2 repos such as the PSGallery because `FindPackagesById()?id='\<packageName>'` fuzzy matches, so it needs to be further filtered for exact matching.

* Because JFrog has no `Id` property, when the package is returned PSResourceGet could not find the name of the package and returned whitespace instead of the proper package name.  When parsing the response xml, PSResourceGet now looks for 'Title' as well as 'Id' for the package name.

* Exceptions thrown from `SendV2RequestForContentAsync` were not properly getting caught and would cause null pointer exceptions to later get thrown. These request call exceptions (specifically related to v2 installation) are now properly caught and thrown.

*  `string.IsNullOrEmpty(content.ToString()))` was not validating that content was not null before using `.ToString()` method.  Simple null check was added here.

* Previously requests to install a package from JFrog looked like: `https://test.jfrog.io/artifactory/api/nuget/nuget/package/<packageName>`. However, the proper request should look like: `https://test.jfrog.io/artifactory/api/nuget/nuget/Download/<packageName>/<packageVersion>`.  JFrog needs the package version to install a package, it won't just install the latest.  `InstallName` now takes a `packageVersion` parameter so that it can form the proper query. 

## PR Context

Resolves #1416  

## PR Checklist

- [x] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [x] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.
- **[Breaking changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)**
    - [x] None
    - **OR**
    - [ ] [Documentation needed]()
        - [ ] Issue filed: 
- **User-facing changes**
    - [x] Not Applicable
    - **OR**
    - [ ] [Documentation needed]()
        - [ ] Issue filed: 
- **Testing - New and feature**
    - [x] N/A or can only be tested interactively
    - **OR**
    - [ ] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
- **Tooling**
    - [x] I have considered the user experience from a tooling perspective and don't believe tooling will be impacted.
    - **OR**
    - [ ] I have considered the user experience from a tooling perspective and enumerated concerns in the summary.

### CODE REVIEW

File: src/code/IServerAPICalls.cs [hunk 1]
```diff
@@ -83,7 +83,7 @@ public interface IServerAPICalls
     /// Name: no wildcard support.
     /// Examples: Install "PowerShellGet"
     /// </summary>
-    Stream InstallName(string packageName, bool includePrerelease, out ErrorRecord errRecord);
```
Comment (anamnavi) [inline src/code/IServerAPICalls.cs:86]: While I understand the reasoning you provided in the issue description for why you're letting `InstallName()` take a `packageVersion` parameter, and how JFrog can't do InstallName(), I think what may be better for the sake of the interface server APIs is if we don't turn `InstallName()` into `InstallVersion()`. That's effectively 2 methods doing the same install behavior and may seem like confusing or redundant behavior to future API implementers.. Perhaps instead in the FindHelper level we can determine from the current server instance that it is a JFrog V2 repository and then call `InstallVersion()`.

Arguably, since we currently call FindHelper before InstallHelper we will always know the package version and therefore always call InstallName..but we had left it as separate APIs so that if in the future we implement doing Install without Find we already have separate code.

**Review by anamnavi — CHANGES_REQUESTED** [review]
PR looks great and thanks for the thorough explanation of findings! Left a thought about overall design wrt to the server APIs.

File: src/code/IServerAPICalls.cs (hunk 1 above)
Comment (anamnavi) [reply src/code/IServerAPICalls.cs:86]: or since we effectively do InstallVersion() instead of InstallName() for ADO V2 feed as well, perhaps in the `ServerApiCall` class we have an overridden method called `InstallPackage(pkgName, pkgVersion, other params)` that determines the situation and calls `InstallName()` or InstallVersion()` that would now only be private methods.

Comment (alerickson) [reply src/code/IServerAPICalls.cs:86]: > or since we effectively do InstallVersion() instead of InstallName() for ADO V2 feed as well, perhaps in the ServerApiCall class we have an overridden method called InstallPackage(pkgName, pkgVersion, other params) that determines the situation and calls InstallName() or InstallVersion()` that would now only be private methods.

I like this idea a lot.  Let me refactor and add this

File: src/code/V3ServerAPICalls.cs [hunk 2]
```diff
@@ -284,38 +284,24 @@ public override FindResults FindVersionWithTag(string packageName, string versio
...
-        ///           Install "Newtonsoft.json" -Version "2.5.0-beta"
+        /// Examples: Install "PowerShellGet"
+        ///           Install "PowerShellGet" -Version "3.0.0"
         /// </summary>
-        public override Stream InstallVersion(string packageName, string version, out ErrorRecord errRecord)
+        public override Stream InstallPackage(string packageName, string packageVersion, bool includePrerelease, out ErrorRecord errRecord)
         {
-            _cmdletPassedIn.WriteDebug("In V3ServerAPICalls::InstallVersion()");
-            if (!NuGetVersion.TryParse(version, out NuGetVersion requiredVersion))
+            Stream results = new MemoryStream();
```
Comment (anamnavi) [inline src/code/V3ServerAPICalls.cs:294]: Perhaps we can add a debug statement for this method, not blocking.
```suggestion
            Stream results = new MemoryStream();
            _cmdletPassedIn.WriteDebug("In V3ServerAPICalls::InstallPackage()");
```

**Review by anamnavi — APPROVED** [review]
LGTM, thanks for making this change!
