### PR TITLE
Bug fix for parsing required modules when publishing

### LINKED ISSUE #1305: Publish-PSResource fails with ModuleSpecification and prerelease module
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://www.powershellgallery.com/packages/PSResourceGet)
- [X] Search the existing issues.

### Steps to reproduce

Trying to publish https://github.com/anypackage/psresourceget to a local repository that already PSResourceGet there.

```
RequiredModules = @(
        @{ ModuleName = 'AnyPackage'; ModuleVersion = '0.5.1' },
        'Microsoft.PowerShell.PSResourceGet')
```

### Expected behavior

```console
# publish successfully
```

### Actual behavior

```console
Publish-PSResource -Repository test -Path ~\Documents\PowerShell\Modules\AnyPackage.PSResourceGet -Verbose
VERBOSE: Performing the operation "Publish-PSResource" on target "Publish resource 'C:\Users\Thomas\Documents\PowerShell\Modules\AnyPackage.PSResourceGet' from the machine".
VERBOSE: Creating new nuspec file.
VERBOSE: The newly created nuspec is: C:\Users\Thomas\AppData\Local\Temp\6a50c3a5-07fd-4859-98d3-cb33d1503c18\AnyPackage.PSResourceGet.nuspec
VERBOSE: Searching in repository test
VERBOSE: Searching in repository test
Publish-PSResource: Dependency 'System.Collections.Hashtable' was not found in repository 'test'.  Make sure the dependency is published to the repository before publishing this module.
VERBOSE: Deleting temporary directory 'C:\Users\Thomas\AppData\Local\Temp\6a50c3a5-07fd-4859-98d3-cb33d1503c18'
```

### Error details

```console
Exception             :
    Type    : System.ArgumentException
    Message : Dependency 'System.Collections.Hashtable' was not found in repository 'test'.  Make sure the dependency
is published to the repository before publishing this module.
    HResult : -2147024809
TargetObject          : Microsoft.PowerShell.PSResourceGet.Cmdlets.PublishPSResource
CategoryInfo          : ObjectNotFound: (Microsoft.PowerShel…s.PublishPSResource:PublishPSResource)
[Publish-PSResource], ArgumentException
FullyQualifiedErrorId : DependencyNotFound,Microsoft.PowerShell.PSResourceGet.Cmdlets.PublishPSResource
InvocationInfo        :
    MyCommand        : Publish-PSResource
    ScriptLineNumber : 1
    OffsetInLine     : 1
    HistoryId        : 32
    Line             : Publish-PSResource -Repository test -Path
~\Documents\PowerShell\Modules\AnyPackage.PSResourceGet -Verbose
    Statement        : Publish-PSResource -Repository test -Path
~\Documents\PowerShell\Modules\AnyPackage.PSResourceGet -Verbose
    PositionMessage  : At line:1 char:1
                       + Publish-PSResource -Repository test -Path ~\Documents\PowerShell\Modu …
                       + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    InvocationName   : Publish-PSResource
    CommandOrigin    : Internal
ScriptStackTrace      : at <ScriptBlock>, <No file>: line 1
PipelineIterationInfo :
```

### Environment data

```powershell
beta23
```

### Visuals

_No response_

### PR DESCRIPTION
**Pull request by alerickson**
# PR Summary
RequiredModules were not being parsed correctly from a module manifest during publish time, thus when, for example, RequiredModules contained both a Hashtable and a string, the hashtable would be parsed as a string and incorrectly assume the module name was "System.Collections.Hashtable".  This PR loops through every element of RequiredModules and tries to parse each object individually instead of assuming that all types within RequiredModules are the same and attempting to parse the object as a whole. 

## PR Context
Resolves #1305 

## PR Checklist

- [ ] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [ ] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [ ] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [ ] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.
- **[Breaking changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)**
    - [ ] None
    - **OR**
    - [ ] [Documentation needed]()
        - [ ] Issue filed: 
- **User-facing changes**
    - [ ] Not Applicable
    - **OR**
    - [ ] [Documentation needed]()
        - [ ] Issue filed: 
- **Testing - New and feature**
    - [ ] N/A or can only be tested interactively
    - **OR**
    - [ ] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
- **Tooling**
    - [ ] I have considered the user experience from a tooling perspective and don't believe tooling will be impacted.
    - **OR**
    - [ ] I have considered the user experience from a tooling perspective and enumerated concerns in the summary.

### CODE REVIEW

File: src/code/PublishPSResource.cs [hunk 1]
```diff
@@ -832,7 +836,7 @@ private bool CheckDependenciesExist(Hashtable dependencies, string repositoryNam
             foreach (var dependency in dependencies.Keys)
```
Comment (adityapatwardhan) [inline src/code/PublishPSResource.cs]: Never enumerate keys of a Hashtable. That causes rehashing and is bad for performance. Use should iterate like here: https://learn.microsoft.com/en-us/dotnet/api/system.collections.dictionaryentry?view=net-7.0

File: src/code/PublishPSResource.cs [hunk 2]
```diff
@@ -790,23 +790,27 @@ private Hashtable ParseRequiredModules(Hashtable parsedMetadataHash)
...
             {
-                // instead of returning an array of hashtables,
-                // loop through the array and add each element of
-                foreach (Hashtable hash in moduleList)
+                if (LanguagePrimitives.TryConvertTo<Hashtable>(reqModule, out Hashtable moduleHash))
                 {
-                    dependenciesHash.Add(hash["ModuleName"], hash["ModuleVersion"]);
+                    if (moduleHash.ContainsKey("ModuleVersion"))
+                    {
+                        dependenciesHash.Add(moduleHash["ModuleName"], moduleHash["ModuleVersion"]);
```
Comment (adityapatwardhan) [inline src/code/PublishPSResource.cs]: `moduleHash["ModuleName"]` is looked up multiple times. Better to store it in local variable and re-use the value

**Review by adityapatwardhan — CHANGES_REQUESTED** [review]

File: src/code/PublishPSResource.cs (hunk 2 above)
Comment (alerickson) [reply src/code/PublishPSResource.cs]: Actually it's only looked up once since it's an if/elseif/else condition. If it's guaranteed to only look up once per iteration I wasn't sure if it's better to have a variable or the look up.

Comment (adityapatwardhan) [reply src/code/PublishPSResource.cs]: Yes, i see

**Review by adityapatwardhan — APPROVED** [review]
