### PR TITLE
check if repo has scheme temp, also default ApiVersion is unknown

### LINKED ISSUE #938: *-PSResourceRepository -Uri does not accept PSPath
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://www.powershellgallery.com/packages/PowerShellGet)
- [X] Search the existing issues.

### Steps to reproduce

If you try to Register/Set a resource repository the `-Uri` parameter does not accept PSPath for example: `Temp:\repo`. I'd assume that Unix style paths also experience the same kind of issue.

Please add an argument transformation attribute to change the PS provider path to the full file system path that `-Uri` expects.

### Expected behavior

```console
Register-PSResourceRepository -Name Test -Uri 'Temp:\repo'
# works
```

### Actual behavior

```console
Register-PSResourceRepository -Name test -Uri 'Temp:\repo'
Register-PSResourceRepository: Invalid Uri, must be one of the following Uri schemes: HTTPS, HTTP, FTP, File Based
```

### Error details

_No response_

### Environment data

```powershell
Name          Version
----          -------
PowerShellGet 3.0.19

Name                           Value
----                           -----
PSVersion                      7.3.2
PSEdition                      Core
GitCommitId                    7.3.2
OS                             Microsoft Windows 10.0.19044
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Visuals

_No response_

### LINKED ISSUE #1279: Null reference exception when installing module internally hosted on Nexus Repository
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://www.powershellgallery.com/packages/PSResourceGet)
- [X] Search the existing issues.

### Steps to reproduce

Using Nexus Repository as an internal PowerShell module source.

```powershell
Install-Module -Name Microsoft.PowerShell.PSResourceGet -Repository PSGallery -AllowPrerelease -Scope CurrentUser

Write-Information "Installing secret management stuff using PowerShellGet"
Install-Module -Name Microsoft.PowerShell.SecretManagement,Microsoft.PowerShell.SecretStore -Repository PSGallery -Scope CurrentUser

$Name = "shared-powershell-hosted-dev"
$Location = https://nexus.MyCompany.com/repository/shared-powershell-hosted-dev/
$NexusUserCode = "blah"
$VaultName = "PSRepos"
$Credential = Get-Credential -Message "Enter your Nexus Repo pass code generated from the UI" -UserName $NexusUserCode

Write-Information "Create a new vault for all the PSRepos' secrets"
if (-not (Get-SecretVault | Where-Object -Property Name -eq $VaultName))
{
    Register-SecretVault -Name $VaultName -ModuleName Microsoft.PowerShell.SecretStore
}

Write-Information "Just set the secret to the whole vault to the same password, for simplicity"
Set-SecretStorePassword -NewPassword $Credential.Password -Password $Credential.Password
Unlock-SecretStore -Password $Credential.Password

Write-Information "Create a new secret with the same name as the repository, with type of PSCredential"
Set-Secret -Name $Name -Vault $VaultName -Secret $Credential

Write-Information "Register the package repository"
if (-not (Get-PSResourceRepository | Where-Object -Property Name -EQ $Name))
{
    $Splat = @{
       Name               = $Name
        Uri                   = $Location
        Trusted            = $true
        CredentialInfo = ([Microsoft.PowerShell.PSResourceGet.UtilClasses.PSCredentialInfo]::new($VaultName, $Name))
    }
    Register-PSResourceRepository @Splat
}

Write-Information "Here's where all that scaffolding finally crashes"
Find-PSResource -Name MyCustomModule -Repository $Name
Write-Information "Here's another angle to hit it from"
Install-PSResource -Name MyCustomModule -Repository $Name -Scope CurrentUser
```

I stripped out as much organization-specific information as I could find, so the errors might not exactly line up.

Btw, @SydneyhSmith  I listened to your interview on The PowerShell Podcast, and there's always going to be those people that are rude or say outrageous things. But my experience is that they have their own issues and it's nothing to do with the wonderful work you all are doing here. PowerShellGet v2 was SO slow and my measurements show that this module at least doubled our speed on the build servers. I'd really like to have that compatibility layer you talked about because I see quite a learning curve for new users of PowerShell as far as passing credentials to a repository.

### Expected behavior

```console
It should find/install the module like PowerShellGet v2 does, except without having to pass the -Credential parameter every time. I.e.


Install-Module -Name MyCustomModule -Repository $Name -Credential $Credential


Doesn't use the credential for some reason with this old module if it's registered with that same credential.
```

### Actual behavior

```console
Doesn't do anything but throw an error.
```

### Error details

```console
Exception             :
    Type       : System.NullReferenceException
    TargetSite :
        Name          : MoveNext
        DeclaringType : Microsoft.PowerShell.PSResourceGet.Cmdlets.FindHelper+<SearchByNames>d__19, Microsoft.PowerShell.PSResourceGet, Version=0.5.22.0, Culture=neutral, PublicKeyToken=null
        MemberType    : Method
        Module        : Microsoft.PowerShell.PSResourceGet.dll
    Message    : Object reference not set to an instance of an object.
    Source     : Microsoft.PowerShell.PSResourceGet
    HResult    : -2147467261
    StackTrace :
   at Microsoft.PowerShell.PSResourceGet.Cmdlets.FindHelper.SearchByNames(ServerApiCall currentServer, ResponseUtil currentResponseUtil, PSRepositoryInfo repository)+MoveNext()
   at Microsoft.PowerShell.PSResourceGet.Cmdlets.FindHelper.FindByResourceName(String[] name, ResourceType type, VersionRange versionRange, NuGetVersion nugetVersion, VersionType versionType, String  
version, Boolean prerelease, String[] tag, String[] repository, Boolean includeDependencies)+MoveNext()
   at Microsoft.PowerShell.PSResourceGet.Cmdlets.FindPSResource.ProcessResourceNameParameterSet()
   at Microsoft.PowerShell.PSResourceGet.Cmdlets.FindPSResource.ProcessRecord()
   at System.Management.Automation.CommandProcessor.ProcessRecord()
CategoryInfo          : NotSpecified: (:) [Find-PSResource], NullReferenceException
FullyQualifiedErrorId : System.NullReferenceException,Microsoft.PowerShell.PSResourceGet.Cmdlets.FindPSResource
InvocationInfo        :
    MyCommand        : Find-PSResource
    ScriptLineNumber : 1
    OffsetInLine     : 1
    HistoryId        : 135
    Line             : Find-PSResource -Name MyCustomModule -Repository shared-powershell-hosted-dev
    PositionMessage  : At line:1 char:1
                       + Find-PSResource -Name MyCustomModule -Repository shared-powershell-hosted-dev
                       + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    InvocationName   : Find-PSResource
    CommandOrigin    : Internal
ScriptStackTrace      : at <ScriptBlock>, <No file>: line 1
and
Exception             :
    Type       : System.ArgumentException
    Message    : Repository shared-powershell-hosted-dev has unknown API Version.
    TargetSite :
        Name          : ThrowTerminatingError
        DeclaringType : System.Management.Automation.MshCommandRuntime, System.Management.Automation, Version=7.3.5.500, Culture=neutral, PublicKeyToken=31bf3856ad364e35
        MemberType    : Method
        Module        : System.Management.Automation.dll
    Source     : System.Management.Automation
    HResult    : -2147024809
    StackTrace :
   at System.Management.Automation.MshCommandRuntime.ThrowTerminatingError(ErrorRecord errorRecord)
TargetObject          : Microsoft.PowerShell.PSResourceGet.Cmdlets.InstallHelper
CategoryInfo          : InvalidOperation: (Microsoft.PowerShel…dlets.InstallHelper:InstallHelper) [Install-PSResource], ArgumentException
FullyQualifiedErrorId : RepositoryAPIVersionUnknownError,Microsoft.PowerShell.PSResourceGet.Cmdlets.InstallPSResource
InvocationInfo        :
    MyCommand        : Install-PSResource
    ScriptLineNumber : 1
    OffsetInLine     : 1
    HistoryId        : 151
    Line             : Install-PSResource -Name MyCustomModule -Repository $Name
    PositionMessage  : At line:1 char:1
                       + Install-PSResource -Name MyCustomModule -Repository $Name
                       + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    InvocationName   : Install-PSResource
    CommandOrigin    : Internal
ScriptStackTrace      : at <ScriptBlock>, <No file>: line 1
```

### Environment data

```powershell
ModuleType Version    PreRelease Name                                PSEdition ExportedCommands
---------- -------    ---------- ----                                --------- ----------------
Binary     0.5.22     beta22     Microsoft.PowerShell.PSResourceGet  Core,Desk {Find-PSResource, Get-InstalledPSResource, Get-PSRes…

Name                           Value
----                           -----
PSVersion                      7.3.5
PSEdition                      Core
GitCommitId                    7.3.5
OS                             Microsoft Windows 10.0.22621
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Visuals

_No response_

### PR DESCRIPTION
**Pull request by anamnavi**
# PR Summary

## PR Context
Undoes #1269 but resolves #938 in a different way
Resolves #1279 partially

## PR Checklist

- [ ] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [ ] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [ ] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [ ] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.
- **[Breaking changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)**
    - [ ] None
    - **OR**
    - [ ] [Documentation needed]()
        - [ ] Issue filed: 
- **User-facing changes**
    - [ ] Not Applicable
    - **OR**
    - [ ] [Documentation needed]()
        - [ ] Issue filed: 
- **Testing - New and feature**
    - [ ] N/A or can only be tested interactively
    - **OR**
    - [ ] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
- **Tooling**
    - [ ] I have considered the user experience from a tooling perspective and don't believe tooling will be impacted.
    - **OR**
    - [ ] I have considered the user experience from a tooling perspective and enumerated concerns in the summary.

### CODE REVIEW

File: src/code/RepositorySettings.cs [hunk 1]
```diff
@@ -97,6 +97,12 @@ public static PSRepositoryInfo AddToRepositoryStore(string repoName, Uri repoUri
                 throw new ArgumentException("Name cannot be null/empty, contain asterisk or be just whitespace");
             }
 
+            if (repoUri == null || !(repoUri.Scheme == System.Uri.UriSchemeHttp || repoUri.Scheme == System.Uri.UriSchemeHttps || repoUri.Scheme == System.Uri.UriSchemeFtp || repoUri.Scheme == System.Uri.UriSchemeFile || repoUri.Scheme.Equals("temp", StringComparison.OrdinalIgnoreCase)))
```
Comment (adityapatwardhan) [inline src/code/RepositorySettings.cs:101]: what is temp? maybe add a comment explaining that.

File: src/code/Utils.cs [hunk 2]
```diff
@@ -413,6 +413,7 @@ public static string FormatCredentialRequestExceptions(Exception exception)
             errorRecord = null;
             if (Uri.TryCreate(uriString, UriKind.Absolute, out uriResult))
             {
+                Console.WriteLine(uriResult.Scheme);
```
Comment (adityapatwardhan) [inline src/code/Utils.cs]: Seems like a debug statement. Please remove.

**Review by adityapatwardhan — CHANGES_REQUESTED** [review]

File: test/FindPSResourceTests/FindPSResourceV2Server.Tests.ps1 [hunk 3]
```diff
@@ -378,6 +378,17 @@ Describe 'Test HTTP Find-PSResource for V2 Server Protocol' -tags 'CI' {
...
         $res.Count | Should -BeGreaterOrEqual 7 
     }
+
+    It "not find resource and error handle when repository's ApiVersion is ApiVersion.unknown" {
+        Register-PSResourceRepository -Name "UnknownTypeRepo" -Uri "https://org.MyCompany.com/repository/shared-feed/" -Trusted
+        $repo = Get-PSResourceRepository -Name "UnknownTypeRepo"
+        $repo.ApiVersion = Microsoft.PowerShell.PSResourceGet.UtilClasses.ApiVersion.unknown
+
+        $res = Find-PSResource -Name "MyPackage" -Repository "UnknownTypeRepo" -ErrorAction SilentlyContinue -ErrorVariable err
+        $err.Count | Should -Not -Be 0
```
Comment (adityapatwardhan) [inline test/FindPSResourceTests/FindPSResourceV2Server.Tests.ps1]:
```suggestion
        $err | Should -HaveCount 0
```

File: test/InstallPSResourceTests/InstallPSResourceV2Server.Tests.ps1 [hunk 4]
```diff
@@ -533,6 +533,17 @@ Describe 'Test Install-PSResource for V2 Server scenarios' -tags 'CI' {
...
         $res.Name | Should -Be "Pester"
     }
+
+    It "not install resource and error handle when repository's ApiVersion is ApiVersion.unknown" {
+        Register-PSResourceRepository -Name "UnknownTypeRepo" -Uri "https://org.MyCompany.com/repository/shared-feed/" -Trusted
+        $repo = Get-PSResourceRepository -Name "UnknownTypeRepo"
+        $repo.ApiVersion = Microsoft.PowerShell.PSResourceGet.UtilClasses.ApiVersion.unknown
+
+        $res = Install-PSResource -Name "MyPackage" -Repository "UnknownTypeRepo" -ErrorAction SilentlyContinue -ErrorVariable err -PassThru
+        $err.Count | Should -Not -Be 0
```
Comment (adityapatwardhan) [inline test/InstallPSResourceTests/InstallPSResourceV2Server.Tests.ps1]:
```suggestion
        $err | Should -HaveCount 0
```

**Review by adityapatwardhan — CHANGES_REQUESTED** [review]

**Review by adityapatwardhan — APPROVED** [review]
