### PR TITLE
Set-PSResourceRepository ran without -ApiVersion param should not reset it for the repository

### LINKED ISSUE #1306: Set-PSResourceRepository sets ApiVersion for a repository to ApiVersion.Unknown
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://www.powershellgallery.com/packages/PSResourceGet)
- [X] Search the existing issues.

### Steps to reproduce

`Get-PSResourceRepository "PSGallery" | fl *`
ApiVersion should be v2

`Set-PSResourceRepository "PSGallery" -Priority 3`
`Get-PSResourceRepository "PSGallery" | fl *"`
ApiVersion is now unknown

### Expected behavior

```console
ApiVersion should be unchanged.
```

### Actual behavior

```console
ApiVersion is unknown
```

### Error details

_No response_

### Environment data

```powershell
Windows, PSCore 7
```

### Visuals

_No response_

### PR DESCRIPTION
**Pull request by anamnavi**
# PR Summary
Currently, running `Set-PSResourceRepository` without the `-ApiVersion` parameter takes on the default value of ApiVersion.Unknown and changes it for the specified repository from the actual value to "unknown". Since ApiVersion is considered nullable the parameter should be too.

## PR Context

Resolves #1306 #1302 #1299 #1325 #1331

## PR Checklist

- [x] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [x] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.
- **[Breaking changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)**
    - [ ] None
    - **OR**
    - [ ] [Documentation needed]()
        - [ ] Issue filed: 
- **User-facing changes**
    - [ ] Not Applicable
    - **OR**
    - [ ] [Documentation needed]()
        - [ ] Issue filed: 
- **Testing - New and feature**
    - [ ] N/A or can only be tested interactively
    - **OR**
    - [x] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
- **Tooling**
    - [ ] I have considered the user experience from a tooling perspective and don't believe tooling will be impacted.
    - **OR**
    - [ ] I have considered the user experience from a tooling perspective and enumerated concerns in the summary.

### CODE REVIEW

File: src/code/SetPSResourceRepository.cs [hunk 1]
```diff
@@ -86,7 +86,7 @@ public SwitchParameter Trusted
         /// Specifies the Api version of the repository to be set.
         /// </sumamry>
         [Parameter(ParameterSetName = NameParameterSet)]
-        public PSRepositoryInfo.APIVersion ApiVersion { get; set; }
+        public PSRepositoryInfo.APIVersion? ApiVersion { get; set; } = null;
```
Comment (adityapatwardhan) [inline src/code/SetPSResourceRepository.cs]: Can you use PSBoundParameters instead of relying on nullable.

**Review by adityapatwardhan — APPROVED** [review]
